import { useEffect, useMemo, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { ModalBase } from "@/shared/components/ModalBase";
import { ConfirmModal } from "@/shared/components/ConfirmModal";
import { Button } from "@/shared/components/ui/Button";
import { Icon } from "@/shared/components/Icon";
import { ApiError } from "@/shared/api/client";
import { useToast } from "@/shared/contexts/ToastContext";
import { RewardedAdSlot } from "./RewardedAdSlot";
import { useClaimAdReward } from "./useClaimAdReward";

/** Seconds the user must watch before the reward unlocks. */
export const REWARD_WATCH_SECONDS = 15;

/** Stable placement string the backend expects. */
export const REWARDED_MODAL_PLACEMENT = "modal_rewarded_v1" as const;

type Props = {
  /** Stable UUID generated by the opener (so re-renders don't churn it). */
  idempotencyKey: string;
  onClose: () => void;
};

export function RewardedAdModal({ idempotencyKey, onClose }: Props) {
  const { t } = useTranslation();
  const { showToast } = useToast();
  const claim = useClaimAdReward();

  const [secondsLeft, setSecondsLeft] = useState(REWARD_WATCH_SECONDS);
  const [confirmForfeit, setConfirmForfeit] = useState(false);
  const claimedRef = useRef(false);

  // Countdown — clears on unmount.
  useEffect(() => {
    if (secondsLeft <= 0) return;
    const id = window.setInterval(() => {
      setSecondsLeft((s) => (s > 0 ? s - 1 : 0));
    }, 1000);
    return () => window.clearInterval(id);
  }, [secondsLeft]);

  const timerExpired = secondsLeft <= 0;

  const handleClaim = () => {
    if (claimedRef.current || claim.isPending) return;
    claimedRef.current = true;
    claim.mutate(
      { idempotencyKey, placement: REWARDED_MODAL_PLACEMENT },
      {
        onSuccess: (res) => {
          showToast(
            t("ads.rewarded.toastSuccess", {
              defaultValue: "+{{count}} lingots earned",
              count: res.lingots_awarded,
            }),
            "success",
          );
          onClose();
        },
        onError: (err: unknown) => {
          if (err instanceof ApiError && err.status === 429) {
            showToast(
              t("ads.rewarded.toastAlreadyCredited", {
                defaultValue:
                  "Already credited for this watch — try again in a moment.",
              }),
              "info",
            );
            onClose();
            return;
          }
          // Re-arm so the user can retry on a transient failure.
          claimedRef.current = false;
          showToast(
            t("ads.rewarded.toastFailed", {
              defaultValue: "Couldn't claim reward — try again.",
            }),
            "error",
          );
        },
      },
    );
  };

  const handleClose = () => {
    // Pre-timer: silent dismissal, no confirm.
    if (!timerExpired) {
      onClose();
      return;
    }
    // Post-timer but already claiming / claimed: don't block on confirm.
    if (claim.isPending || claimedRef.current) {
      onClose();
      return;
    }
    // Post-timer, reward unclaimed: confirm forfeit.
    setConfirmForfeit(true);
  };

  const statusLabel = useMemo(() => {
    if (timerExpired) {
      return t("ads.rewarded.rewardReady", {
        defaultValue: "Reward ready — tap to claim",
      });
    }
    return t("ads.rewarded.countdown", {
      defaultValue: "Reward unlocks in {{count}}s…",
      count: secondsLeft,
    });
  }, [secondsLeft, timerExpired, t]);

  return (
    <>
      <ModalBase
        onClose={handleClose}
        title={t("ads.rewarded.title", {
          defaultValue: "Watch an ad to earn 5 lingots",
        })}
        maxWidth="max-w-md"
        // Backdrop click should follow the same forfeit semantics as the
        // X button: pre-timer = silent dismiss, post-timer = confirm.
        closeOnBackdrop
      >
        <div className="space-y-4 px-6 py-5">
          <div className="flex justify-center">
            <RewardedAdSlot className="max-w-full" />
          </div>

          <div
            className="flex items-center justify-center gap-2 text-sm font-medium text-text-secondary"
            aria-live="polite"
            data-testid="rewarded-status"
          >
            {timerExpired ? (
              <Icon name="check" size={16} className="text-success" aria-hidden />
            ) : null}
            <span>{statusLabel}</span>
          </div>

          <Button
            type="button"
            variant="primary"
            className="w-full"
            disabled={!timerExpired || claim.isPending}
            onClick={handleClaim}
            data-testid="rewarded-claim-button"
          >
            {claim.isPending
              ? t("ads.rewarded.claiming", { defaultValue: "Claiming…" })
              : t("ads.rewarded.claimCta", {
                  defaultValue: "Claim 5 lingots",
                })}
          </Button>
        </div>
      </ModalBase>

      {confirmForfeit ? (
        <ConfirmModal
          title={t("ads.rewarded.forfeitTitle", {
            defaultValue: "Forfeit reward?",
          })}
          message={t("ads.rewarded.forfeitMessage", {
            defaultValue:
              "You've finished the ad but haven't claimed your lingots yet. Close anyway?",
          })}
          cancelLabel={t("common.cancel", { defaultValue: "Cancel" })}
          confirmLabel={t("ads.rewarded.forfeitConfirm", {
            defaultValue: "Close without claiming",
          })}
          onCancel={() => setConfirmForfeit(false)}
          onConfirm={() => {
            setConfirmForfeit(false);
            onClose();
          }}
        />
      ) : null}
    </>
  );
}
