/**
 * PT m1 L4 — "Eu estou cansado" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m1-l4.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M1_L4_ATOMS: PtAtom[] = [
  atom({
    surface: "estou",
    meaningEn: "I am (temporary state)",
    partOfSpeech: "verb",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "está",
    meaningEn: "is / are (temporary state)",
    partOfSpeech: "verb",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "em",
    meaningEn: "in, at",
    partOfSpeech: "particle",
    fromModule: "m1",
    kind: "particle",
  }),
  atom({
    surface: "no",
    meaningEn: "in the (masc.) — em + o",
    partOfSpeech: "particle",
    fromModule: "m1",
    kind: "particle",
  }),
  atom({
    surface: "cansado",
    meaningEn: "tired",
    partOfSpeech: "adjective",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "feliz",
    meaningEn: "happy",
    partOfSpeech: "adjective",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "aqui",
    meaningEn: "here",
    partOfSpeech: "adverb",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "hospital",
    meaningEn: "hospital",
    partOfSpeech: "noun",
    fromModule: "m1",
    kind: "vocab",
    gender: "m",
    emoji: "🏥",
  }),
];
