/**
 * PT m3 L5 — "Que horas são?" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m3-l5.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M3_L5_ATOMS: PtAtom[] = [
  atom({
    surface: "são",
    meaningEn: "they are / it is (plural, for the hours)",
    partOfSpeech: "verb",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "duas",
    meaningEn: "two (f., for the hours)",
    partOfSpeech: "number",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "dois",
    meaningEn: "two",
    partOfSpeech: "number",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "três",
    meaningEn: "three",
    partOfSpeech: "number",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "quatro",
    meaningEn: "four",
    partOfSpeech: "number",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "dez",
    meaningEn: "ten",
    partOfSpeech: "number",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "reais",
    meaningEn: "reais (currency)",
    partOfSpeech: "noun",
    fromModule: "m3",
    kind: "vocab",
    gender: "m",
    emoji: "💰",
  }),
  atom({
    surface: "hora",
    meaningEn: "hour",
    partOfSpeech: "noun",
    fromModule: "m3",
    kind: "vocab",
    gender: "f",
    emoji: "🕐",
  }),
];
