/**
 * PT m4 L1 — "Meu nome é Sam" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m4-l1.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M4_L1_ATOMS: PtAtom[] = [
  atom({
    surface: "meu",
    meaningEn: "my (m.)",
    partOfSpeech: "determiner",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "minha",
    meaningEn: "my (f.)",
    partOfSpeech: "determiner",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "seu",
    meaningEn: "your / his / her (m.)",
    partOfSpeech: "determiner",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "sua",
    meaningEn: "your / his / her (f.)",
    partOfSpeech: "determiner",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "nome",
    meaningEn: "name",
    partOfSpeech: "noun",
    fromModule: "m4",
    kind: "vocab",
    gender: "m",
    emoji: "🪪",
  }),
  atom({
    surface: "mãe",
    meaningEn: "mother",
    partOfSpeech: "noun",
    fromModule: "m4",
    kind: "vocab",
    gender: "f",
    emoji: "👩",
  }),
  atom({
    surface: "pai",
    meaningEn: "father",
    partOfSpeech: "noun",
    fromModule: "m4",
    kind: "vocab",
    gender: "m",
    emoji: "👨",
  }),
];
