/**
 * PT m3 L3 — "Vou para o hotel" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m3-l3.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M3_L3_ATOMS: PtAtom[] = [
  atom({
    surface: "vou",
    meaningEn: "I go / I'm going",
    partOfSpeech: "verb",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "vai",
    meaningEn: "you go / he, she goes",
    partOfSpeech: "verb",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "vamos",
    meaningEn: "we go / let's go",
    partOfSpeech: "verb",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "para",
    meaningEn: "to / for",
    partOfSpeech: "particle",
    fromModule: "m3",
    kind: "particle",
  }),
  atom({
    surface: "hotel",
    meaningEn: "hotel",
    partOfSpeech: "noun",
    fromModule: "m3",
    kind: "vocab",
    gender: "m",
    emoji: "🏨",
  }),
  atom({
    surface: "praia",
    meaningEn: "beach",
    partOfSpeech: "noun",
    fromModule: "m3",
    kind: "vocab",
    gender: "f",
    emoji: "🏖",
  }),
  atom({
    surface: "ônibus",
    meaningEn: "bus",
    partOfSpeech: "noun",
    fromModule: "m3",
    kind: "vocab",
    gender: "m",
    emoji: "🚌",
  }),
  atom({
    surface: "amanhã",
    meaningEn: "tomorrow",
    partOfSpeech: "adverb",
    fromModule: "m3",
    kind: "vocab",
  }),
];
