/**
 * PT m1 L2 — "De onde você é?" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m1-l2.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M1_L2_ATOMS: PtAtom[] = [
  atom({
    surface: "de",
    meaningEn: "of / from",
    partOfSpeech: "particle",
    fromModule: "m1",
    kind: "particle",
  }),
  atom({
    surface: "onde",
    meaningEn: "where",
    partOfSpeech: "adverb",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "do",
    meaningEn: "of the / from the (masc.)",
    partOfSpeech: "particle",
    fromModule: "m1",
    kind: "particle",
  }),
  atom({
    surface: "da",
    meaningEn: "of the / from the (fem.)",
    partOfSpeech: "particle",
    fromModule: "m1",
    kind: "particle",
  }),
  atom({
    surface: "cidade",
    meaningEn: "city",
    partOfSpeech: "noun",
    fromModule: "m1",
    kind: "vocab",
    gender: "f",
  }),
  atom({
    surface: "país",
    meaningEn: "country",
    partOfSpeech: "noun",
    fromModule: "m1",
    kind: "vocab",
    gender: "m",
  }),
  atom({
    surface: "França",
    meaningEn: "France",
    partOfSpeech: "proper-noun",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "Califórnia",
    meaningEn: "California",
    partOfSpeech: "proper-noun",
    fromModule: "m1",
    kind: "vocab",
  }),
];
