/**
 * PT m1 L1 — "Eu sou Sam" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m1-l1.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M1_L1_ATOMS: PtAtom[] = [
  atom({
    surface: "olá",
    meaningEn: "hello",
    partOfSpeech: "interjection",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "eu",
    meaningEn: "I",
    partOfSpeech: "pronoun",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "você",
    meaningEn: "you",
    partOfSpeech: "pronoun",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "sou",
    meaningEn: "I am",
    partOfSpeech: "verb",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "é",
    meaningEn: "is / are",
    partOfSpeech: "verb",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "estudante",
    meaningEn: "student",
    partOfSpeech: "noun",
    fromModule: "m1",
    kind: "vocab",
    gender: "epicene",
    emoji: "🎓",
  }),
  atom({
    surface: "professor",
    meaningEn: "teacher (m)",
    partOfSpeech: "noun",
    fromModule: "m1",
    kind: "vocab",
    gender: "m",
    emoji: "👨‍🏫",
  }),
  atom({
    surface: "Brasil",
    meaningEn: "Brazil",
    partOfSpeech: "proper-noun",
    fromModule: "m1",
    kind: "vocab",
  }),
];
