/**
 * PT m4 L2 — "Quero isso" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m4-l2.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M4_L2_ATOMS: PtAtom[] = [
  atom({
    surface: "esse",
    meaningEn: "this / that (m.)",
    partOfSpeech: "determiner",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "essa",
    meaningEn: "this / that (f.)",
    partOfSpeech: "determiner",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "aquele",
    meaningEn: "that over there (m.)",
    partOfSpeech: "determiner",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "aquela",
    meaningEn: "that over there (f.)",
    partOfSpeech: "determiner",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "aquilo",
    meaningEn: "that thing over there",
    partOfSpeech: "pronoun",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "ali",
    meaningEn: "right there",
    partOfSpeech: "adverb",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "lá",
    meaningEn: "over there",
    partOfSpeech: "adverb",
    fromModule: "m4",
    kind: "vocab",
  }),
];
