/**
 * PT m3 L4 — "Durmo cedo" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m3-l4.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M3_L4_ATOMS: PtAtom[] = [
  atom({
    surface: "abro",
    meaningEn: "I open",
    partOfSpeech: "verb",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "abre",
    meaningEn: "you open / it opens",
    partOfSpeech: "verb",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "durmo",
    meaningEn: "I sleep",
    partOfSpeech: "verb",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "dorme",
    meaningEn: "you sleep / he, she sleeps",
    partOfSpeech: "verb",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "quarto",
    meaningEn: "room",
    partOfSpeech: "noun",
    fromModule: "m3",
    kind: "vocab",
    gender: "m",
    emoji: "🛏",
  }),
  atom({
    surface: "cedo",
    meaningEn: "early",
    partOfSpeech: "adverb",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "tarde",
    meaningEn: "late",
    partOfSpeech: "adverb",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "agora",
    meaningEn: "now",
    partOfSpeech: "adverb",
    fromModule: "m3",
    kind: "vocab",
  }),
];
