/**
 * PT m1 L3 — "Eu tenho uma família" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m1-l3.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M1_L3_ATOMS: PtAtom[] = [
  atom({
    surface: "tenho",
    meaningEn: "I have",
    partOfSpeech: "verb",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "um",
    meaningEn: "a / an (masculine)",
    partOfSpeech: "determiner",
    fromModule: "m1",
    kind: "vocab",
    gender: "m",
  }),
  atom({
    surface: "gato",
    meaningEn: "cat",
    partOfSpeech: "noun",
    fromModule: "m1",
    kind: "vocab",
    gender: "m",
    emoji: "🐱",
  }),
  atom({
    surface: "uma",
    meaningEn: "a / an (feminine)",
    partOfSpeech: "determiner",
    fromModule: "m1",
    kind: "vocab",
    gender: "f",
  }),
  atom({
    surface: "irmã",
    meaningEn: "sister",
    partOfSpeech: "noun",
    fromModule: "m1",
    kind: "vocab",
    gender: "f",
    emoji: "👧",
  }),
  atom({
    surface: "amigo",
    meaningEn: "friend",
    partOfSpeech: "noun",
    fromModule: "m1",
    kind: "vocab",
    gender: "m",
    emoji: "🧑‍🤝‍🧑",
  }),
  atom({
    surface: "família",
    meaningEn: "family",
    partOfSpeech: "noun",
    fromModule: "m1",
    kind: "vocab",
    gender: "f",
    emoji: "👨‍👩‍👧",
  }),
  atom({
    surface: "tem",
    meaningEn: "you have / he/she has",
    partOfSpeech: "verb",
    fromModule: "m1",
    kind: "vocab",
  }),
];
