/**
 * PT m2 L4 — "Moro em São Paulo" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m2-l4.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M2_L4_ATOMS: PtAtom[] = [
  atom({
    surface: "moro",
    meaningEn: "I live",
    partOfSpeech: "verb",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "mora",
    meaningEn: "you live / he, she lives",
    partOfSpeech: "verb",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "trabalhar",
    meaningEn: "to work",
    partOfSpeech: "verb",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "ele",
    meaningEn: "he",
    partOfSpeech: "pronoun",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "ela",
    meaningEn: "she",
    partOfSpeech: "pronoun",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "a gente",
    meaningEn: "we (spoken)",
    partOfSpeech: "phrase",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "inglês",
    meaningEn: "English",
    partOfSpeech: "noun",
    fromModule: "m2",
    kind: "vocab",
    gender: "m",
  }),
  atom({
    surface: "português",
    meaningEn: "Portuguese",
    partOfSpeech: "noun",
    fromModule: "m2",
    kind: "vocab",
    gender: "m",
  }),
];
