/**
 * PT m2 L5 — "Não falo português" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m2-l5.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M2_L5_ATOMS: PtAtom[] = [
  atom({
    surface: "falo",
    meaningEn: "I speak",
    partOfSpeech: "verb",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "também",
    meaningEn: "also",
    partOfSpeech: "adverb",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "nunca",
    meaningEn: "never",
    partOfSpeech: "adverb",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "sempre",
    meaningEn: "always",
    partOfSpeech: "adverb",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "tudo",
    meaningEn: "everything",
    partOfSpeech: "pronoun",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "bem",
    meaningEn: "well",
    partOfSpeech: "adverb",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "um pouco",
    meaningEn: "a little",
    partOfSpeech: "phrase",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "sim",
    meaningEn: "yes",
    partOfSpeech: "adverb",
    fromModule: "m2",
    kind: "vocab",
  }),
];
