/**
 * PT m1 L5 — "O que você gosta de fazer?" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m1-l5.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M1_L5_ATOMS: PtAtom[] = [
  atom({
    surface: "gosto",
    meaningEn: "I like",
    partOfSpeech: "verb",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "gosta",
    meaningEn: "you like / he or she likes",
    partOfSpeech: "verb",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "falar",
    meaningEn: "to speak, to talk",
    partOfSpeech: "verb",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "comer",
    meaningEn: "to eat",
    partOfSpeech: "verb",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "assistir",
    meaningEn: "to watch",
    partOfSpeech: "verb",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "filme",
    meaningEn: "movie, film",
    partOfSpeech: "noun",
    fromModule: "m1",
    kind: "vocab",
    gender: "m",
    emoji: "🎬",
  }),
  atom({
    surface: "música",
    meaningEn: "music",
    partOfSpeech: "noun",
    fromModule: "m1",
    kind: "vocab",
    gender: "f",
    emoji: "🎵",
  }),
  atom({
    surface: "pizza",
    meaningEn: "pizza",
    partOfSpeech: "noun",
    fromModule: "m1",
    kind: "vocab",
    gender: "f",
    emoji: "🍕",
  }),
];
