/**
 * PT m4 L4 — "Estou aprendendo" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m4-l4.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M4_L4_ATOMS: PtAtom[] = [
  atom({
    surface: "aprender",
    meaningEn: "to learn",
    partOfSpeech: "verb",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "aprendendo",
    meaningEn: "learning",
    partOfSpeech: "verb",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "esperar",
    meaningEn: "to wait",
    partOfSpeech: "verb",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "esperando",
    meaningEn: "waiting",
    partOfSpeech: "verb",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "trabalhando",
    meaningEn: "working",
    partOfSpeech: "verb",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "comendo",
    meaningEn: "eating",
    partOfSpeech: "verb",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "dormindo",
    meaningEn: "sleeping",
    partOfSpeech: "verb",
    fromModule: "m4",
    kind: "vocab",
  }),
];
