/**
 * PT m3 L2 — "Posso pagar com cartão?" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m3-l2.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M3_L2_ATOMS: PtAtom[] = [
  atom({
    surface: "posso",
    meaningEn: "I can",
    partOfSpeech: "verb",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "pode",
    meaningEn: "you can / he, she can",
    partOfSpeech: "verb",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "pagar",
    meaningEn: "to pay",
    partOfSpeech: "verb",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "cartão",
    meaningEn: "card",
    partOfSpeech: "noun",
    fromModule: "m3",
    kind: "vocab",
    gender: "m",
  }),
  atom({
    surface: "dinheiro",
    meaningEn: "money",
    partOfSpeech: "noun",
    fromModule: "m3",
    kind: "vocab",
    gender: "m",
    emoji: "💰",
  }),
  atom({
    surface: "ajudar",
    meaningEn: "to help",
    partOfSpeech: "verb",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "repetir",
    meaningEn: "to repeat",
    partOfSpeech: "verb",
    fromModule: "m3",
    kind: "vocab",
  }),
];
