/**
 * PT m4 L3 — "Onde fica o hotel?" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m4-l3.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M4_L3_ATOMS: PtAtom[] = [
  atom({
    surface: "fica",
    meaningEn: "is located / stays",
    partOfSpeech: "verb",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "fico",
    meaningEn: "I stay",
    partOfSpeech: "verb",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "perto",
    meaningEn: "near",
    partOfSpeech: "adverb",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "longe",
    meaningEn: "far",
    partOfSpeech: "adverb",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "rua",
    meaningEn: "street",
    partOfSpeech: "noun",
    fromModule: "m4",
    kind: "vocab",
    gender: "f",
    emoji: "🛣",
  }),
  atom({
    surface: "loja",
    meaningEn: "shop",
    partOfSpeech: "noun",
    fromModule: "m4",
    kind: "vocab",
    gender: "f",
    emoji: "🏪",
  }),
  atom({
    surface: "centro",
    meaningEn: "downtown",
    partOfSpeech: "noun",
    fromModule: "m4",
    kind: "vocab",
    gender: "m",
    emoji: "🏙",
  }),
];
