/**
 * PT m2 L2 — "A conta, por favor" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m2-l2.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M2_L2_ATOMS: PtAtom[] = [
  atom({
    surface: "o",
    meaningEn: "the (m.)",
    partOfSpeech: "determiner",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "a",
    meaningEn: "the (f.)",
    partOfSpeech: "determiner",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "os",
    meaningEn: "the (m. pl.)",
    partOfSpeech: "determiner",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "as",
    meaningEn: "the (f. pl.)",
    partOfSpeech: "determiner",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "casa",
    meaningEn: "house",
    partOfSpeech: "noun",
    fromModule: "m2",
    kind: "vocab",
    gender: "f",
    emoji: "🏠",
  }),
  atom({
    surface: "dia",
    meaningEn: "day",
    partOfSpeech: "noun",
    fromModule: "m2",
    kind: "vocab",
    gender: "m",
    emoji: "🌞",
  }),
  atom({
    surface: "conta",
    meaningEn: "bill",
    partOfSpeech: "noun",
    fromModule: "m2",
    kind: "vocab",
    gender: "f",
    emoji: "🧾",
  }),
  atom({
    surface: "pão",
    meaningEn: "bread",
    partOfSpeech: "noun",
    fromModule: "m2",
    kind: "vocab",
    gender: "m",
    emoji: "🍞",
  }),
];
