/**
 * PT m1 L6 — "Eu sou, estou, tenho e gosto" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m1-l6.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M1_L6_ATOMS: PtAtom[] = [
  atom({
    surface: "sou",
    meaningEn: "I am",
    partOfSpeech: "verb",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "é",
    meaningEn: "is / are (you, he, she)",
    partOfSpeech: "verb",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "estou",
    meaningEn: "I am (temporary state)",
    partOfSpeech: "verb",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "está",
    meaningEn: "is / are (temporary state)",
    partOfSpeech: "verb",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "tenho",
    meaningEn: "I have",
    partOfSpeech: "verb",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "tem",
    meaningEn: "you have / he/she has",
    partOfSpeech: "verb",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "gosto",
    meaningEn: "I like",
    partOfSpeech: "verb",
    fromModule: "m1",
    kind: "vocab",
  }),
  atom({
    surface: "gosta",
    meaningEn: "you like / he or she likes",
    partOfSpeech: "verb",
    fromModule: "m1",
    kind: "vocab",
  }),
];
