/**
 * PT m3 L1 — "Não entendo" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m3-l1.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M3_L1_ATOMS: PtAtom[] = [
  atom({
    surface: "bebo",
    meaningEn: "I drink",
    partOfSpeech: "verb",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "bebe",
    meaningEn: "you drink / he, she drinks",
    partOfSpeech: "verb",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "entendo",
    meaningEn: "I understand",
    partOfSpeech: "verb",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "entende",
    meaningEn: "you understand / he, she understands",
    partOfSpeech: "verb",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "leite",
    meaningEn: "milk",
    partOfSpeech: "noun",
    fromModule: "m3",
    kind: "vocab",
    gender: "m",
    emoji: "🥛",
  }),
  atom({
    surface: "suco",
    meaningEn: "juice",
    partOfSpeech: "noun",
    fromModule: "m3",
    kind: "vocab",
    gender: "m",
    emoji: "🧃",
  }),
  atom({
    surface: "devagar",
    meaningEn: "slowly",
    partOfSpeech: "adverb",
    fromModule: "m3",
    kind: "vocab",
  }),
  atom({
    surface: "hoje",
    meaningEn: "today",
    partOfSpeech: "adverb",
    fromModule: "m3",
    kind: "vocab",
  }),
];
