/**
 * PT m2 L1 — "Quero um café" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m2-l1.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M2_L1_ATOMS: PtAtom[] = [
  atom({
    surface: "quero",
    meaningEn: "I want",
    partOfSpeech: "verb",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "quer",
    meaningEn: "you want / he, she wants",
    partOfSpeech: "verb",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "água",
    meaningEn: "water",
    partOfSpeech: "noun",
    fromModule: "m2",
    kind: "vocab",
    gender: "f",
    emoji: "💧",
  }),
  atom({
    surface: "café",
    meaningEn: "coffee",
    partOfSpeech: "noun",
    fromModule: "m2",
    kind: "vocab",
    gender: "m",
    emoji: "☕",
  }),
  atom({
    surface: "mais",
    meaningEn: "more",
    partOfSpeech: "adverb",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "por favor",
    meaningEn: "please",
    partOfSpeech: "phrase",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "obrigado",
    meaningEn: "thank you (said by a man)",
    partOfSpeech: "phrase",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "obrigada",
    meaningEn: "thank you (said by a woman)",
    partOfSpeech: "phrase",
    fromModule: "m2",
    kind: "vocab",
  }),
];
