/**
 * PT m4 L5 — "Preciso de um médico" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m4-l5.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M4_L5_ATOMS: PtAtom[] = [
  atom({
    surface: "preciso",
    meaningEn: "I need",
    partOfSpeech: "verb",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "precisa",
    meaningEn: "you need / he, she needs",
    partOfSpeech: "verb",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "ajuda",
    meaningEn: "help",
    partOfSpeech: "noun",
    fromModule: "m4",
    kind: "vocab",
    gender: "f",
  }),
  atom({
    surface: "médico",
    meaningEn: "doctor",
    partOfSpeech: "noun",
    fromModule: "m4",
    kind: "vocab",
    gender: "m",
  }),
  atom({
    surface: "sair",
    meaningEn: "to leave",
    partOfSpeech: "verb",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "voltar",
    meaningEn: "to come back",
    partOfSpeech: "verb",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "até amanhã",
    meaningEn: "see you tomorrow",
    partOfSpeech: "phrase",
    fromModule: "m4",
    kind: "vocab",
  }),
  atom({
    surface: "tenho que",
    meaningEn: "I have to",
    partOfSpeech: "phrase",
    fromModule: "m4",
    kind: "vocab",
  }),
];
