/**
 * PT m2 L3 — "Onde é o banheiro?" — GENERATED by
 * scripts/author/pt/from-spec.mjs from specs/pt-m2-l3.yaml. Do not
 * hand-edit; regenerate instead.
 */
import { atom, type PtAtom } from "./courseAtoms";

export const PT_M2_L3_ATOMS: PtAtom[] = [
  atom({
    surface: "o que",
    meaningEn: "what",
    partOfSpeech: "phrase",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "quem",
    meaningEn: "who",
    partOfSpeech: "pronoun",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "como",
    meaningEn: "how",
    partOfSpeech: "adverb",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "quanto",
    meaningEn: "how much",
    partOfSpeech: "adverb",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "banheiro",
    meaningEn: "bathroom",
    partOfSpeech: "noun",
    fromModule: "m2",
    kind: "vocab",
    gender: "m",
    emoji: "🚻",
  }),
  atom({
    surface: "isso",
    meaningEn: "this / that (thing)",
    partOfSpeech: "pronoun",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "caro",
    meaningEn: "expensive",
    partOfSpeech: "adjective",
    fromModule: "m2",
    kind: "vocab",
  }),
  atom({
    surface: "custa",
    meaningEn: "it costs (chunk: Quanto custa?)",
    partOfSpeech: "phrase",
    fromModule: "m2",
    kind: "vocab",
  }),
];
