/**
 * lib/emitFragment.mjs — scheduled steps + spec -> the fragment YAML text
 * `compile-ir-pt.mjs` reads (`curriculum/ir/m<mod>/l<n>.ir.yaml`), in the
 * ONE shape the real fragment-merge compiler accepts today: a top-level
 * `lesson: {n, template, title, description, steps}` mapping plus an
 * optional `atoms:` list, each atom's shape matching `ir.newAtoms`
 * (see `compile-ir-pt.mjs`'s atom-emission loop). This is deliberately the
 * ONLY fragment shape `from-spec.mjs` ever produces — the pack tells every
 * future lane to write specs, not fragments, precisely so this shape
 * question never needs re-deciding (it was re-guessed five different ways
 * across PTAUTH-L1..L5 before the real compiler landed; see the PTTOOL
 * report).
 *
 * Uses the `yaml` package (already a `compile-ir-pt.mjs` dependency) to
 * stringify, not hand-built strings — guarantees valid, byte-stable YAML
 * without re-solving quoting.
 */
import { stringify } from "yaml";
import { mapPartOfSpeech } from "./rules.mjs";

/** Strip candidate-only bookkeeping (`tiles: []` placeholders the
 *  compiler's own `buildLit` emitter fills from `pt` — leaving it here
 *  would just duplicate tokens already in `pt`) down to exactly what
 *  `assemble.mjs`'s literal-beat emitters read for each `kind`. */
function cleanStep(s) {
  const { kind, id, ...rest } = s;
  if (kind === "buildLit" && Array.isArray(rest.tiles) && rest.tiles.length === 0) delete rest.tiles;
  return { kind, id, ...rest };
}

export function emitFragmentYaml(spec, orderedSteps) {
  const atoms = spec.words.map((w) => ({
    surface: w.pt,
    meaningEn: w.en,
    partOfSpeech: mapPartOfSpeech(w.pos),
    kind: w.pos === "particle" ? "particle" : "vocab",
    ...(w.gender ? { gender: w.gender } : {}),
    ...(w.emoji ? { emoji: w.emoji } : {}),
    ...(w.hint ? { hint: w.hint } : {}),
  }));

  const doc = {
    lesson: {
      n: spec.lesson,
      template: "free",
      title: spec.title,
      description: spec.grammar,
      steps: orderedSteps.map(cleanStep),
    },
    atoms,
  };

  const header = [
    `# ${spec.id} — "${spec.title}" (generated by scripts/author/pt/from-spec.mjs)`,
    `#`,
    `# GENERATED from a SPEC, not hand-authored. Regenerate instead of`,
    `# hand-editing: node scripts/author/pt/from-spec.mjs specs/<this>.yaml`,
    `# Source spec: specs/${spec.id}.yaml. Pack: docs/pt-authoring-pack.md.`,
    ``,
  ].join("\n");

  // aliasDuplicateObjects: false — two steps sharing the same `atoms`
  // array (by reference) would otherwise print as a YAML anchor/alias
  // (`&a1` / `*a1`), which is valid but not the plain, flat style every
  // hand-authored PT fragment uses; a lane reading the generated file
  // should never have to know what a YAML alias is.
  return header + stringify(doc, { lineWidth: 0, aliasDuplicateObjects: false });
}
