/**
 * lib/emitAtomsTs.mjs — spec.words -> `courseAtoms.m<mod>-l<n>.ts`, the
 * same hand-authored shape every PTAUTH-L1..L5 lane wrote (see
 * `src/features/languages/pt/courseAtoms.m1-l2.ts`): a side-effect-import
 * file whose `atom({...})` calls register into the live registry, exported
 * as `PT_M<mod>_L<n>_ATOMS` for direct read access too.
 *
 * NOTE this is generated ALONGSIDE the IR fragment's own `atoms:` list
 * (same data, two consumers) — exactly the redundancy
 * `courseAtoms.m1-l2.ts`'s own header names as deliberate until PT's
 * fragment-merge compiler is the only place atoms are read from. Once that
 * day comes, dropping this file's generation is a one-line change in
 * `from-spec.mjs`, not a redesign.
 */
import { mapPartOfSpeech } from "./rules.mjs";

const q = (s) => JSON.stringify(s);

export function emitAtomsTs(spec) {
  // Module is always m1 for this lane's scope (PTTOOL proves the tool on
  // m1; a future module needs only a one-line change here to parameterize).
  const exportName = `PT_M1_L${spec.lesson}_ATOMS`;
  const calls = spec.words.map((w) => {
    const fields = [
      `surface: ${q(w.pt)}`,
      `meaningEn: ${q(w.en)}`,
      `partOfSpeech: ${q(mapPartOfSpeech(w.pos))}`,
      `fromModule: "m1"`,
      `kind: ${q(w.pos === "particle" ? "particle" : "vocab")}`,
    ];
    if (w.gender) fields.push(`gender: ${q(w.gender)}`);
    if (w.emoji) fields.push(`emoji: ${q(w.emoji)}`);
    if (w.hint) fields.push(`hint: ${q(w.hint)}`);
    return `  atom({\n    ${fields.join(",\n    ")},\n  }),`;
  });

  return [
    `/**`,
    ` * PT m1 L${spec.lesson} — "${spec.title}" — GENERATED by`,
    ` * scripts/author/pt/from-spec.mjs from specs/${spec.id}.yaml. Do not`,
    ` * hand-edit; regenerate instead.`,
    ` */`,
    `import { atom, type PtAtom } from "./courseAtoms";`,
    ``,
    `export const ${exportName}: PtAtom[] = [`,
    ...calls,
    `];`,
    ``,
  ].join("\n");
}
