/**
 * lib/emitFragment.mjs — scheduled steps + spec -> the fragment YAML text
 * `compile-ir-pt.mjs` reads (`curriculum/ir/m<mod>/l<n>.ir.yaml`), in the
 * ONE shape the real fragment-merge compiler accepts today: a top-level
 * `lesson: {n, template, title, description, steps}` mapping plus an
 * optional `atoms:` list, each atom's shape matching `ir.newAtoms`
 * (see `compile-ir-pt.mjs`'s atom-emission loop). This is deliberately the
 * ONLY fragment shape `from-spec.mjs` ever produces.
 *
 * Uses the `yaml` package (already a `compile-ir-pt.mjs` dependency) to
 * stringify, not hand-built strings — guarantees valid, byte-stable YAML
 * without re-solving quoting.
 *
 * ROUND 2 (lane PTTOOL2):
 *  - `checkpoint: true` emits `atoms: []` unconditionally (coordinator
 *    finding a — a checkpoint recalls already-registered surfaces; it must
 *    never re-register them as new atoms, which is what PTR1-L6's `words:`
 *    workaround did).
 *  - Every printed `pt`/`en`/`sentence`/`text`/`prompt` string is run
 *    through `normalizeSentence` (PTGRADE capitalization + terminal-
 *    punctuation finding) before emission.
 *  - The info step's `antiPattern` (structured `{ok, wrong}`) is carried
 *    as an extra field on the `info` step — forward-compat metadata for
 *    the real emitter (editing `assemble.mjs` is out of this lane's scope;
 *    see the pack's "known gaps").
 *  - `allow: spec.allow` round-trips onto the fragment doc itself (not a
 *    step) so `check-lesson.mjs`'s independent taught-vocabulary residual
 *    check can read the same declared function-word allowlist the spec
 *    author wrote, without re-parsing the spec.
 */
import { stringify } from "yaml";
import { mapPartOfSpeech } from "./rules.mjs";
import { normalizeSentence } from "./normalizeText.mjs";

const TEXT_FIELDS = ["pt", "en", "sentence", "text", "prompt", "correct"];

function normalizeStepText(s) {
  const out = { ...s };
  for (const f of TEXT_FIELDS) if (typeof out[f] === "string") out[f] = normalizeSentence(out[f]);
  if (Array.isArray(out.distractors) && out.kind === "mcq") out.distractors = out.distractors.map(normalizeSentence);
  if (Array.isArray(out.distractorsEn)) out.distractorsEn = out.distractorsEn.map(normalizeSentence);
  if (out.segments) out.segments = out.segments.map((seg) => (seg.text ? { ...seg, text: seg.text } : seg)); // agreementLit text fragments keep their own spacing; not sentence-normalized
  return out;
}

/** Strip candidate-only bookkeeping (`_ord` scheduling metadata, `tiles: []`
 *  placeholders the compiler's own `buildLit` emitter fills from `pt`) down
 *  to exactly what `assemble.mjs`'s literal-beat emitters read for each
 *  `kind`. */
function cleanStep(s, spec) {
  const { kind, id, _ord, ...rest } = normalizeStepText(s);
  if (kind === "buildLit" && Array.isArray(rest.tiles) && rest.tiles.length === 0) delete rest.tiles;
  if (kind === "info" && spec.antiPattern) rest.antiPattern = spec.antiPattern;
  return { kind, id, ...rest };
}

export function emitFragmentYaml(spec, orderedSteps) {
  const atoms = spec.checkpoint
    ? []
    : spec.words.map((w) => ({
        surface: w.pt,
        meaningEn: w.en,
        partOfSpeech: mapPartOfSpeech(w.pos),
        kind: w.pos === "particle" ? "particle" : "vocab",
        ...(w.gender ? { gender: w.gender } : {}),
        ...(w.emoji ? { emoji: w.emoji } : {}),
        ...(w.hint ? { hint: w.hint } : {}),
        // ROUND 3 (lane PTTOOL3, rule 2): only carried when a noun opted
        // OUT of imageMcq — lets `lib/checkRules.mjs`'s independent
        // re-check tell "imageable: false, documented" apart from a
        // hand-edit that silently deleted a noun's `emoji` field, without
        // re-parsing the spec.
        ...(w.pos === "noun" && w.imageable === false ? { imageable: false, imageableReason: w.imageableReason } : {}),
      }));

  const doc = {
    lesson: {
      n: spec.lesson,
      template: "free",
      title: spec.title,
      description: spec.grammar,
      // ROUND 3 (lane PTTOOL3, rule 1): carried through ONLY when true, so
      // `lib/checkRules.mjs`'s independent dialogue-mandatory re-check can
      // tell a checkpoint fragment (module law: matchLit -> speakLit ->
      // sim) from a regular one (sim -> matchLit -> speakLit-win) without
      // re-parsing the spec that generated it — an extra field the real
      // compiler (`compile-ir-pt.mjs`/`assemble.mjs`) already tolerates
      // and ignores (same precedent as the `info` step's `antiPattern`).
      ...(spec.checkpoint ? { checkpoint: true } : {}),
      steps: orderedSteps.map((s) => cleanStep(s, spec)),
    },
    atoms,
    ...(spec.allow.length ? { allow: spec.allow } : {}),
  };

  const header = [
    `# ${spec.id} — "${spec.title}" (generated by scripts/author/pt/from-spec.mjs)`,
    `#`,
    `# GENERATED from a SPEC, not hand-authored. Regenerate instead of`,
    `# hand-editing: node scripts/author/pt/from-spec.mjs specs/<this>.yaml`,
    `# Source spec: specs/${spec.id}.yaml. Pack: docs/pt-authoring-pack.md.`,
    ``,
  ].join("\n");

  // aliasDuplicateObjects: false — two steps sharing the same `atoms`
  // array (by reference) would otherwise print as a YAML anchor/alias
  // (`&a1` / `*a1`), which is valid but not the plain, flat style every
  // hand-authored PT fragment uses; a lane reading the generated file
  // should never have to know what a YAML alias is.
  return header + stringify(doc, { lineWidth: 0, aliasDuplicateObjects: false });
}
