/** Culture stories — festivals, customs, and everyday cultural context. */
import type { Story } from "../types";

export const JA_CULTURE_STORIES: Story[] = [
  {
    // The earliest module that can carry hanami at all: さくら/はな/いけ are m1-m2,
    // こうえん/みせ m6, and m9 finally supplies にぎやか/しずか/ゆうめい — the three
    // words the whole arc turns on (a famous park, too loud, a quiet corner).
    // Polite, per the m3-m10 default. Present throughout: m9 has no past form.
    id: "ja-m9-hanami",
    languageId: "ja",
    module: 9,
    level: 3,
    title: "Under the cherry trees",
    theme: "A famous park on a spring afternoon, and a quieter corner of it.",
    tags: ["culture", "festival", "spring", "park"],
    glosses: [
      { surface: "はなみ", meaning: "flower viewing — sitting under the cherry blossoms with food and drink" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "いけの あそこは どうですか。",
        options: ["しずかです", "にぎやかです", "ゆうめいです"],
        answer: "しずかです",
      },
      {
        id: "tea",
        kind: "detail",
        prompt: "おちゃは いくらですか。",
        options: ["にひゃくえんです", "ひゃくえんです", "ごひゃくえんです"],
        answer: "にひゃくえんです",
      },
    ],
    sentences: [
      { text: "きょう、わたしは ともだちと こうえんに いきます。", translation: "Today I go to the park with a friend." },
      { text: "この こうえんの さくらは とても ゆうめいです。", translation: "This park's cherry blossoms are very famous." },
      { text: "ふたりで はなみを します。", translation: "The two of us do hanami." },
      { text: "こうえんは とても にぎやかです。", translation: "The park is very lively." },
      { text: "ここは しずかじゃないです。", translation: "It is not quiet here." },
      { text: "ともだちは いけの あそこに いきます。", translation: "My friend goes over there by the pond." },
      { text: "わたしも いきます。", translation: "I go too." },
      { text: "あそこに ひとが すこし います。", translation: "There are a few people over there." },
      { text: "あそこは しずかです。", translation: "It is quiet over there." },
      { text: "みずに さくらの はなが あります。", translation: "There are cherry blossoms on the water." },
      { text: "ふたりで ごはんを たべます。", translation: "The two of us eat a meal." },
      { text: "おちゃが ありません。", translation: "We have no tea." },
      { text: "それから、わたしは みせで おちゃを かいます。", translation: "After that I buy tea at the shop." },
      { text: "おちゃは にひゃくえんです。", translation: "The tea is two hundred yen." },
      { text: "いけの あそこの はなみは とても おもしろいです。", translation: "Hanami over there by the pond is very interesting." },
    ],
  },
  {
    // m12 is the first module that has コンビニ at all, so it is the earliest the
    // topic can be written. Polite (m12 carries one polite and one plain story
    // already). Present throughout — of the polite past forms only かいました
    // gates, so a past narration is not writable here.
    id: "ja-m12-the-late-night-shop",
    languageId: "ja",
    module: 12,
    level: 3,
    title: "The late-night shop",
    theme: "Eleven at night, an empty kitchen, and a visitor who has never seen a konbini.",
    tags: ["culture", "food", "town"],
    glosses: [
      { surface: "おにぎり", meaning: "rice ball wrapped in seaweed" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "コンビニは どうですか。",
        options: ["べんりです", "たかいです", "しずかです"],
        answer: "べんりです",
      },
      {
        id: "price",
        kind: "detail",
        prompt: "おにぎりは いくらですか。",
        options: ["ひゃくごじゅうえんです", "ひゃくえんです", "ごひゃくえんです"],
        answer: "ひゃくごじゅうえんです",
      },
    ],
    sentences: [
      { text: "こんしゅう、アメリカの ともだちの トムが にほんに きます。", translation: "This week my American friend Tom is coming to Japan." },
      { text: "トムは えきの ホテルに います。", translation: "Tom is at the hotel by the station." },
      { text: "いまは よる じゅういちじです。", translation: "It is eleven at night now." },
      { text: "うちに ごはんが ありません。", translation: "There is no food at my house." },
      { text: "ふたりで コンビニに いきます。", translation: "The two of us go to the convenience store." },
      { text: "コンビニは うちに ちかいです。", translation: "The convenience store is close to my house." },
      { text: "よるの コンビニにも ひとが います。", translation: "There are people in the convenience store at night too." },
      { text: "トムは この みせを しりません。", translation: "Tom does not know this shop." },
      { text: "コンビニに パンも おにぎりも あります。", translation: "The convenience store has bread and onigiri." },
      { text: "ラーメンも コーヒーも ビールも あります。", translation: "It has ramen, coffee and beer too." },
      { text: "トムは おにぎりを かいます。", translation: "Tom buys an onigiri." },
      { text: "おにぎりは ひゃくごじゅうえんです。", translation: "The onigiri is a hundred and fifty yen." },
      { text: "わたしは ラーメンと コーヒーを かいます。", translation: "I buy ramen and a coffee." },
      { text: "アメリカの みせは よる ありません。", translation: "In America the shops are not there at night." },
      { text: "コンビニは ほんとうに べんりです。", translation: "The convenience store really is convenient." },
      { text: "あした、トムは また コンビニに いきます。", translation: "Tomorrow Tom goes to the convenience store again." },
    ],
  },
  {
    // m14 is the earliest module with せん/まん, so it is the first place an
    // otoshidama can carry a real amount — which is what the arc turns on. It
    // also hands over ふうとう, みせる, かす and the と-はなす quote frame, so the
    // envelope, the offer and the reply are all writable. Plain form (m13-m30
    // default), narrative present with a past coda (かった / だった are m11).
    id: "ja-m14-the-new-year-envelope",
    languageId: "ja",
    module: 14,
    level: 4,
    title: "The New Year envelope",
    theme: "New Year money, a camera that costs too much, and an older brother.",
    tags: ["culture", "festival", "family", "money"],
    glosses: [
      { surface: "おしょうがつ", meaning: "the New Year holiday" },
      { surface: "おとしだま", meaning: "New Year money given to children in a small envelope" },
      { surface: "じんじゃ", meaning: "a Shinto shrine" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "その あと、ドアに なにが ありますか。",
        options: ["あにの ふうとうです", "ちちの てがみです", "ははの ふうとうです"],
        answer: "あにの ふうとうです",
      },
      {
        id: "money",
        kind: "detail",
        prompt: "わたしの おとしだまは いくらですか。",
        options: ["いちまんえんです", "にまんえんです", "さんまんえんです"],
        answer: "いちまんえんです",
      },
    ],
    sentences: [
      { text: "ことしの おしょうがつだ。", translation: "It is New Year this year." },
      { text: "かぞくが うちに くる。", translation: "The family comes to my house." },
      { text: "ちちと ははと あにと わたし、よにんだ。", translation: "Father, Mother, my older brother and me — four of us." },
      { text: "ははの りょうりは とても おいしい。", translation: "Mother's cooking is very good." },
      { text: "わたしは ごはんを たべる。", translation: "I eat the meal." },
      { text: "おちゃも のむ。", translation: "I drink tea too." },
      { text: "あとで ちちが ふうとうを みせる。", translation: "Afterwards Father shows an envelope." },
      { text: "ふうとうに おとしだまが ある。", translation: "There is New Year money in the envelope." },
      { text: "わたしの おとしだまは いちまんえんだ。", translation: "My New Year money is ten thousand yen." },
      { text: "あにの おとしだまも いちまんえんだ。", translation: "My brother's New Year money is ten thousand yen too." },
      { text: "わたしは カメラが ほしい。", translation: "I want a camera." },
      { text: "その カメラは さんまんえんだ。", translation: "That camera is thirty thousand yen." },
      { text: "カメラは たかい。", translation: "The camera is expensive." },
      { text: "おかねが ない。", translation: "There is no money." },
      { text: "つぎの あさ、かぞくで じんじゃに いく。", translation: "The next morning the family goes to the shrine." },
      { text: "じんじゃは とても にぎやかだ。", translation: "The shrine is very crowded." },
      { text: "あには じんじゃで わたしに はなす。", translation: "At the shrine my brother speaks to me." },
      { text: "「ぼくの おとしだまを かす。」", translation: "\"I will lend you my New Year money.\"" },
      { text: "わたしは 「ありがとう」と はなす。", translation: "I say, \"Thank you.\"" },
      { text: "その あと、あにの ふうとうが ドアに ある。", translation: "After that my brother's envelope is at the door." },
      { text: "ふうとうに にまんえんが ある。", translation: "There is twenty thousand yen in the envelope." },
      { text: "わたしは カメラを かった。", translation: "I bought the camera." },
      { text: "ことしの おしょうがつは いい おしょうがつだった。", translation: "This year's New Year was a good New Year." },
    ],
  },
  {
    // m16 is the earliest module with はいる, and the onsen story is entirely a
    // story about entering things (the bath, the outdoor bath) plus the wash-first
    // rule, which needs さきに (m16) — まえ is m17. りょこう is m15. Plain form,
    // narrative present; あった / はいった do not gate at any module.
    id: "ja-m16-the-first-hot-spring",
    languageId: "ja",
    module: 16,
    level: 4,
    title: "The first hot spring",
    theme: "A mountain hotel, a rule nobody wrote down, and a bottle of milk.",
    tags: ["culture", "travel", "family"],
    glosses: [
      { surface: "おんせん", meaning: "a hot spring bath" },
      { surface: "ゆかた", meaning: "a light cotton robe worn at an inn" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "わたしは まいとし どこに いきますか。",
        options: ["おんせんに いきます", "がっこうに いきます", "としょかんに いきます"],
        answer: "おんせんに いきます",
      },
      {
        id: "drink",
        kind: "detail",
        prompt: "おんせんの あとで なにを のみますか。",
        options: ["ぎゅうにゅうです", "コーヒーです", "おちゃです"],
        answer: "ぎゅうにゅうです",
      },
    ],
    sentences: [
      { text: "なつやすみに かぞくで りょこうに いく。", translation: "In the summer holidays the family goes on a trip." },
      { text: "ホテルは やまに ある。", translation: "The hotel is in the mountains." },
      { text: "ホテルに おんせんが ある。", translation: "The hotel has a hot spring." },
      { text: "ホテルの ふくは ゆかただ。", translation: "The hotel's clothes are yukata." },
      { text: "わたしは おんせんに はじめて はいる。", translation: "I get into a hot spring for the first time." },
      { text: "わたしは おんせんの ことが わからない。", translation: "I do not understand hot springs." },
      { text: "ちちは わたしに おんせんの はなしを する。", translation: "Father tells me about hot springs." },
      { text: "「さきに からだを あらう。」", translation: "\"You wash your body first.\"" },
      { text: "これは たいせつだ。", translation: "This is important." },
      { text: "わたしは さきに せっけんで からだを あらう。", translation: "First I wash my body with soap." },
      { text: "それから おんせんに はいる。", translation: "Then I get into the hot spring." },
      { text: "みずが とても あつい。", translation: "The water is very hot." },
      { text: "わたしは そとに いく。", translation: "I go outside." },
      { text: "そとにも おんせんが ある。", translation: "There is a hot spring outside too." },
      { text: "そとの おんせんで やまを みる。", translation: "At the outdoor hot spring I look at the mountains." },
      { text: "ここは とても しずかだ。", translation: "It is very quiet here." },
      { text: "おんせんで およぐ ひとは いない。", translation: "Nobody swims in a hot spring." },
      { text: "おんせんは スポーツ じゃない。", translation: "A hot spring is not a sport." },
      { text: "わたしは しずかに すわる。", translation: "I sit quietly." },
      { text: "わたしは ながい じかん おんせんに はいる。", translation: "I stay in the hot spring for a long time." },
      { text: "あとで ぎゅうにゅうを のむ。", translation: "Afterwards I drink milk." },
      { text: "おんせんの あとの ぎゅうにゅうは とても おいしい。", translation: "Milk after a hot spring is very good." },
      { text: "いまは おんせんの ことが わかった。", translation: "Now I have understood hot springs." },
      { text: "まいとし おんせんに いく。", translation: "I go to a hot spring every year." },
    ],
  },
  {
    // m17 is the earliest module with のる / おりる / まえ / うしろ / よこ / そば —
    // the whole story is positional (who is in front, who is beside me), and the
    // manner is enforced by being looked at rather than told. Plain form. Note the
    // narrow plain-negative palette at this module: only たべない / いない / しない
    // gate, so every "nobody does X" is routed through ひとは いない.
    id: "ja-m17-the-quiet-carriage",
    languageId: "ja",
    module: 17,
    level: 3,
    title: "The quiet carriage",
    theme: "Eight o'clock, a bag of bread, and two people looking at me.",
    tags: ["culture", "town", "manners"],
    glosses: [
      { surface: "マナー", meaning: "manners, the way people behave in public" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "わたしは これから でんしゃで なにを しますか。",
        options: ["ほんを よみます", "パンを たべます", "はなしを します"],
        answer: "ほんを よみます",
      },
      {
        id: "carriage",
        kind: "detail",
        prompt: "でんしゃの なかは どうですか。",
        options: ["しずかです", "にぎやかです", "たかいです"],
        answer: "しずかです",
      },
    ],
    sentences: [
      { text: "でんしゃの なかは とても しずかだ。", translation: "Inside the train it is very quiet." },
      { text: "わたしは はちじの でんしゃに のる。", translation: "I get on the eight o'clock train." },
      { text: "わたしは まどの そばに すわる。", translation: "I sit by the window." },
      { text: "まえの ひとは ほんを よむ。", translation: "The person in front of me reads a book." },
      { text: "うしろの ひとは ねる。", translation: "The person behind me sleeps." },
      { text: "でんしゃで はなしを する ひとは いない。", translation: "Nobody talks on the train." },
      { text: "けいたいを つかう ひとも いない。", translation: "Nobody uses a phone either." },
      { text: "わたしは かばんから パンを とる。", translation: "I take bread out of my bag." },
      { text: "わたしは パンを たべる。", translation: "I eat the bread." },
      { text: "よこの ひとが わたしを みる。", translation: "The person beside me looks at me." },
      { text: "まえの ひとも わたしを みる。", translation: "The person in front of me looks at me too." },
      { text: "でんしゃで パンを たべる ひとは いない。", translation: "Nobody eats bread on the train." },
      { text: "わたしは でんしゃの マナーが わかった。", translation: "I understood the manners of the train." },
      { text: "わたしは もう たべない。", translation: "I do not eat any more." },
      { text: "つぎの えきで おりる。", translation: "I get off at the next station." },
      { text: "これから でんしゃで しずかに ほんを よむ。", translation: "From now on I read quietly on the train." },
    ],
  },
  {
    // Obon needs a grandmother, a return, and a crowd of adults and children —
    // おばあさん / かえる / おとな / こども / みんな all land together at m19, which
    // makes m19 the earliest module that can carry it. にわ / き / なつ are m18.
    // Plain form. じかん is used bare because Nじかん never gates (see report).
    id: "ja-m19-the-town-that-dances",
    languageId: "ja",
    module: 19,
    level: 4,
    title: "The town that dances",
    theme: "A long train ride I did not want to make, and a dance in the park.",
    tags: ["culture", "festival", "family", "summer"],
    glosses: [
      { surface: "おぼん", meaning: "Obon — the summer days when families return home" },
      { surface: "ぼんおどり", meaning: "the Bon dance, danced together in the town square" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "おぼんに かぞくは どこに いますか。",
        options: ["おばあさんの うちです", "こうえんです", "えきです"],
        answer: "おばあさんの うちです",
      },
      {
        id: "teacher",
        kind: "detail",
        prompt: "わたしに ぼんおどりを おしえる ひとは だれですか。",
        options: ["いもうとです", "おばあさんです", "ははです"],
        answer: "いもうとです",
      },
    ],
    sentences: [
      { text: "おばあさんの うちは とても とおい。", translation: "Grandmother's house is very far away." },
      { text: "なつの おぼんに かぞくで おばあさんの うちに かえる。", translation: "At Obon in summer the family goes back to Grandmother's house." },
      { text: "かぞくの よにんで でんしゃに のる。", translation: "The four of us in the family get on the train." },
      { text: "でんしゃの じかんは ながい。", translation: "The time on the train is long." },
      { text: "でんしゃは とても にぎやかだ。", translation: "The train is very crowded." },
      { text: "わたしは ながい でんしゃが きらいだ。", translation: "I hate long trains." },
      { text: "おぼんに みんな うちに かえる。", translation: "At Obon everyone goes home." },
      { text: "おばあさんの まちは ちいさい。", translation: "Grandmother's town is small." },
      { text: "にわに おおきな きが ある。", translation: "There is a big tree in the garden." },
      { text: "おばあさんは ななじゅうさいだ。", translation: "Grandmother is seventy." },
      { text: "おばあさんの ごはんは ほんとうに おいしい。", translation: "Grandmother's food is really good." },
      { text: "ゆうがた、まちの こうえんに いく。", translation: "In the evening we go to the town's park." },
      { text: "こうえんで まちの ひとが ぼんおどりを する。", translation: "In the park the people of the town do the Bon dance." },
      { text: "おとなも こどもも いる。", translation: "There are adults and there are children." },
      { text: "わたしは ぼんおどりが わからない。", translation: "I do not know the Bon dance." },
      { text: "いもうとが わたしに ぼんおどりを おしえる。", translation: "My little sister teaches me the Bon dance." },
      { text: "ぼんおどりは やさしい。", translation: "The Bon dance is easy." },
      { text: "おばあさんは こうえんの よこに すわる。", translation: "Grandmother sits beside the park." },
      { text: "おばあさんは まいとし ここに くる。", translation: "Grandmother comes here every year." },
      { text: "おぼんは かぞくの やすみだ。", translation: "Obon is the family's holiday." },
      { text: "わたしも まいとし ここに かえる。", translation: "I come back here every year too." },
      { text: "でんしゃの ながい じかんは ぜんぜん たいへんじゃない。", translation: "The long time on the train is not hard at all." },
    ],
  },
  {
    // The club story is really a story about せんぱい / こうはい / けいご / ためぐち,
    // and all four are m30 atoms — so m30 is the earliest module where it can be
    // told at all, and the only one where the register contrast is readable. L5
    // takes the register shift the level band explicitly allows: the same three
    // quoted words come back at the end with the roles reversed.
    id: "ja-m30-the-club",
    languageId: "ja",
    module: 30,
    level: 5,
    title: "The club",
    theme: "One wrong greeting on the first day, and the same greeting a year later.",
    tags: ["culture", "school", "manners"],
    glosses: [
      { surface: "ぶかつ", meaning: "a school club — daily after-school practice" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "ぶかつの せんぱいには なにが たいせつですか。",
        options: ["けいごです", "ためぐちです", "スポーツです"],
        answer: "けいごです",
      },
      {
        id: "tidy",
        kind: "detail",
        prompt: "こうはいが かたづける ところは どこですか。",
        options: ["きょうしつです", "ろうかです", "こうえんです"],
        answer: "きょうしつです",
      },
    ],
    sentences: [
      { text: "がっこうの ぶかつに はいる。", translation: "I join a school club." },
      { text: "わたしは スポーツの ぶかつを えらぶ。", translation: "I choose a sports club." },
      { text: "ぶかつは まいにち ごごに ある。", translation: "The club is every day in the afternoon." },
      { text: "はじめて ぶかつに いく。", translation: "I go to the club for the first time." },
      { text: "きょうしつに せんぱいが いる。", translation: "There is a senpai in the classroom." },
      { text: "わたしは せんぱいに 「こんにちは」と はなす。", translation: "I say \"Hello\" to the senpai." },
      { text: "せんぱいは わたしを みる。", translation: "The senpai looks at me." },
      { text: "せんぱいは ぜんぜん はなしを しない。", translation: "The senpai does not say anything at all." },
      { text: "クラスの ともだちが わたしに おしえる。", translation: "A friend from my class explains it to me." },
      { text: "「ぶかつの せんぱいには けいごを つかう」と ともだちは はなす。", translation: "\"With a club senpai you use keigo,\" my friend says." },
      { text: "ともだちは また 「ためぐちは しつれいだ」と はなす。", translation: "My friend also says, \"Tameguchi is rude.\"" },
      { text: "わたしは せんぱいに 「すみません」と はなす。", translation: "I say \"I am sorry\" to the senpai." },
      { text: "せんぱいは 「だいじょうぶ」と はなす。", translation: "The senpai says, \"It is fine.\"" },
      { text: "それから、わたしは まいにち れんしゅうする。", translation: "After that I practise every day." },
      { text: "わたしは よわい。", translation: "I am weak." },
      { text: "クラスの ともだちは わたしより つよい。", translation: "My friends from class are stronger than me." },
      { text: "だんだん わたしも じょうずに なる。", translation: "Little by little I get better too." },
      { text: "ぶかつの あとで、こうはいが きょうしつを かたづける。", translation: "After the club the kouhai tidy the classroom." },
      { text: "わたしも きょうしつを かたづける。", translation: "I tidy the classroom too." },
      { text: "せんぱいは さきに かえる。", translation: "The senpai goes home first." },
      { text: "わたしは いま ぶかつの なかまだ。", translation: "Now I am one of the club's members." },
      { text: "らいねん、あたらしい こうはいが くる。", translation: "Next year a new kouhai comes." },
      { text: "あたらしい こうはいは わたしに ためぐちで はなす。", translation: "The new kouhai speaks to me in tameguchi." },
      { text: "わたしは じぶんの はじめての ぶかつを おもう。", translation: "I think about my own first time at the club." },
      { text: "わたしは こうはいに 「だいじょうぶ」と はなす。", translation: "I say \"It is fine\" to the kouhai." },
      { text: "けいごは たいせつだ。", translation: "Keigo is important." },
      { text: "しかし、なかまは もっと たいせつだ。", translation: "But comrades are more important." },
    ],
  },
];
