/**
 * STORIES are newly authored for early-mid modules using only in-module
 * vocab (gate-verified). Density ramp: sparse early -> richer late.
 */
import type { Story } from "../types";

export const KO_STORIES: Story[] = [
  // ── Early (m3-m8): sparse, ~1 story per 2 modules ──────────────────────────
  {
    id: "ko-m3-new-friend",
    languageId: "ko",
    module: 3,
    level: 1,
    title: "A new classmate",
    theme: "Introducing yourself on the first day.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "이름이 뭐예요?",
        options: ["민수예요", "미나예요", "지수예요"],
        answer: "민수예요",
      },
    ],
    sentences: [
      { text: "안녕하세요.", translation: "Hello." },
      { text: "저는 학생이에요.", translation: "I'm a student." },
      { text: "이름이 민수예요.", translation: "My name is Minsu." },
      { text: "이름이 뭐예요?", translation: "What's your name?" },
      { text: "친구도 학생이에요.", translation: "My friend is a student too." },
      { text: "반갑습니다.", translation: "Nice to meet you." },
    ],
  },
  {
    // m3 stretch read (m3 caps at L2). Copula-only pool: the ONLY predicate
    // available is 이에요/예요, so the arc has to be carried by identity —
    // hence a mistaken-identity turn. 있어요 (m6) and 그런데 (m8) are the two
    // gloss slots; without 그런데 m3 has no connective at all.
    id: "ko-m3-who-is-that",
    languageId: "ko",
    module: 3,
    level: 2,
    title: "Is that Jisu?",
    theme: "A cheerful hello to entirely the wrong person.",
    tags: ["school", "greetings"],
    glosses: [
      { surface: "있어요", meaning: "there is, is (here)", atomId: "ko:있어요" },
      { surface: "그런데", meaning: "but, and yet", atomId: "ko:그런데" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "유진은 누구예요?",
        options: ["선생님이에요", "학생이에요", "친구예요"],
        answer: "선생님이에요",
      },
    ],
    sentences: [
      { text: "여기는 교실이에요.", translation: "This is the classroom." },
      { text: "교실에 학생이 있어요.", translation: "There are students in the classroom." },
      { text: "저는 민수예요.", translation: "I'm Minsu." },
      { text: "거기에 지수가 있어요?", translation: "Is that Jisu over there?" },
      { text: "안녕, 지수!", translation: "Hi, Jisu!" },
      { text: "아니요. 저는 유진이에요.", translation: "No. I'm Yujin." },
      { text: "그런데 유진 선생님이에요!", translation: "But she's Ms. Yujin, the teacher!" },
      { text: "죄송합니다!", translation: "I'm so sorry!" },
      { text: "괜찮아요. 반갑습니다.", translation: "It's all right. Nice to meet you." },
    ],
  },
  {
    // m4 stretch read. Same copula-only constraint as m3, so the arc is a
    // small identification mystery built out of m4's object nouns plus the
    // 제 거예요 / 누구 거예요 possessive frame m4 teaches.
    id: "ko-m4-whose-bag",
    languageId: "ko",
    module: 4,
    level: 2,
    title: "Whose bag?",
    theme: "A bag on a chair, and nobody claiming it.",
    tags: ["school", "objects"],
    glosses: [
      { surface: "있어요", meaning: "there is, is (here)", atomId: "ko:있어요" },
      { surface: "그런데", meaning: "but, and yet", atomId: "ko:그런데" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "이 가방은 누구 거예요?",
        options: ["유진 거예요", "지수 거예요", "제 거예요"],
        answer: "유진 거예요",
      },
    ],
    sentences: [
      { text: "의자에 가방이 있어요.", translation: "There's a bag on a chair." },
      { text: "이거는 제 가방이에요?", translation: "Is this my bag?" },
      { text: "아니요. 제 가방은 여기에 있어요.", translation: "No. My bag is right here." },
      { text: "그런데 이 가방은 누구 거예요?", translation: "But whose bag is this?" },
      { text: "지수 거예요?", translation: "Is it Jisu's?" },
      { text: "지수 가방은 저거예요.", translation: "Jisu's bag is that one over there." },
      { text: "가방에 책이 있어요.", translation: "There's a book in the bag." },
      { text: "책에 이름이 있어요.", translation: "There's a name in the book." },
      { text: "이름이 유진이에요.", translation: "The name is Yujin." },
      { text: "이 가방은 유진 거예요.", translation: "This bag is Yujin's." },
    ],
  },
  {
    id: "ko-m5-cafe-morning",
    languageId: "ko",
    module: 5,
    level: 1,
    title: "Morning at the cafe",
    theme: "A quick coffee run.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "이거 얼마예요?",
        options: ["사천 원이에요", "오천 원이에요", "삼천 원이에요"],
        answer: "사천 원이에요",
      },
    ],
    sentences: [
      { text: "커피 두 잔 주세요.", translation: "Two coffees, please." },
      { text: "물도 한 잔 주세요.", translation: "One water too, please." },
      { text: "빵도 주세요.", translation: "Bread too, please." },
      { text: "이거 얼마예요?", translation: "How much is this?" },
      { text: "사천 원이에요.", translation: "It's 4,000 won." },
      { text: "감사합니다.", translation: "Thank you." },
    ],
  },
  {
    // m5 stretch read. m5 has no place nouns and no verbs yet, so the whole
    // story is a counter drill turned into a miscount-and-fix: counters +
    // 주세요 + prices are the module's entire content, and the arc is the
    // number that changes under the narrator.
    id: "ko-m5-one-more-bread",
    languageId: "ko",
    module: 5,
    level: 2,
    title: "One more piece of bread",
    theme: "A count that comes up one short at the counter.",
    tags: ["food", "shopping", "numbers"],
    glosses: [{ surface: "그런데", meaning: "but, and yet", atomId: "ko:그런데" }],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "모두 얼마예요?",
        options: ["팔천 원이에요", "사천 원이에요", "오천 원이에요"],
        answer: "팔천 원이에요",
      },
    ],
    sentences: [
      { text: "제 친구는 네 명이에요.", translation: "I have four friends." },
      { text: "빵 네 개 주세요.", translation: "Four pieces of bread, please." },
      { text: "얼마예요?", translation: "How much is that?" },
      { text: "사천 원이에요.", translation: "That's 4,000 won." },
      { text: "그런데 우리 친구는 다섯 명이에요!", translation: "But there are five friends!" },
      { text: "빵 한 개 주세요.", translation: "One more piece of bread, please." },
      { text: "물도 다섯 잔 주세요.", translation: "Five glasses of water too, please." },
      { text: "모두 얼마예요?", translation: "How much altogether?" },
      { text: "팔천 원이에요.", translation: "It's 8,000 won." },
      { text: "빵이 다섯 개예요.", translation: "There are five pieces of bread." },
    ],
  },
  {
    // m6 stretch read. m6 finally supplies places + 있어요/없어요, so this is
    // the first KO story with somewhere to be. Motion is bought with one
    // gloss (가요, m7) so the last line can actually leave.
    id: "ko-m6-no-restaurant-at-the-station",
    languageId: "ko",
    module: 6,
    level: 2,
    title: "No restaurant at the station",
    theme: "Hungry, out of time, and in the wrong building.",
    tags: ["travel", "food"],
    glosses: [
      { surface: "그런데", meaning: "but, and yet", atomId: "ko:그런데" },
      { surface: "가요", meaning: "go, am going", atomId: "ko:가요" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "역에 뭐가 있어요?",
        options: ["가게가 있어요", "식당이 있어요", "병원이 있어요"],
        answer: "가게가 있어요",
      },
    ],
    sentences: [
      { text: "여기는 역이에요.", translation: "I'm at the station." },
      { text: "저는 시간이 없어요.", translation: "I don't have time." },
      { text: "역에 식당이 있어요?", translation: "Is there a restaurant in the station?" },
      { text: "아니요, 식당이 없어요.", translation: "No — there's no restaurant." },
      { text: "그런데 가게가 있어요.", translation: "But there is a shop." },
      { text: "가게에 빵이 있어요.", translation: "The shop has bread." },
      { text: "빵 두 개 주세요.", translation: "Two pieces of bread, please." },
      { text: "제 가방에 빵이 있어요.", translation: "There's bread in my bag." },
      { text: "저는 학교에 가요.", translation: "I go to school." },
    ],
  },
  {
    id: "ko-m7-my-day",
    languageId: "ko",
    module: 7,
    level: 1,
    title: "My afternoon",
    theme: "A simple run-through of an afternoon.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "친구는 어디에 있어요?",
        options: ["학교에 있어요", "집에 있어요", "식당에 있어요"],
        answer: "학교에 있어요",
      },
    ],
    sentences: [
      { text: "저는 집에 있어요.", translation: "I'm at home." },
      { text: "밥을 먹어요.", translation: "I eat a meal." },
      { text: "커피를 마셔요.", translation: "I drink coffee." },
      { text: "영화도 봐요.", translation: "I watch a movie too." },
      { text: "친구는 학교에 있어요.", translation: "My friend is at school." },
      { text: "친구는 공부해요.", translation: "My friend studies." },
    ],
  },
  {
    // m7 stretch read (m7 caps at L3). Present tense throughout — m7 has no
    // past forms and no time adverbs at all (오늘/어제 are m10), so the arc has
    // to run on sequence rather than on when. 하고 (m9) buys the companionship
    // the last line pays off.
    id: "ko-m7-the-teacher-at-the-door",
    languageId: "ko",
    module: 7,
    level: 3,
    title: "The teacher at the door",
    theme: "A study session that quietly stops being a study session.",
    tags: ["school", "movies", "friends"],
    glosses: [
      { surface: "그런데", meaning: "but, and yet", atomId: "ko:그런데" },
      { surface: "하고", meaning: "with, and", atomId: "ko:하고" },
      { surface: "좋아요", meaning: "is good, is nice", atomId: "ko:좋아요" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "우리는 선생님하고 뭐 해요?",
        options: ["영화를 봐요", "공부해요", "빵을 먹어요"],
        answer: "영화를 봐요",
      },
    ],
    sentences: [
      { text: "저는 학교에 가요.", translation: "I go to school." },
      { text: "교실에서 공부해요.", translation: "I study in the classroom." },
      { text: "교실에 선생님이 없어요.", translation: "The teacher isn't in the classroom." },
      { text: "그런데 친구가 와요.", translation: "But a friend comes in." },
      { text: "친구 핸드폰에 영화가 있어요.", translation: "My friend has a movie on their phone." },
      { text: "저는 친구하고 영화를 봐요.", translation: "I watch the movie with my friend." },
      { text: "영화가 좋아요.", translation: "The movie is good." },
      { text: "우리는 커피도 마셔요.", translation: "We drink coffee too." },
      { text: "빵도 먹어요.", translation: "We eat bread too." },
      { text: "그런데 문에 선생님이 있어요!", translation: "But the teacher is at the door!" },
      { text: "선생님이 교실에 와요.", translation: "The teacher comes into the classroom." },
      { text: "우리는 책을 봐요.", translation: "We look at our books." },
      { text: "선생님도 핸드폰을 봐요.", translation: "The teacher looks at the phone too." },
      { text: "선생님도 영화를 봐요!", translation: "The teacher watches the movie too!" },
      { text: "우리는 선생님하고 영화를 봐요.", translation: "We watch the movie with the teacher." },
    ],
  },
  {
    // m8 stretch read. m8 is the adjective module and has NO negation yet
    // (안/못 are m11), so nothing can be refused outright — the rejections
    // have to be carried by 그런데 contrast. Order is load-bearing: L4 states
    // the size criterion, L7 discovers the price one, and each candidate
    // fails exactly one of the two. The third bag pays off only because both
    // criteria were established before it appears.
    id: "ko-m8-the-right-bag",
    languageId: "ko",
    module: 8,
    level: 3,
    title: "The right bag",
    theme: "Two things I need from a bag, and three bags that mostly don't.",
    tags: ["shopping", "school"],
    glosses: [
      { surface: "하고", meaning: "and, with", atomId: "ko:하고" },
      { surface: "그래서", meaning: "so, therefore", atomId: "ko:그래서" },
      { surface: "그리고", meaning: "and, and also", atomId: "ko:그리고" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "좋은 가방은 얼마예요?",
        options: ["사천 원이에요", "구천 원이에요", "이천 원이에요"],
        answer: "사천 원이에요",
      },
    ],
    sentences: [
      { text: "제 가방은 작아요.", translation: "My bag is small." },
      { text: "그런데 제 책하고 핸드폰은 커요.", translation: "But my book and my phone are big." },
      { text: "그래서 저는 가게에 가요.", translation: "So I go to the shop." },
      { text: "저는 큰 가방이 좋아요.", translation: "I like big bags." },
      { text: "이 가방은 커요.", translation: "This bag is big." },
      { text: "그런데 구천 원이에요.", translation: "But it's 9,000 won." },
      { text: "구천 원은 비싸요.", translation: "9,000 won is expensive." },
      { text: "저 가방은 싸요.", translation: "That bag over there is cheap." },
      { text: "이천 원이에요.", translation: "It's 2,000 won." },
      { text: "그런데 저 가방은 작아요.", translation: "But that bag is small." },
      { text: "거기에 좋은 가방이 있어요.", translation: "Over there is a good bag." },
      { text: "그 가방은 커요.", translation: "That bag is big." },
      { text: "그리고 사천 원이에요.", translation: "And it's 4,000 won." },
      { text: "그 가방은 예뻐요.", translation: "That bag is pretty." },
      { text: "그거 주세요!", translation: "I'll take it!" },
      { text: "제 책하고 핸드폰이 가방에 있어요.", translation: "My book and my phone are in the bag." },
    ],
  },
  // ── Mid (m9-m17): ~1 story per module ──────────────────────────────────────
  {
    id: "ko-m9-a-snack",
    languageId: "ko",
    module: 9,
    level: 2,
    title: "A snack at home",
    theme: "Bread, milk, and an apple.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "뭐가 커요?",
        options: ["사과예요", "빵이에요", "우유예요"],
        answer: "사과예요",
      },
    ],
    sentences: [
      { text: "저는 집에 있어요.", translation: "I'm at home." },
      { text: "빵하고 우유가 있어요.", translation: "There's bread and milk." },
      { text: "사과도 있어요.", translation: "There's an apple too." },
      { text: "빵을 먹어요.", translation: "I eat the bread." },
      { text: "우유를 마셔요.", translation: "I drink the milk." },
      { text: "빵하고 우유가 맛있어요.", translation: "The bread and milk are tasty." },
      { text: "사과는 커요.", translation: "The apple is big." },
    ],
  },
  {
    // m9 stretch read. m9 adds the "and" particles (하고 / 과 / 와) plus 빵,
    // 우유, 사과 — so the story is built on sharing, which is what those
    // particles are for. Still present tense: past lands at m10.
    id: "ko-m9-the-apple-in-the-bag",
    languageId: "ko",
    module: 9,
    level: 3,
    title: "The apple in the bag",
    theme: "One lunch between two people, and then a surprise.",
    tags: ["food", "friends", "school"],
    glosses: [
      { surface: "그래서", meaning: "so, therefore", atomId: "ko:그래서" },
      { surface: "좋아해요", meaning: "like(s)", atomId: "ko:좋아해요" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "친구 가방에 뭐가 있어요?",
        options: ["사과가 있어요", "빵이 있어요", "우유가 있어요"],
        answer: "사과가 있어요",
      },
    ],
    sentences: [
      { text: "저는 학교에 가요.", translation: "I go to school." },
      { text: "제 가방에 빵과 우유가 있어요.", translation: "In my bag there's bread and milk." },
      { text: "교실에서 친구를 봐요.", translation: "In the classroom I see my friend." },
      { text: "그런데 친구 가방에 빵이 없어요.", translation: "But there's no bread in my friend's bag." },
      { text: "우유도 없어요.", translation: "No milk either." },
      { text: "그래서 저는 친구하고 빵을 먹어요.", translation: "So I eat the bread with my friend." },
      { text: "우유도 마셔요.", translation: "We drink the milk too." },
      { text: "그런데 친구 가방에 사과가 있어요!", translation: "But there's an apple in my friend's bag!" },
      { text: "사과는 커요.", translation: "The apple is big." },
      { text: "우리는 사과를 먹어요.", translation: "We eat the apple." },
      { text: "사과가 맛있어요.", translation: "The apple is delicious." },
      { text: "우리 가방에 빵도 우유도 사과도 없어요.", translation: "Our bags have no bread, no milk, no apple." },
      { text: "그런데 괜찮아요.", translation: "But that's fine." },
      { text: "저는 친구를 좋아해요.", translation: "I like my friend." },
    ],
  },
  {
    id: "ko-m10-yesterday",
    languageId: "ko",
    module: 10,
    level: 2,
    title: "Yesterday",
    theme: "Looking back on a good day.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "어제 뭐가 좋았어요?",
        options: ["영화예요", "커피예요", "우유예요"],
        answer: "영화예요",
      },
    ],
    sentences: [
      { text: "어제 친구하고 커피를 마셨어요.", translation: "Yesterday I had coffee with a friend." },
      { text: "우리는 영화를 봤어요.", translation: "We watched a movie." },
      { text: "영화가 좋았어요.", translation: "The movie was good." },
      { text: "저는 집에서 밥을 먹었어요.", translation: "I ate at home." },
      { text: "친구는 공부했어요.", translation: "My friend studied." },
      { text: "우유도 마셨어요.", translation: "I drank milk too." },
      { text: "오늘도 커피를 마셔요.", translation: "Today I drink coffee too." },
    ],
  },
  {
    // m10 stretch read — the FIRST fully past-tense KO story in the file.
    // m10's past action verbs (갔어요 / 왔어요 / 마셨어요 / 먹었어요 /
    // 맛있었어요) all gate; 있었어요 and 없었어요 never gate at ANY module, so
    // they are bought with two of the four gloss slots. They earn them: the
    // whole arc is a sequence of absences ending in a presence.
    id: "ko-m10-looking-for-a-friend",
    languageId: "ko",
    module: 10,
    level: 3,
    title: "Looking for a friend",
    theme: "Two people spend a whole day missing each other.",
    tags: ["friends", "town"],
    glosses: [
      { surface: "없었어요", meaning: "wasn't there, wasn't in", atomId: "ko:없어요" },
      { surface: "있었어요", meaning: "was there, was in", atomId: "ko:있어요" },
      { surface: "그래서", meaning: "so, therefore", atomId: "ko:그래서" },
      { surface: "그리고", meaning: "and, and then", atomId: "ko:그리고" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "친구는 어디에 있었어요?",
        options: ["식당에 있었어요", "집에 있었어요", "학교에 있었어요"],
        answer: "식당에 있었어요",
      },
    ],
    sentences: [
      { text: "어제 저는 친구 집에 갔어요.", translation: "Yesterday I went to my friend's house." },
      { text: "그런데 친구가 집에 없었어요.", translation: "But my friend wasn't home." },
      { text: "그래서 저는 학교에 갔어요.", translation: "So I went to the school." },
      { text: "학교에도 친구가 없었어요.", translation: "My friend wasn't at school either." },
      { text: "저는 교실에서 커피를 마셨어요.", translation: "I drank a coffee in the classroom." },
      { text: "그리고 가게에 갔어요.", translation: "And then I went to the shop." },
      { text: "가게에도 친구가 없었어요.", translation: "My friend wasn't at the shop either." },
      { text: "저는 식당에 갔어요.", translation: "I went to the restaurant." },
      { text: "식당에 친구가 있었어요!", translation: "My friend was at the restaurant!" },
      { text: "친구는 밥을 먹었어요.", translation: "My friend ate." },
      { text: "저도 밥을 먹었어요.", translation: "I ate too." },
      { text: "밥이 맛있었어요.", translation: "The food was delicious." },
      { text: "친구도 어제 우리 집에 왔어요!", translation: "My friend had come to my house yesterday too!" },
      { text: "그런데 저는 집에 없었어요.", translation: "But I wasn't home." },
      { text: "우리는 식당에서 커피를 마셨어요.", translation: "We drank coffee at the restaurant." },
      { text: "어제는 좋았어요.", translation: "Yesterday was good." },
    ],
  },
  {
    id: "ko-m11-a-day-off",
    languageId: "ko",
    module: 11,
    level: 2,
    title: "A day off",
    theme: "Staying in on a quiet day.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "오늘 저는 어디에 있어요?",
        options: ["집에 있어요", "학교에 있어요", "식당에 있어요"],
        answer: "집에 있어요",
      },
    ],
    sentences: [
      { text: "오늘은 학교에 안 가요.", translation: "Today I don't go to school." },
      { text: "저는 집에 있어요.", translation: "I stay at home." },
      { text: "영화를 보고 싶어요.", translation: "I want to watch a movie." },
      { text: "그런데 커피가 없어요.", translation: "But there's no coffee." },
      { text: "커피를 못 마셔요.", translation: "I can't have my coffee." },
      { text: "빵도 없어요.", translation: "There's no bread either." },
      { text: "그런데 밥도 안 먹어요.", translation: "But I don't eat, either." },
    ],
  },
  {
    // m11 stretch read. m11 adds 안 / 못 / …고 싶어요, which is what makes a
    // frustrated-desire arc writable at all. Note 보고 싶어요 is the ONLY
    // want-form available here: 가고 / 먹고 residual until 고 lands at m14, so
    // the atoms "가고 싶어요" / "먹고 싶어요" are unusable as written text.
    id: "ko-m11-the-restaurant-i-cant-go-to",
    languageId: "ko",
    module: 11,
    level: 3,
    title: "The restaurant I can't go to",
    theme: "An expensive craving, and a cheaper thing that beats it.",
    tags: ["food", "friends", "home"],
    glosses: [
      { surface: "좋아해요", meaning: "like(s)", atomId: "ko:좋아해요" },
      { surface: "그래서", meaning: "so, therefore", atomId: "ko:그래서" },
      { surface: "있었어요", meaning: "was there, was in", atomId: "ko:있어요" },
      { surface: "그리고", meaning: "and, and then", atomId: "ko:그리고" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "저는 어디에서 빵을 먹었어요?",
        options: ["집에서 먹었어요", "식당에서 먹었어요", "학교에서 먹었어요"],
        answer: "집에서 먹었어요",
      },
    ],
    sentences: [
      { text: "저는 그 식당을 좋아해요.", translation: "I love that restaurant." },
      { text: "그 식당은 밥이 맛있어요.", translation: "The food there is delicious." },
      { text: "그런데 그 식당은 비싸요.", translation: "But that restaurant is expensive." },
      { text: "그래서 저는 그 식당에 못 가요.", translation: "So I can't go there." },
      { text: "저는 영화를 보고 싶어요.", translation: "I want to watch a movie." },
      { text: "어제 저는 집에 있었어요.", translation: "Yesterday I was at home." },
      { text: "저는 밥을 안 먹었어요.", translation: "I didn't eat." },
      { text: "그런데 친구가 우리 집에 왔어요.", translation: "But my friend came over." },
      { text: "친구 가방에 빵하고 우유가 있었어요.", translation: "There was bread and milk in my friend's bag." },
      { text: "우리는 집에서 빵을 먹었어요.", translation: "We ate the bread at home." },
      { text: "빵이 맛있었어요.", translation: "The bread was delicious." },
      { text: "그리고 우리는 영화를 봤어요.", translation: "And we watched a movie." },
      { text: "영화가 좋았어요.", translation: "The movie was good." },
      { text: "저는 그 식당에 못 가요.", translation: "I can't go to that restaurant." },
      { text: "그런데 괜찮아요!", translation: "But that's all right!" },
      { text: "우리 집이 좋아요.", translation: "Home is good." },
    ],
  },
  {
    id: "ko-m12-friday-plan",
    languageId: "ko",
    module: 12,
    level: 2,
    title: "A plan for Friday",
    theme: "Setting a time to meet.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "몇 시에 만나요?",
        options: ["세 시에 만나요", "두 시에 만나요", "한 시에 만나요"],
        answer: "세 시에 만나요",
      },
    ],
    sentences: [
      { text: "금요일에 시간이 있어요.", translation: "I have time on Friday." },
      { text: "친구하고 영화를 보고 싶어요.", translation: "I want to watch a movie with a friend." },
      { text: "지금 몇 시예요?", translation: "What time is it now?" },
      { text: "두 시예요.", translation: "It's 2 o'clock." },
      { text: "세 시에 만나요.", translation: "Let's meet at 3:00." },
      { text: "우리는 영화를 봐요.", translation: "We watch a movie." },
      { text: "우리는 밥도 먹어요.", translation: "We eat a meal too." },
    ],
  },
  {
    // L3 EXEMPLAR for docs/story-authoring-guide.md. m12 caps at L3, so this is
    // the stretch read that sits above ko-m12-friday-plan's L2. Polite 해요
    // register throughout, matching the course's spine.
    //
    // Present-tense narration is a POOL CONSTRAINT, not a style pick: the past
    // action verbs gate cleanly (갔어요 / 왔어요 / 봤어요 / 마셨어요), but
    // 있었어요 / 없었어요 / 싶었어요 residual whole at m12, m13, m20 AND m27 —
    // they are not writable at any module in the course — and this arc turns on
    // exactly those "was at home" / "wanted to watch" beats.
    //
    // Present tense is the weaker Korean. Where an arc CAN be told with the past
    // action verbs, prefer the past; don't copy this pattern by default.
    id: "ko-m12-waiting-for-a-friend",
    languageId: "ko",
    module: 12,
    level: 3,
    title: "Waiting for a friend",
    theme: "A plan to see a movie falls apart, then comes back together.",
    tags: ["friends", "food", "daily-life"],
    glosses: [
      { surface: "기다려요", meaning: "wait(s)", atomId: "ko:기다리다" },
      { surface: "전화", meaning: "phone, phone call", atomId: "ko:전화" },
      { surface: "아파요", meaning: "hurts, is unwell", atomId: "ko:아파요" },
      { surface: "그래서", meaning: "so, therefore", atomId: "ko:그래서" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "우리는 어디에서 영화를 봐요?",
        options: ["친구 집에서 봐요", "식당에서 봐요", "학교에서 봐요"],
        answer: "친구 집에서 봐요",
      },
      {
        id: "time",
        kind: "detail",
        prompt: "우리는 몇 시에 만나요?",
        options: ["세 시에 만나요", "두 시에 만나요", "한 시에 만나요"],
        answer: "세 시에 만나요",
      },
    ],
    sentences: [
      { text: "오늘은 학교에 안 가요.", translation: "Today I don't go to school." },
      { text: "저는 친구하고 영화를 보고 싶어요.", translation: "I want to watch a movie with my friend." },
      { text: "우리는 세 시에 만나요.", translation: "We're meeting at three." },
      { text: "지금 두 시예요.", translation: "It's two o'clock now." },
      { text: "저는 식당에 가요.", translation: "I go to the restaurant." },
      { text: "식당에서 커피를 마셔요.", translation: "I drink coffee at the restaurant." },
      { text: "저는 식당에서 친구를 기다려요.", translation: "I wait for my friend at the restaurant." },
      { text: "그런데 친구가 안 와요.", translation: "But my friend doesn't come." },
      { text: "저는 한 시간 기다려요.", translation: "I wait for an hour." },
      { text: "지금도 친구가 안 와요.", translation: "Even now my friend doesn't come." },
      { text: "저는 전화해요.", translation: "I call." },
      { text: "친구는 집에 있어요.", translation: "My friend is at home." },
      { text: "친구는 머리가 아파요.", translation: "My friend has a headache." },
      { text: "그래서 저는 친구 집에 가요.", translation: "So I go to my friend's house." },
      { text: "우리는 집에서 영화를 봐요.", translation: "We watch the movie at the house." },
    ],
  },
  {
    id: "ko-m13-my-week",
    languageId: "ko",
    module: 13,
    level: 2,
    title: "My week",
    theme: "Work, study, and a bit of exercise.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "토요일에는 뭐 해요?",
        options: ["집에 있어요", "회사에 가요", "학교에 가요"],
        answer: "집에 있어요",
      },
    ],
    sentences: [
      { text: "저는 자주 운동해요.", translation: "I exercise often." },
      { text: "월요일부터 금요일까지 회사에 가요.", translation: "I go to work from Monday to Friday." },
      { text: "회사에서 공부해요.", translation: "I study at work." },
      { text: "저는 커피를 좋아해요.", translation: "I like coffee." },
      { text: "그리고 운동도 좋아해요.", translation: "And I like exercise too." },
      { text: "가끔 영화를 봐요.", translation: "Sometimes I watch a movie." },
      { text: "토요일에는 항상 집에 있어요.", translation: "On Saturdays I always stay home." },
    ],
  },
  {
    // m13 stretch read — first KO L4 (17-24 sentences). m13 hands over the
    // frequency adverbs (항상 / 자주 / 가끔 / 별로 / 전혀), 부터…까지, month
    // names and both 그래서 / 그리고, which is exactly enough to write a habit
    // that CHANGES rather than a habit that is merely listed.
    id: "ko-m13-from-june-to-october",
    languageId: "ko",
    module: 13,
    level: 4,
    title: "From June to October",
    theme: "Someone drags me out to exercise. Months later the roles swap.",
    tags: ["exercise", "work", "friends"],
    glosses: [
      { surface: "같이", meaning: "together" },
      { surface: "아팠어요", meaning: "hurt, was sore", atomId: "ko:아파요" },
      { surface: "혼자", meaning: "alone, by myself" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "지금 친구는 어디에 있어요?",
        options: ["회사에 있어요", "집에 있어요", "학교에 있어요"],
        answer: "회사에 있어요",
      },
    ],
    sentences: [
      { text: "저는 민수예요.", translation: "I'm Minsu." },
      { text: "저는 아홉 시부터 여섯 시까지 회사에 있어요.", translation: "I'm at the office from nine until six." },
      { text: "저는 회사에서 커피를 자주 마셔요.", translation: "I drink coffee at the office a lot." },
      { text: "그런데 저는 운동을 전혀 안 해요.", translation: "But I never exercise at all." },
      { text: "제 친구는 항상 운동해요.", translation: "My friend always exercises." },
      { text: "유월에 친구가 우리 집에 왔어요.", translation: "In June my friend came to my house." },
      { text: "민수, 같이 운동해요!", translation: "\"Minsu, let's exercise together!\"" },
      { text: "저는 운동을 별로 안 좋아해요.", translation: "I don't much like exercise." },
      { text: "그런데 저는 친구하고 운동했어요.", translation: "But I exercised with my friend." },
      { text: "운동이 별로 안 좋았어요.", translation: "I didn't enjoy it much." },
      { text: "제 다리가 아팠어요.", translation: "My legs hurt." },
      { text: "그래서 저는 운동을 안 했어요.", translation: "So I didn't exercise." },
      { text: "그런데 친구가 토요일에 항상 우리 집에 왔어요.", translation: "But my friend came to my house every Saturday." },
      { text: "그리고 우리는 같이 운동했어요.", translation: "And we exercised together." },
      { text: "칠월에도 친구가 왔어요.", translation: "In July my friend came too." },
      { text: "팔월에도 왔어요.", translation: "In August too." },
      { text: "시월부터 저는 운동을 좋아해요.", translation: "From October on, I like exercise." },
      { text: "지금 저는 자주 운동해요.", translation: "Now I exercise often." },
      { text: "그런데 지금 친구는 운동을 안 해요.", translation: "But now my friend doesn't exercise." },
      { text: "친구는 항상 회사에 있어요.", translation: "My friend is always at the office." },
      { text: "그래서 저는 토요일에 혼자 운동해요.", translation: "So on Saturdays I exercise alone." },
      { text: "지금 저는 친구 회사에 가요.", translation: "Now I go to my friend's office." },
      { text: "친구, 같이 운동해요!", translation: "\"Come on — let's exercise together!\"" },
    ],
  },
  {
    id: "ko-m14-a-busy-day",
    languageId: "ko",
    module: 14,
    level: 2,
    title: "A busy day",
    theme: "Too much to do, too little time.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "저는 뭐를 못 마셔요?",
        options: ["커피를 못 마셔요", "물을 못 마셔요", "우유를 못 마셔요"],
        answer: "커피를 못 마셔요",
      },
    ],
    sentences: [
      { text: "저는 바빠서 시간이 없어요.", translation: "I'm busy, so I have no time." },
      { text: "오늘 회사에 가요.", translation: "I go to work today." },
      { text: "회사에서 공부하고 밥을 먹어요.", translation: "At work I study and eat." },
      { text: "친구가 와요.", translation: "A friend comes over." },
      { text: "친구는 커피를 마셔요.", translation: "My friend drinks coffee." },
      { text: "저는 바빠서 커피를 못 마셔요.", translation: "But I'm too busy for coffee." },
      { text: "기다려 주세요.", translation: "Please wait." },
    ],
  },
  {
    // m14 stretch read. m14 lands 고 (clause join), 바빠서, the 백/천/만
    // number scale and 기다리다 — so this is the first KO story that can both
    // wait and explain why someone else couldn't come. 기다렸어요 never gates
    // at any module and is bought with a gloss; 마시고 / 먹고 are NOT available
    // yet (마시고 is m15, 먹고 never), so the meal is two short sentences.
    id: "ko-m14-the-child-at-the-station",
    languageId: "ko",
    module: 14,
    level: 4,
    title: "The child at the station",
    theme: "A small stranger asks for help, and the wait gets long.",
    tags: ["town", "family", "help"],
    glosses: [
      { surface: "기다렸어요", meaning: "waited", atomId: "ko:기다리다" },
      { surface: "있었어요", meaning: "was there, was in", atomId: "ko:있어요" },
      { surface: "같이", meaning: "together" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "미나 어머니는 어디에 있었어요?",
        options: ["병원에 있었어요", "역에 있었어요", "가게에 있었어요"],
        answer: "병원에 있었어요",
      },
    ],
    sentences: [
      { text: "어제 저는 역에 갔어요.", translation: "Yesterday I went to the station." },
      { text: "역에서 작은 아이를 봤어요.", translation: "At the station I saw a small child." },
      { text: "아이가 저를 봤어요.", translation: "The child looked at me." },
      { text: "어머니가 없어요. 도와주세요.", translation: "\"My mother isn't here. Please help me.\"" },
      { text: "아이 이름은 미나예요.", translation: "The child's name is Mina." },
      { text: "미나는 학생이에요.", translation: "Mina is a schoolchild." },
      { text: "저는 미나하고 같이 어머니를 기다렸어요.", translation: "I waited together with Mina for her mother." },
      { text: "그런데 어머니가 안 왔어요.", translation: "But her mother didn't come." },
      { text: "우리는 한 시간 기다렸어요.", translation: "We waited for an hour." },
      { text: "미나는 밥을 안 먹었어요.", translation: "Mina hadn't eaten." },
      { text: "그래서 우리는 가게에 갔어요.", translation: "So we went to the shop." },
      { text: "빵 두 개하고 우유를 주세요.", translation: "\"Two pieces of bread and a milk, please.\"" },
      { text: "이천 원이에요.", translation: "\"That's 2,000 won.\"" },
      { text: "우리는 빵을 먹었어요.", translation: "We ate the bread." },
      { text: "그리고 우유를 마셨어요.", translation: "And we drank the milk." },
      { text: "우리 어머니는 병원에 있어요.", translation: "\"My mother is at the hospital.\"" },
      { text: "그래서 우리는 같이 병원에 갔어요.", translation: "So we went to the hospital together." },
      { text: "병원에 미나 어머니가 있었어요!", translation: "Mina's mother was at the hospital!" },
      { text: "어머니는 바빠서 역에 못 왔어요.", translation: "She was busy, so she couldn't come to the station." },
      { text: "고마워요! 감사합니다!", translation: "\"Thank you! Thank you so much!\"" },
      { text: "미나는 어머니하고 집에 가고 저는 역에 갔어요.", translation: "Mina went home with her mother, and I went back to the station." },
      { text: "어제는 좋았어요.", translation: "Yesterday was a good day." },
    ],
  },
  {
    id: "ko-m15-relaxing-at-home",
    languageId: "ko",
    module: 15,
    level: 2,
    title: "Relaxing at home",
    theme: "A quiet afternoon with a friend.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "오늘 저는 어디에 있어요?",
        options: ["집에 있어요", "학교에 있어요", "회사에 있어요"],
        answer: "집에 있어요",
      },
    ],
    sentences: [
      { text: "오늘은 집에 있어요.", translation: "Today I'm at home." },
      { text: "커피를 마시고 있어요.", translation: "I'm drinking coffee." },
      { text: "영화를 보고 있어요.", translation: "I'm watching a movie." },
      { text: "친구가 전화해요.", translation: "A friend calls." },
      { text: "친구도 집에 와요.", translation: "My friend comes over too." },
      { text: "여기 앉아도 돼요.", translation: "You can sit here." },
      { text: "우리는 커피를 마시고 영화를 봐요.", translation: "We drink coffee and watch a movie." },
    ],
  },
  {
    // m15 stretch read. m15 gives …고 있어요, 이지만 and 전화, so the phone can
    // finally ring and a sentence can finally concede something. Narration is
    // past; the progressive appears where it belongs — inside the phone call,
    // where present tense is what a speaker would actually use.
    id: "ko-m15-the-saturday-call",
    languageId: "ko",
    module: 15,
    level: 4,
    title: "The Saturday call",
    theme: "A day off, one phone call, and an office with nobody in it.",
    tags: ["work", "phone", "home"],
    glosses: [
      { surface: "사람", meaning: "person, people" },
      { surface: "없었어요", meaning: "wasn't there, wasn't in", atomId: "ko:없어요" },
      { surface: "기다렸어요", meaning: "waited", atomId: "ko:기다리다" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "저는 회사에 언제 가요?",
        options: ["일요일에 가요", "토요일에 가요", "금요일에 가요"],
        answer: "일요일에 가요",
      },
    ],
    sentences: [
      { text: "오늘은 토요일이에요.", translation: "Today is Saturday." },
      { text: "저는 회사에 안 가요.", translation: "I don't go to the office." },
      { text: "저는 집에서 영화를 봤어요.", translation: "I watched a movie at home." },
      { text: "커피도 마셨어요.", translation: "I drank coffee too." },
      { text: "그런데 회사에서 전화했어요.", translation: "But the office called." },
      { text: "지금 뭐 해요?", translation: "\"What are you doing right now?\"" },
      { text: "저는 집에서 영화를 보고 있어요.", translation: "\"I'm at home watching a movie.\"" },
      { text: "오늘 회사에 와요.", translation: "\"Come in to the office today.\"" },
      { text: "오늘은 토요일이지만 저는 회사에 갔어요.", translation: "Today is Saturday, but I went in to the office." },
      { text: "그런데 회사에 사람이 없었어요.", translation: "But there was nobody at the office." },
      { text: "저는 한 시간 기다렸어요.", translation: "I waited for an hour." },
      { text: "그런데 사람이 안 왔어요.", translation: "But nobody came." },
      { text: "그래서 저는 회사에 전화했어요.", translation: "So I called the office." },
      { text: "일요일에 회사에 와요.", translation: "\"Come in to the office on Sunday.\"" },
      { text: "오늘은 토요일이에요!", translation: "But today is Saturday!" },
      { text: "저는 집에 갔어요.", translation: "I went home." },
      { text: "집에서 커피를 마시고 영화를 봤어요.", translation: "At home I drank coffee and watched my movie." },
      { text: "지금 저는 자고 싶어요.", translation: "Right now I want to sleep." },
      { text: "일요일에 저는 회사에 가요.", translation: "On Sunday I go in to the office." },
      { text: "그런데 일요일에도 회사에 사람이 없어요?", translation: "But on Sunday — is there nobody at the office either?" },
    ],
  },
  {
    id: "ko-m16-friends-house",
    languageId: "ko",
    module: 16,
    level: 2,
    title: "At a friend's house",
    theme: "Visiting a friend's place.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "저는 뭐를 좋아해요?",
        options: ["커피를 좋아해요", "담배를 좋아해요", "영화를 좋아해요"],
        answer: "커피를 좋아해요",
      },
    ],
    sentences: [
      { text: "오늘 친구 집에 가요.", translation: "Today I go to my friend's house." },
      { text: "친구 집에서는 담배를 피우면 안 돼요.", translation: "You can't smoke at my friend's house." },
      { text: "저는 담배를 싫어해요.", translation: "I don't like cigarettes." },
      { text: "네, 알겠어요.", translation: "OK, got it." },
      { text: "친구는 커피를 좋아해요.", translation: "My friend likes coffee." },
      { text: "저도 커피를 좋아해요.", translation: "I like coffee too." },
      { text: "우리는 커피를 마시고 영화를 봐요.", translation: "We drink coffee and watch a movie." },
    ],
  },
  {
    // m16 stretch read — first KO L4 in the m16-m27 run. m16's own grammar is
    // the no-smoking frame (피우면 안 돼요 / 알겠어요 / 싫어해요), so the sign is
    // the module's content and the story is what the sign costs. Note 지 마세요
    // is UNUSABLE in running text: the atom carries a space, the gate matches
    // inside tokens, and "마세요" alone is not a surface — 피우면 안 돼요 is the
    // only prohibition m16 can actually write.
    id: "ko-m16-the-rule-at-the-restaurant",
    languageId: "ko",
    module: 16,
    level: 4,
    title: "The rule at the restaurant",
    theme: "A sign I was glad to see, and what it turned out to cost.",
    tags: ["work", "food", "friends"],
    glosses: [
      { surface: "사람", meaning: "person, people" },
      { surface: "혼자", meaning: "alone, by myself" },
      { surface: "몰랐어요", meaning: "didn't know" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "준은 지금 어디에 있어요?",
        options: ["병원에 있어요", "식당에 있어요", "가게에 있어요"],
        answer: "병원에 있어요",
      },
    ],
    sentences: [
      { text: "저는 담배를 싫어해요.", translation: "I dislike cigarettes." },
      { text: "그런데 제 친구 준은 담배를 좋아해요.", translation: "But my friend Jun likes cigarettes." },
      { text: "저는 준을 좋아해요.", translation: "I like Jun." },
      { text: "준하고 저는 회사 식당에서 밥을 먹어요.", translation: "Jun and I eat at the office restaurant." },
      { text: "그 식당은 밥이 맛있어요. 그리고 싸요.", translation: "The food at that restaurant is delicious. And cheap." },
      { text: "화요일에 식당 사람이 왔어요.", translation: "On Tuesday someone from the restaurant came over." },
      { text: "준, 여기서 담배를 피우면 안 돼요.", translation: "\"Jun, you may not smoke here.\"" },
      { text: "네, 알겠어요.", translation: "\"Yes, understood.\"" },
      { text: "저는 좋았어요.", translation: "I was glad." },
      { text: "그런데 수요일에 준이 식당에 안 왔어요.", translation: "But on Wednesday Jun didn't come to the restaurant." },
      { text: "목요일에도 안 왔어요.", translation: "On Thursday he didn't come either." },
      { text: "저는 혼자 밥을 먹었어요.", translation: "I ate alone." },
      { text: "그런데 밥이 안 맛있었어요.", translation: "But the food wasn't good." },
      { text: "금요일에도 준이 안 왔어요.", translation: "On Friday too Jun didn't come." },
      { text: "그래서 전화했어요.", translation: "So I called." },
      { text: "준, 지금 어디에 있어요?", translation: "\"Jun, where are you right now?\"" },
      { text: "저는 병원에 있어요.", translation: "\"I'm at the hospital.\"" },
      { text: "우리 어머니가 병원에 있어요.", translation: "\"My mother is at the hospital.\"" },
      { text: "저는 몰랐어요.", translation: "I didn't know." },
      { text: "빵 두 개 주세요.", translation: "\"Two pieces of bread, please.\"" },
      { text: "준하고 저는 병원에서 빵을 먹었어요.", translation: "Jun and I ate bread at the hospital." },
      { text: "고마워요.", translation: "\"Thanks.\"" },
      { text: "저는 담배를 싫어해요. 그런데 준은 제 친구예요.", translation: "I dislike cigarettes. But Jun is my friend." },
    ],
  },
  {
    id: "ko-m17-my-commute",
    languageId: "ko",
    module: 17,
    level: 2,
    title: "My commute",
    theme: "Bus, subway, and a left turn.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "회사는 어디에 있어요?",
        options: ["왼쪽에 있어요", "오른쪽에 있어요", "역에 있어요"],
        answer: "왼쪽에 있어요",
      },
    ],
    sentences: [
      { text: "저는 회사에 가요.", translation: "I go to work." },
      { text: "버스를 타요.", translation: "I take the bus." },
      { text: "다음 역에서 내려요.", translation: "I get off at the next stop." },
      { text: "그리고 지하철을 타요.", translation: "And then I take the subway." },
      { text: "회사까지 똑바로 가요.", translation: "I go straight to the office." },
      { text: "회사는 왼쪽에 있어요.", translation: "The office is on the left." },
      { text: "저는 회사에서 공부해요.", translation: "I study at work." },
    ],
  },
  {
    // m17 stretch read. m17 hands over 로/으로, the vehicles, 왼쪽/오른쪽,
    // 똑바로 and the 타세요 / 내려서 imperatives — a whole directions kit — so
    // the arc is directions that are perfectly correct and still fail. The
    // plant is line 11: the narrator is at the SHOP, and the instructions were
    // written from the STATION.
    id: "ko-m17-the-left-that-was-right",
    languageId: "ko",
    module: 17,
    level: 4,
    title: "The left that was right",
    theme: "Perfect directions, followed from the wrong starting point.",
    tags: ["town", "travel", "friends"],
    glosses: [
      { surface: "몰랐어요", meaning: "didn't know" },
      { surface: "탔어요", meaning: "got on, rode", atomId: "ko:타다" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "민수는 어디에서 버스를 탔어요?",
        options: ["가게에서 탔어요", "역에서 탔어요", "학교에서 탔어요"],
        answer: "가게에서 탔어요",
      },
    ],
    sentences: [
      { text: "저는 미나 집을 몰랐어요.", translation: "I didn't know Mina's house." },
      { text: "그래서 저는 가게에서 전화했어요.", translation: "So I called from the shop." },
      { text: "미나, 집에 어떻게 가요?", translation: "\"Mina, how do I get to the house?\"" },
      { text: "역에서 버스를 타세요.", translation: "\"Take the bus from the station.\"" },
      { text: "그리고 다음 역에서 내려요.", translation: "\"And get off at the next stop.\"" },
      { text: "거기에서 똑바로 가세요.", translation: "\"From there go straight.\"" },
      { text: "병원에서 왼쪽으로 가세요.", translation: "\"At the hospital go to the left.\"" },
      { text: "우리 집은 왼쪽에 있어요.", translation: "\"My house is on the left.\"" },
      { text: "미나, 고마워요.", translation: "\"Thank you, Mina.\"" },
      { text: "저는 버스를 탔어요.", translation: "I got on the bus." },
      { text: "그리고 다음 역에서 내려서 똑바로 갔어요.", translation: "And I got off at the next stop and went straight." },
      { text: "저는 병원을 봤어요.", translation: "I saw a hospital." },
      { text: "그래서 저는 왼쪽으로 갔어요.", translation: "So I went to the left." },
      { text: "그런데 미나 집을 못 봤어요.", translation: "But I couldn't find Mina's house." },
      { text: "미나, 왼쪽에 미나 집이 없어요.", translation: "\"Mina, your house isn't on the left.\"" },
      { text: "민수, 왼쪽에 뭐가 있어요?", translation: "\"Minsu, what's on the left?\"" },
      { text: "학교가 있어요.", translation: "\"There's a school.\"" },
      { text: "민수, 역에서 버스를 탔어요?", translation: "\"Minsu, did you get on the bus at the station?\"" },
      { text: "아니요. 저는 가게에서 버스를 탔어요.", translation: "\"No. I got on the bus at the shop.\"" },
      { text: "역에서 미나 집은 왼쪽에 있어요. 그런데 가게에서 미나 집은 오른쪽에 있어요.", translation: "From the station Mina's house is on the left. But from the shop it's on the right." },
    ],
  },
  // ── Late (m18-m27): ramp up — 1, sometimes 2 stories per module ────────────
  {
    id: "ko-m18-tomorrows-weather",
    languageId: "ko",
    module: 18,
    level: 2,
    title: "Tomorrow's weather",
    theme: "A clear day, then rain.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "내일은 뭐가 올 거예요?",
        options: ["비가 올 거예요", "눈이 올 거예요", "바람이 올 거예요"],
        answer: "비가 올 거예요",
      },
    ],
    sentences: [
      { text: "오늘은 날씨가 좋아요.", translation: "The weather is nice today." },
      { text: "맑아요.", translation: "It's clear." },
      { text: "그런데 내일은 비가 올 거예요.", translation: "But tomorrow it will rain." },
      { text: "내일은 추워요.", translation: "Tomorrow it's cold." },
      { text: "저는 겨울을 좋아해요.", translation: "I like winter." },
      { text: "겨울에는 눈이 와요.", translation: "In winter it snows." },
      { text: "여름에는 더워요.", translation: "In summer it's hot." },
    ],
  },
  {
    // m18 stretch read. m18 supplies the weather nouns, the ㅂ-irregular
    // adjectives and 올 거예요 / 것 같아요, so a forecast can finally CONTRADICT
    // a plan. The story is the decision to go anyway. 우산 has no atom anywhere
    // in the course but the arc cannot be told without it, so it takes a slot.
    id: "ko-m18-rain-at-the-sea",
    languageId: "ko",
    module: 18,
    level: 4,
    title: "Rain at the sea",
    theme: "The forecast says don't go. We go.",
    tags: ["weather", "travel", "friends"],
    glosses: [
      { surface: "우산", meaning: "umbrella" },
      { surface: "없었어요", meaning: "wasn't there, didn't have", atomId: "ko:없어요" },
      { surface: "추웠어요", meaning: "was cold", atomId: "ko:추워요" },
      { surface: "사람", meaning: "person, people" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "지수는 토요일에 어디에 갔어요?",
        options: ["바다에 갔어요", "집에 갔어요", "학교에 갔어요"],
        answer: "바다에 갔어요",
      },
    ],
    sentences: [
      { text: "저는 봄부터 바다에 가고 싶어요.", translation: "Since spring I've wanted to go to the sea." },
      { text: "지수도 바다를 좋아해요.", translation: "Jisu likes the sea too." },
      { text: "우리는 토요일에 기차로 바다에 가요.", translation: "On Saturday we go to the sea by train." },
      { text: "그런데 금요일에 저는 지수하고 가게에 갔어요.", translation: "But on Friday I went to the shop with Jisu." },
      { text: "내일은 비가 올 거예요.", translation: "\"Tomorrow it will rain.\"" },
      { text: "민수, 우리는 못 가요.", translation: "\"Minsu, we can't go.\"" },
      { text: "저는 바다에 가요.", translation: "\"I'm going to the sea.\"" },
      { text: "토요일 아홉 시에 지수가 역에 왔어요.", translation: "At nine on Saturday Jisu came to the station." },
      { text: "저는 우산이 없었어요.", translation: "I didn't have an umbrella." },
      { text: "그런데 지수 우산은 커요.", translation: "But Jisu's umbrella is big." },
      { text: "우리는 기차로 갔어요.", translation: "We went by train." },
      { text: "기차에서 우리는 커피를 마셨어요.", translation: "On the train we drank coffee." },
      { text: "열두 시에 우리는 바다에 갔어요.", translation: "At twelve we went to the sea." },
      { text: "바다에 비가 왔어요.", translation: "It rained at the sea." },
      { text: "그리고 추웠어요.", translation: "And it was cold." },
      { text: "바다에 사람이 없었어요.", translation: "There was nobody at the sea." },
      { text: "우리는 두 시간 바다를 봤어요.", translation: "We looked at the sea for two hours." },
      { text: "바다가 좋았어요.", translation: "The sea was good." },
      { text: "우리는 역 식당에 갔어요.", translation: "Then we went to the restaurant at the station." },
      { text: "식당에서 빵을 먹었어요.", translation: "We ate bread at the restaurant." },
      { text: "지수는 겨울에도 바다에 가요.", translation: "Jisu goes to the sea in winter too." },
      { text: "겨울에는 눈이 와요.", translation: "In winter it snows." },
      { text: "저는 겨울에도 바다에 가고 싶어요.", translation: "I want to go to the sea in winter too." },
    ],
  },
  {
    id: "ko-m19-my-family",
    languageId: "ko",
    module: 19,
    level: 2,
    title: "My family",
    theme: "Four of us, and an older brother.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "우리 가족은 몇 명이에요?",
        options: ["네 명이에요", "세 명이에요", "두 명이에요"],
        answer: "네 명이에요",
      },
    ],
    sentences: [
      { text: "우리 가족은 네 명이에요.", translation: "There are four people in my family." },
      { text: "엄마, 아빠, 형, 그리고 저요.", translation: "Mom, dad, my older brother, and me." },
      { text: "형은 스무 살이에요.", translation: "My brother is twenty." },
      { text: "저는 학생이에요.", translation: "I'm a student." },
      { text: "형은 회사에 가요.", translation: "My brother goes to work." },
      { text: "우리 가족은 커피를 좋아해요.", translation: "My family likes coffee." },
      { text: "저는 우리 가족을 좋아해요.", translation: "I love my family." },
    ],
  },
  {
    // m19 stretch read. m19 gives the family nouns plus 살 / 스무 / 서른, so the
    // story can be about the gap between two ages. Structure: the brother's
    // claim ("회사는 정말 좋아요") is planted three times and then falsified by
    // one Saturday visit; the closing line is what the narrator does about it.
    id: "ko-m19-my-brothers-office",
    languageId: "ko",
    module: 19,
    level: 4,
    title: "My brother's office",
    theme: "The job my brother makes sound wonderful, seen once from the inside.",
    tags: ["family", "work"],
    glosses: [
      { surface: "정말", meaning: "really, truly" },
      { surface: "사람", meaning: "person, people" },
      { surface: "없었어요", meaning: "wasn't there, wasn't in", atomId: "ko:없어요" },
      { surface: "혼자", meaning: "alone, by oneself" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "형은 토요일에 어디에서 밥을 먹었어요?",
        options: ["가게에서 먹었어요", "회사 식당에서 먹었어요", "집에서 먹었어요"],
        answer: "가게에서 먹었어요",
      },
    ],
    sentences: [
      { text: "제 형은 항상 열 시에 집에 와요.", translation: "My older brother always comes home at ten." },
      { text: "형은 서른 살이에요. 저는 스무 살 학생이에요.", translation: "My brother is thirty. I'm a twenty-year-old student." },
      { text: "형은 회사를 좋아해요.", translation: "My brother likes the office." },
      { text: "회사는 정말 좋아요.", translation: "\"The office is really good.\"" },
      { text: "형은 회사에서 커피를 마셔요. 그리고 밥도 먹어요.", translation: "He drinks coffee at the office. And he eats there too." },
      { text: "그래서 저도 회사에서 공부하고 싶어요.", translation: "So I want to study at an office too." },
      { text: "토요일에도 형은 회사에 가요.", translation: "On Saturdays too my brother goes to the office." },
      { text: "시월에 저는 형하고 회사에 갔어요.", translation: "In October I went to the office with my brother." },
      { text: "형 회사는 커요.", translation: "My brother's office is big." },
      { text: "그런데 토요일에 회사에 사람이 없었어요.", translation: "But on Saturday there was nobody at the office." },
      { text: "형은 혼자 회사에서 공부했어요.", translation: "My brother studied at the office alone." },
      { text: "형은 밥을 못 먹었어요.", translation: "My brother hadn't been able to eat." },
      { text: "회사에 식당이 없었어요.", translation: "There was no restaurant at the office." },
      { text: "우리는 가게에 갔어요.", translation: "We went to the shop." },
      { text: "형은 가게에서 빵하고 우유를 먹었어요.", translation: "My brother ate bread and milk at the shop." },
      { text: "고마워요.", translation: "\"Thanks.\"" },
      { text: "회사는 정말 좋아요.", translation: "\"The office is really good.\"" },
      { text: "저는 알겠어요.", translation: "I understand." },
    ],
  },
  {
    id: "ko-m20-a-cold",
    languageId: "ko",
    module: 20,
    level: 2,
    title: "A cold",
    theme: "Aches, a fever, and some medicine.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "어디가 아파요?",
        options: ["머리가 아파요", "다리가 아파요", "팔이 아파요"],
        answer: "머리가 아파요",
      },
    ],
    sentences: [
      { text: "오늘은 머리가 아파요.", translation: "My head hurts today." },
      { text: "그리고 배도 아파요.", translation: "And my stomach hurts too." },
      { text: "감기예요.", translation: "It's a cold." },
      { text: "저는 병원에 가요.", translation: "I go to the hospital." },
      { text: "약을 먹어요.", translation: "I take medicine." },
      { text: "약을 먹으면 괜찮을 거예요.", translation: "If I take medicine, I'll be fine." },
      { text: "그리고 집에 있어요.", translation: "And I stay home." },
    ],
  },
  {
    // m20 stretch read. m20 lands the body parts, 아파요, 열이 나요, 약,
    // 먹으면 and 괜찮을 거예요 — enough to write an illness that is DOUBTED and
    // then confirmed. The Monday complaint is planted in the first five lines
    // precisely so the reader shares the narrator's disbelief.
    id: "ko-m20-the-monday-stomachache",
    languageId: "ko",
    module: 20,
    level: 4,
    title: "The Monday stomachache",
    theme: "My sibling's stomach hurts every Monday. Until one Monday it really does.",
    tags: ["health", "family", "school"],
    glosses: [
      { surface: "정말", meaning: "really, truly" },
      { surface: "아팠어요", meaning: "hurt, was unwell", atomId: "ko:아파요" },
      { surface: "몰랐어요", meaning: "didn't know" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "동생은 왜 학교에서 병원에 갔어요?",
        options: ["열이 나요", "다리가 아파요", "학교를 싫어해요"],
        answer: "열이 나요",
      },
    ],
    sentences: [
      { text: "제 동생은 열 살이에요.", translation: "My younger sibling is ten." },
      { text: "동생은 학교를 싫어해요.", translation: "My sibling dislikes school." },
      { text: "월요일에 동생은 항상 배가 아파요.", translation: "On Mondays my sibling's stomach always hurts." },
      { text: "그런데 화요일에는 안 아파요.", translation: "But on Tuesdays it doesn't hurt." },
      { text: "수요일에도 괜찮아요.", translation: "On Wednesdays it's fine too." },
      { text: "동생, 학교에 가요.", translation: "\"Go to school.\"" },
      { text: "시월 월요일에 동생이 배가 아팠어요.", translation: "On a Monday in October my sibling's stomach hurt." },
      { text: "괜찮아요. 학교에 가요.", translation: "\"You're fine. Go to school.\"" },
      { text: "동생은 학교에 갔어요.", translation: "My sibling went to school." },
      { text: "열한 시에 학교에서 전화가 왔어요.", translation: "At eleven a call came from the school." },
      { text: "동생이 열이 나요.", translation: "\"Your sibling has a fever.\"" },
      { text: "동생은 지금 병원에 있어요.", translation: "\"Your sibling is at the hospital now.\"" },
      { text: "저는 회사에서 병원에 갔어요.", translation: "I went from the office to the hospital." },
      { text: "동생은 병원에서 자고 있어요.", translation: "My sibling is asleep at the hospital." },
      { text: "동생은 감기예요.", translation: "My sibling has a cold." },
      { text: "병원 선생님이 왔어요.", translation: "The doctor came." },
      { text: "약을 먹으면 괜찮을 거예요.", translation: "\"If you take the medicine you'll be fine.\"" },
      { text: "동생은 약을 먹었어요.", translation: "My sibling took the medicine." },
      { text: "네 시에 동생이 물을 마셨어요.", translation: "At four my sibling drank some water." },
      { text: "형, 저는 정말 배가 아팠어요.", translation: "\"Brother, my stomach really did hurt.\"" },
      { text: "저는 몰랐어요.", translation: "I didn't know." },
      { text: "동생은 목요일에 학교에 갔어요.", translation: "My sibling went back to school on Thursday." },
      { text: "지금 월요일에 저는 동생하고 병원에 가요.", translation: "Now on Mondays I go to the hospital with my sibling." },
    ],
  },
  {
    id: "ko-m21-a-korean-meal",
    languageId: "ko",
    module: 21,
    level: 2,
    title: "A Korean meal",
    theme: "Bibimbap, bulgogi, and kimchi.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "친구는 뭐를 먹어요?",
        options: ["생선을 먹어요", "비빔밥을 먹어요", "라면을 먹어요"],
        answer: "생선을 먹어요",
      },
    ],
    sentences: [
      { text: "저는 식당에 가요.", translation: "I go to a restaurant." },
      { text: "비빔밥하고 불고기를 먹어요.", translation: "I eat bibimbap and bulgogi." },
      { text: "김치도 맛있어요.", translation: "The kimchi is tasty too." },
      { text: "라면도 좋아해요.", translation: "I like ramen too." },
      { text: "친구는 생선하고 채소를 먹어요.", translation: "My friend eats fish and vegetables." },
      { text: "과일도 먹어요.", translation: "We eat fruit too." },
      { text: "커피 한 잔 주세요.", translation: "One coffee, please." },
    ],
  },
  {
    id: "ko-m21-cooking-dinner",
    languageId: "ko",
    module: 21,
    level: 2,
    title: "Cooking dinner",
    theme: "A meal at home with a friend.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "친구는 뭐를 마셔요?",
        options: ["우유를 마셔요", "커피를 마셔요", "물을 마셔요"],
        answer: "우유를 마셔요",
      },
    ],
    sentences: [
      { text: "오늘은 집에서 밥을 먹어요.", translation: "Today I eat at home." },
      { text: "저는 불고기를 좋아해요.", translation: "I like bulgogi." },
      { text: "그래서 불고기하고 밥을 먹어요.", translation: "So I have bulgogi and rice." },
      { text: "김치도 있어요.", translation: "There's kimchi too." },
      { text: "친구도 집에 와요.", translation: "My friend comes over too." },
      { text: "우리는 라면하고 과일도 먹어요.", translation: "We eat ramen and fruit too." },
      { text: "저는 커피를 마시고 친구는 우유를 마셔요.", translation: "I drink coffee and my friend drinks milk." },
    ],
  },
  {
    // m21 stretch read — the first KO L5 (25-35 sentences). m21 is the food
    // module, so the food IS the plot rather than the list: the four refusals
    // in lines 3-6 are planted so the closing dialogue can pay two of them off
    // and leave one standing, and 자주 아파요 in line 8 is what the last line
    // answers. 요리 is m23, so the cooking is written with 밥을 했어요 /
    // 불고기를 했어요 — the only "cook" m21 can say. Note 하다 does NOT take
    // 고기/채소 as an object meaning "cook them"; the dish name has to carry it.
    id: "ko-m21-the-vegetables-in-the-bulgogi",
    languageId: "ko",
    module: 21,
    level: 5,
    title: "The vegetables in the bulgogi",
    theme: "My friend won't eat vegetables. So I stop naming them.",
    tags: ["food", "friends", "health"],
    glosses: [
      { surface: "많이", meaning: "a lot, plenty" },
      { surface: "정말", meaning: "really, truly" },
      { surface: "아직", meaning: "still, not yet" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "지금 유진은 뭐를 먹어요?",
        options: ["김치도 먹어요", "생선을 먹어요", "채소를 안 먹어요"],
        answer: "김치도 먹어요",
      },
    ],
    sentences: [
      { text: "유진은 채소를 싫어해요.", translation: "Yujin dislikes vegetables." },
      { text: "김치도 안 먹어요.", translation: "She doesn't eat kimchi either." },
      { text: "생선도 안 먹어요.", translation: "She doesn't eat fish either." },
      { text: "과일도 안 좋아해요.", translation: "She doesn't eat fruit either." },
      { text: "그런데 유진은 고기를 좋아해요.", translation: "But Yujin likes meat." },
      { text: "유진은 항상 라면을 먹어요.", translation: "Yujin always eats ramyeon." },
      { text: "그리고 유진은 자주 아파요.", translation: "And Yujin is often unwell." },
      { text: "유월에 유진이 병원에 갔어요.", translation: "In June Yujin went to the hospital." },
      { text: "채소하고 과일을 먹으면 괜찮을 거예요.", translation: "\"If you eat vegetables and fruit you'll be fine.\"" },
      { text: "그런데 유진은 라면을 먹었어요.", translation: "But Yujin ate ramyeon." },
      { text: "저는 채소를 좋아해요.", translation: "I like vegetables." },
      { text: "저는 밥을 해요.", translation: "I cook." },
      { text: "토요일에 저는 유진 집에서 불고기를 했어요.", translation: "On Saturday I made bulgogi at Yujin's place." },
      { text: "불고기에 채소가 많이 있어요.", translation: "There are a lot of vegetables in bulgogi." },
      { text: "그리고 김치도 있어요.", translation: "And there's kimchi too." },
      { text: "이거 뭐예요?", translation: "\"What's this?\"" },
      { text: "불고기예요.", translation: "\"It's bulgogi.\"" },
      { text: "유진은 불고기를 먹었어요.", translation: "Yujin ate the bulgogi." },
      { text: "그리고 많이 먹었어요.", translation: "And she ate a lot." },
      { text: "정말 맛있어요!", translation: "\"It's really delicious!\"" },
      { text: "유진은 밥을 모두 먹었어요.", translation: "Yujin ate all of it." },
      { text: "저는 일요일에도 월요일에도 불고기를 했어요.", translation: "On Sunday and on Monday I made bulgogi too." },
      { text: "화요일에 유진이 불고기를 봤어요.", translation: "On Tuesday Yujin looked at the bulgogi." },
      { text: "불고기에 뭐가 있어요?", translation: "\"What's in the bulgogi?\"" },
      { text: "채소가 있어요.", translation: "\"There are vegetables in it.\"" },
      { text: "저는 채소를 싫어해요. 그런데 민수 채소는 맛있어요.", translation: "\"I dislike vegetables. But your vegetables are delicious, Minsu.\"" },
      { text: "유진, 김치도 먹어요?", translation: "\"Yujin, do you eat kimchi too?\"" },
      { text: "네, 김치도 먹어요.", translation: "\"Yes, I eat kimchi too.\"" },
      { text: "생선도 먹어요?", translation: "\"Do you eat fish too?\"" },
      { text: "아니요. 생선은 아직 안 먹어요.", translation: "\"No. I still don't eat fish.\"" },
      { text: "유진은 시월에 병원에 안 갔어요.", translation: "Yujin didn't go to the hospital in October." },
    ],
  },
  {
    id: "ko-m22-which-i-like-more",
    languageId: "ko",
    module: 22,
    level: 2,
    title: "Which I like more",
    theme: "Comparing coffee and tea.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "뭐가 제일 좋아요?",
        options: ["커피예요", "차예요", "우유예요"],
        answer: "커피예요",
      },
    ],
    sentences: [
      { text: "저는 커피하고 차 중에서 커피가 더 좋아요.", translation: "Between coffee and tea, I like coffee more." },
      { text: "차는 커피보다 싸요.", translation: "Tea is cheaper than coffee." },
      { text: "그래도 커피가 제일 맛있어요.", translation: "Still, coffee is the tastiest." },
      { text: "친구는 차를 더 좋아해요.", translation: "My friend likes tea more." },
      { text: "뭐가 제일 좋아요?", translation: "What do you like best?" },
      { text: "커피가 가장 좋아요.", translation: "I like coffee best." },
      { text: "저는 커피를 자주 마셔요.", translation: "I drink coffee often." },
    ],
  },
  {
    id: "ko-m22-bibimbap-or-ramen",
    languageId: "ko",
    module: 22,
    level: 2,
    title: "Bibimbap or ramen?",
    theme: "Picking a favorite at the restaurant.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "이 식당은 뭐가 가장 맛있어요?",
        options: ["불고기예요", "비빔밥이에요", "라면이에요"],
        answer: "불고기예요",
      },
    ],
    sentences: [
      { text: "저는 비빔밥하고 라면 중에서 비빔밥이 더 좋아요.", translation: "Between bibimbap and ramen, I like bibimbap more." },
      { text: "라면은 비빔밥보다 싸요.", translation: "Ramen is cheaper than bibimbap." },
      { text: "그래도 비빔밥이 제일 맛있어요.", translation: "Still, bibimbap is the tastiest." },
      { text: "친구는 라면을 더 좋아해요.", translation: "My friend likes ramen more." },
      { text: "우리는 식당에서 밥을 먹어요.", translation: "We eat at a restaurant." },
      { text: "이 식당은 불고기가 가장 맛있어요.", translation: "This restaurant's bulgogi is the tastiest." },
      { text: "그래서 저는 이 식당을 좋아해요.", translation: "So I like this place." },
    ],
  },
  {
    // m22 stretch read (L5). m22's whole content is comparison — 보다 / 더 /
    // 제일 / 중에서 / 그래도 — so the story is a comparison the narrator has
    // been getting WRONG. The fare in line 10 is the plant; lines 23-26 are the
    // arithmetic that overturns the ranking; the last three lines change the
    // criterion from price to company.
    id: "ko-m22-the-cheaper-restaurant",
    languageId: "ko",
    module: 22,
    level: 5,
    title: "The cheaper restaurant",
    theme: "I always eat at the cheap place. Jisu finally does the arithmetic.",
    tags: ["food", "work", "money"],
    glosses: [
      { surface: "처음", meaning: "for the first time" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "역 식당 밥하고 지하철은 모두 얼마예요?",
        options: ["팔천 원이에요", "오천 원이에요", "육천오백 원이에요"],
        answer: "팔천 원이에요",
      },
    ],
    sentences: [
      { text: "회사 식당은 밥이 팔천 원이에요.", translation: "At the office restaurant a meal is 8,000 won." },
      { text: "역 식당은 밥이 오천 원이에요.", translation: "At the station restaurant a meal is 5,000 won." },
      { text: "오천 원은 팔천 원보다 싸요.", translation: "5,000 won is cheaper than 8,000 won." },
      { text: "그래서 저는 항상 역 식당에 가요.", translation: "So I always go to the station restaurant." },
      { text: "회사에서 역까지 지하철로 가요.", translation: "I go from the office to the station by subway." },
      { text: "지하철은 천오백 원이에요.", translation: "The subway is 1,500 won." },
      { text: "지수는 항상 회사 식당에 가요.", translation: "Jisu always goes to the office restaurant." },
      { text: "지수, 역 식당이 더 싸요.", translation: "\"Jisu, the station restaurant is cheaper.\"" },
      { text: "역 식당이 제일 싸요.", translation: "\"The station restaurant is the cheapest.\"" },
      { text: "그런데 지수는 안 가요.", translation: "But Jisu doesn't go." },
      { text: "월요일에 지수가 처음 저하고 역 식당에 갔어요.", translation: "On Monday Jisu went to the station restaurant with me for the first time." },
      { text: "우리는 열두 시에 지하철로 갔어요.", translation: "We went by subway at twelve." },
      { text: "열두 시 반에 우리는 비빔밥을 먹었어요.", translation: "At half past twelve we ate bibimbap." },
      { text: "비빔밥이 맛있었어요.", translation: "The bibimbap was delicious." },
      { text: "그런데 우리는 한 시에 회사에 못 갔어요.", translation: "But we couldn't get back to the office at one." },
      { text: "한 시 십오 분에 갔어요.", translation: "We got back at one fifteen." },
      { text: "민수, 역 식당 밥은 오천 원이에요.", translation: "\"Minsu, the station restaurant's meal is 5,000 won.\"" },
      { text: "그런데 지하철이 천오백 원이에요.", translation: "\"But the subway is 1,500 won.\"" },
      { text: "그리고 회사까지 천오백 원이에요.", translation: "\"And 1,500 won back to the office.\"" },
      { text: "밥하고 지하철은 모두 팔천 원이에요.", translation: "\"The meal and the subway are 8,000 won altogether.\"" },
      { text: "회사 식당 밥도 팔천 원이에요.", translation: "\"The office restaurant's meal is 8,000 won too.\"" },
      { text: "저는 유월부터 역 식당에 갔어요.", translation: "I had been going to the station restaurant since June." },
      { text: "그래도 저는 역 식당이 더 좋아요.", translation: "Still, I like the station restaurant more." },
      { text: "역 식당 비빔밥은 회사 식당 밥보다 맛있어요.", translation: "The station restaurant's bibimbap is tastier than the office restaurant's food." },
      { text: "저는 금요일에 역 식당에 가요.", translation: "I go to the station restaurant on Fridays." },
      { text: "그리고 월요일부터 목요일까지 지수하고 회사 식당에서 밥을 먹어요.", translation: "And from Monday to Thursday I eat at the office restaurant with Jisu." },
      { text: "회사 식당 밥은 별로 안 맛있어요.", translation: "The office restaurant's food isn't very good." },
      { text: "그런데 지수가 있어요.", translation: "But Jisu is there." },
    ],
  },
  {
    id: "ko-m23-weekend-plans",
    languageId: "ko",
    module: 23,
    level: 2,
    title: "Weekend plans",
    theme: "Cooking and doing things together.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "저는 뭐를 못해요?",
        options: ["노래를 못해요", "요리를 못해요", "수영을 못해요"],
        answer: "노래를 못해요",
      },
    ],
    sentences: [
      { text: "주말에 뭐 할까요?", translation: "What shall we do on the weekend?" },
      { text: "저는 요리를 잘해요.", translation: "I'm good at cooking." },
      { text: "같이 요리할까요?", translation: "Shall we cook together?" },
      { text: "저는 수영도 잘해요.", translation: "I'm good at swimming too." },
      { text: "그런데 노래는 못해요.", translation: "But I can't sing." },
      { text: "주말에 같이 운동합시다.", translation: "Let's exercise together on the weekend." },
      { text: "그리고 같이 밥도 먹어요.", translation: "And let's eat together too." },
    ],
  },
  {
    // m23 stretch read (L5). m23 teaches 잘해요 / 못해요 and the 할까요 /
    // 합시다 proposal forms, so the story is a boast about being 잘해요 coming
    // due. The lie in line 5 is the plant; Saturday is the bill; the mirror in
    // the last four lines is Mina volunteering her own 못해요 and doing it
    // anyway, which is the change the narrator needed.
    id: "ko-m23-i-said-i-could-cook",
    languageId: "ko",
    module: 23,
    level: 5,
    title: "I said I could cook",
    theme: "One boast in June, four friends on Saturday.",
    tags: ["cooking", "friends", "hobbies"],
    glosses: [
      { surface: "웃었어요", meaning: "laughed, smiled" },
      { surface: "정말", meaning: "really, truly" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "토요일에 우리는 뭐를 먹었어요?",
        options: ["라면을 먹었어요", "불고기를 먹었어요", "비빔밥을 먹었어요"],
        answer: "라면을 먹었어요",
      },
    ],
    sentences: [
      { text: "미나는 제 친구예요.", translation: "Mina is my friend." },
      { text: "미나는 요리를 잘해요.", translation: "Mina is good at cooking." },
      { text: "미나는 수영도 잘해요.", translation: "Mina is good at swimming too." },
      { text: "저는 미나를 좋아해요.", translation: "I like Mina." },
      { text: "유월에 저는 미나하고 커피를 마셨어요.", translation: "In June I had a coffee with Mina." },
      { text: "저도 요리를 잘해요.", translation: "\"I'm good at cooking too.\"" },
      { text: "그런데 저는 요리를 못해요.", translation: "But I'm bad at cooking." },
      { text: "저는 항상 라면을 먹어요.", translation: "I always eat ramyeon." },
      { text: "칠월에 미나가 저하고 수영했어요.", translation: "In July Mina went swimming with me." },
      { text: "주말에 같이 요리할까요?", translation: "\"Shall we cook together this weekend?\"" },
      { text: "민수, 친구가 네 명 와요.", translation: "\"Minsu, four friends are coming.\"" },
      { text: "네. 저는 요리를 잘해요.", translation: "\"Sure. I'm good at cooking.\"" },
      { text: "그런데 저는 요리를 못해요.", translation: "But I'm bad at cooking." },
      { text: "저는 목요일에 밥을 했어요.", translation: "On Thursday I cooked." },
      { text: "밥이 별로 안 맛있었어요.", translation: "The food wasn't very good." },
      { text: "금요일에도 밥을 했어요.", translation: "On Friday I cooked too." },
      { text: "그런데 밥이 안 맛있었어요.", translation: "But the food wasn't good." },
      { text: "저는 전화하고 싶어요.", translation: "I want to call." },
      { text: "그런데 못 했어요.", translation: "But I couldn't." },
      { text: "토요일에 저는 미나 집에 갔어요.", translation: "On Saturday I went to Mina's house." },
      { text: "미나 집에 친구가 네 명 왔어요.", translation: "Four friends came to Mina's house." },
      { text: "민수, 불고기를 할까요?", translation: "\"Minsu, shall we make bulgogi?\"" },
      { text: "저는 불고기를 했어요.", translation: "I made the bulgogi." },
      { text: "불고기가 안 맛있었어요.", translation: "The bulgogi wasn't good." },
      { text: "친구가 모두 안 먹었어요.", translation: "None of the friends ate." },
      { text: "저는 요리를 못해요.", translation: "\"I'm bad at cooking.\"" },
      { text: "미나가 웃었어요.", translation: "Mina laughed." },
      { text: "괜찮아요.", translation: "\"It's all right.\"" },
      { text: "그리고 우리는 라면을 먹었어요.", translation: "And we ate ramyeon." },
      { text: "라면이 맛있었어요.", translation: "The ramyeon was delicious." },
      { text: "그런데 미나는 노래를 못해요.", translation: "But Mina is bad at singing." },
      { text: "그래도 미나가 노래했어요.", translation: "Even so, Mina sang." },
      { text: "미나는 노래를 정말 못해요.", translation: "Mina really is bad at singing." },
      { text: "그런데 우리는 모두 좋았어요.", translation: "But we were all glad." },
    ],
  },
  {
    id: "ko-m24-my-hobbies",
    languageId: "ko",
    module: 24,
    level: 2,
    title: "My hobbies",
    theme: "Music, photos, and a bit of singing.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "제 취미는 뭐예요?",
        options: ["음악이에요", "게임이에요", "요리예요"],
        answer: "음악이에요",
      },
    ],
    sentences: [
      { text: "제 취미는 음악이에요.", translation: "My hobby is music." },
      { text: "저는 음악을 자주 들어요.", translation: "I listen to music often." },
      { text: "사진도 좋아해요.", translation: "I like photography too." },
      { text: "노래도 할 줄 알아요.", translation: "I also know how to sing." },
      { text: "일주일에 두 번 게임을 해요.", translation: "I play games twice a week." },
      { text: "저는 그림도 좋아해요.", translation: "I like drawing too." },
      { text: "주말에 같이 할까요?", translation: "Shall we do it together on the weekend?" },
    ],
  },
  {
    id: "ko-m24-music-and-games",
    languageId: "ko",
    module: 24,
    level: 2,
    title: "Music and games",
    theme: "Sharing hobbies with a friend.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "친구는 뭐를 좋아해요?",
        options: ["게임을 좋아해요", "노래를 좋아해요", "사진을 좋아해요"],
        answer: "게임을 좋아해요",
      },
    ],
    sentences: [
      { text: "저는 음악을 좋아해요.", translation: "I like music." },
      { text: "저는 노래도 할 줄 알아요.", translation: "I also know how to sing." },
      { text: "일주일에 세 번 노래해요.", translation: "I sing three times a week." },
      { text: "친구는 게임을 좋아해요.", translation: "My friend likes games." },
      { text: "우리는 같이 게임을 해요.", translation: "We play games together." },
      { text: "저는 사진도 좋아해요.", translation: "I like photos too." },
      { text: "취미가 뭐예요?", translation: "What's your hobby?" },
    ],
  },
  {
    // m24 stretch read (L5). m24 adds 취미 / 음악 / 그림 / 할 줄 알아요 and the
    // 일주일에 N 번 frequency frame. Structure: the narrator's secret is stated
    // in lines 4-6 and pressed on for half the story; the reversal is finding
    // the SAME secret in Jisu's bag, which is what makes an audience of one
    // possible. Last line refuses the tidy ending: the office still doesn't know.
    id: "ko-m24-an-audience-of-one",
    languageId: "ko",
    module: 24,
    level: 5,
    title: "An audience of one",
    theme: "I sing only when nobody can hear. So does someone else.",
    tags: ["hobbies", "music", "friends"],
    glosses: [
      { surface: "혼자", meaning: "alone, by myself" },
      { surface: "사람", meaning: "person, people" },
      { surface: "몰라요", meaning: "doesn't know" },
      { surface: "들었어요", meaning: "heard, listened to" },
      { surface: "아직", meaning: "still, not yet" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "민수는 주말에 어디에서 노래했어요?",
        options: ["지수 집에서 노래했어요", "식당에서 노래했어요", "회사에서 노래했어요"],
        answer: "지수 집에서 노래했어요",
      },
    ],
    sentences: [
      { text: "저는 혼자 노래해요.", translation: "I sing alone." },
      { text: "회사 사람은 몰라요.", translation: "The people at the office don't know." },
      { text: "집에서 저는 음악을 들어요.", translation: "At home I listen to music." },
      { text: "음악은 제 취미예요.", translation: "Music is my hobby." },
      { text: "그리고 저는 노래해요.", translation: "And I sing." },
      { text: "그런데 회사에서는 안 해요.", translation: "But at the office I don't." },
      { text: "시월 주말에 회사 사람이 모두 식당에서 만나요.", translation: "On a weekend in October everyone from the office meets at a restaurant." },
      { text: "거기에서 사람이 노래해요.", translation: "People sing there." },
      { text: "저는 그 식당에 안 가고 싶어요.", translation: "I don't want to go to that restaurant." },
      { text: "화요일에 지수가 우리 집에 왔어요.", translation: "On Tuesday Jisu came to my house." },
      { text: "지수가 문에서 제 노래를 들었어요.", translation: "Jisu heard my singing at the door." },
      { text: "민수는 노래를 할 줄 알아요!", translation: "\"Minsu knows how to sing!\"" },
      { text: "저는 노래를 못해요.", translation: "\"I'm bad at singing.\"" },
      { text: "민수, 주말에 식당에서 노래해요.", translation: "\"Minsu, sing at the restaurant this weekend.\"" },
      { text: "못 해요.", translation: "\"I can't.\"" },
      { text: "수요일에도 목요일에도 지수가 우리 회사에 왔어요.", translation: "Jisu came to my office on Wednesday and on Thursday too." },
      { text: "금요일에 저는 지수 가방에서 그림을 봤어요.", translation: "On Friday I saw a drawing in Jisu's bag." },
      { text: "그림이 예뻐요.", translation: "The drawing is pretty." },
      { text: "지수, 이 그림은 누구 거예요?", translation: "\"Jisu, whose drawing is this?\"" },
      { text: "제 거예요.", translation: "\"It's mine.\"" },
      { text: "그런데 회사 사람은 몰라요.", translation: "\"But the people at the office don't know.\"" },
      { text: "주말에 저는 그 식당에 안 갔어요.", translation: "That weekend I didn't go to that restaurant." },
      { text: "그런데 지수 집에 갔어요.", translation: "But I went to Jisu's house." },
      { text: "지수 집에서 저는 노래했어요.", translation: "At Jisu's house I sang." },
      { text: "그리고 저는 지수 그림을 봤어요.", translation: "And I looked at Jisu's drawing." },
      { text: "우리는 두 명이에요.", translation: "There are two of us." },
      { text: "지금 저는 일주일에 한 번 지수 집에서 노래해요.", translation: "Now I sing at Jisu's house once a week." },
      { text: "그리고 회사 사람은 아직 몰라요.", translation: "And the people at the office still don't know." },
    ],
  },
  {
    id: "ko-m25-planning-a-trip",
    languageId: "ko",
    module: 25,
    level: 2,
    title: "Planning a trip",
    theme: "A trip to Japan and a hot spring.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "어디에 가려고 해요?",
        options: ["일본에 가려고 해요", "한국에 가려고 해요", "학교에 가려고 해요"],
        answer: "일본에 가려고 해요",
      },
    ],
    sentences: [
      { text: "저는 여행 계획이 있어요.", translation: "I have travel plans." },
      { text: "저는 일본에 가려고 해요.", translation: "I intend to go to Japan." },
      { text: "일본에 간 적이 있어요.", translation: "I've been to Japan before." },
      { text: "온천에 가고 싶어요.", translation: "I want to go to a hot spring." },
      { text: "축제도 보고 싶어요.", translation: "I want to see a festival too." },
      { text: "다음 주말에 출발해요.", translation: "I leave next weekend." },
      { text: "저는 여행을 좋아해요.", translation: "I like traveling." },
    ],
  },
  {
    id: "ko-m25-trip-with-a-friend",
    languageId: "ko",
    module: 25,
    level: 2,
    title: "A trip with a friend",
    theme: "Two friends heading to Japan.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "저는 뭐를 하고 싶어요?",
        options: ["온천에 가고 싶어요", "축제를 보고 싶어요", "집에 가고 싶어요"],
        answer: "온천에 가고 싶어요",
      },
    ],
    sentences: [
      { text: "친구하고 여행 계획이 있어요.", translation: "My friend and I have travel plans." },
      { text: "우리는 일본에 가려고 해요.", translation: "We intend to go to Japan." },
      { text: "친구는 일본에 간 적이 있어요.", translation: "My friend has been to Japan before." },
      { text: "저는 온천에 가고 싶어요.", translation: "I want to go to a hot spring." },
      { text: "친구는 축제를 보고 싶어요.", translation: "My friend wants to see a festival." },
      { text: "우리는 다음 주말에 출발해요.", translation: "We leave next weekend." },
      { text: "일본에서 비빔밥을 먹어요.", translation: "We'll eat bibimbap in Japan." },
    ],
  },
  {
    // m25 stretch read (L5). m25 supplies 여행 / 계획 / 출발 / 도착 / 외국 /
    // 졸업 plus 가려고 and the 간 적이 있어요 experience frame. The three
    // postponements are not filler: the reveal in line 27 dates Jun's decision
    // to September, which retro-colours the last two of them — he let the
    // farewell trip keep failing after it had stopped being a farewell.
    id: "ko-m25-the-goodbye-trip",
    languageId: "ko",
    module: 25,
    level: 5,
    title: "The goodbye trip",
    theme: "A farewell trip for a friend who turns out not to be leaving.",
    tags: ["travel", "friends", "plans"],
    glosses: [
      { surface: "있었어요", meaning: "was there, stayed", atomId: "ko:있어요" },
      { surface: "결정했어요", meaning: "decided", atomId: "ko:결정하다" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "준은 언제 결정했어요?",
        options: ["구월에 결정했어요", "시월에 결정했어요", "유월에 결정했어요"],
        answer: "구월에 결정했어요",
      },
    ],
    sentences: [
      { text: "준은 유월에 졸업했어요.", translation: "Jun graduated in June." },
      { text: "그리고 준은 시월에 외국에 가요.", translation: "And Jun goes abroad in October." },
      { text: "저는 준하고 여행을 가려고 해요.", translation: "I intend to take a trip with Jun." },
      { text: "저는 여행을 계획했어요.", translation: "I planned the trip." },
      { text: "우리는 일본에 가요.", translation: "We go to Japan." },
      { text: "저는 일본에 간 적이 있어요.", translation: "I've been to Japan before." },
      { text: "그런데 준은 일본에 간 적이 없어요.", translation: "But Jun has never been to Japan." },
      { text: "저는 온천하고 축제를 계획했어요.", translation: "I planned a hot spring and a festival." },
      { text: "준은 칠월에 회사에서 바빠서 못 갔어요.", translation: "In July Jun was busy at work, so he couldn't go." },
      { text: "그래서 우리는 팔월에 가요.", translation: "So we go in August." },
      { text: "팔월에도 준은 바빠서 못 갔어요.", translation: "In August too Jun was busy, so he couldn't go." },
      { text: "구월에도 못 갔어요.", translation: "In September he couldn't go either." },
      { text: "저는 시월 계획을 했어요.", translation: "I made an October plan." },
      { text: "시월에 준은 외국에 가요.", translation: "In October Jun goes abroad." },
      { text: "그래서 우리는 시월 금요일에 출발했어요.", translation: "So we left on a Friday in October." },
      { text: "우리는 비행기로 갔어요.", translation: "We went by plane." },
      { text: "우리는 세 시에 일본에 도착했어요.", translation: "We arrived in Japan at three." },
      { text: "토요일에 축제에 갔어요.", translation: "On Saturday we went to the festival." },
      { text: "축제가 좋았어요.", translation: "The festival was good." },
      { text: "일요일에 우리는 온천에 갔어요.", translation: "On Sunday we went to the hot spring." },
      { text: "온천에서 우리는 세 시간 있었어요.", translation: "We stayed three hours at the hot spring." },
      { text: "준, 외국에서 전화해요.", translation: "\"Jun, call me from abroad.\"" },
      { text: "저는 외국에 안 가요.", translation: "\"I'm not going abroad.\"" },
      { text: "저는 구월에 결정했어요.", translation: "\"I decided in September.\"" },
      { text: "준, 이 여행은 왜 했어요?", translation: "\"Jun, why did we take this trip?\"" },
      { text: "준은 저하고 여행을 좋아해요.", translation: "Jun likes travelling with me." },
      { text: "저는 그래도 좋았어요.", translation: "Still, I was glad." },
      { text: "우리는 온천에서 고기를 먹었어요.", translation: "We ate meat at the hot spring." },
      { text: "그리고 우리는 다음 여행을 계획했어요.", translation: "And we planned the next trip." },
    ],
  },
  {
    id: "ko-m26-a-rough-morning",
    languageId: "ko",
    module: 26,
    level: 2,
    title: "A rough morning",
    theme: "Late, tired, and a traffic jam.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "왜 회사에 늦었어요?",
        options: ["길이 막혔거든요", "피곤해요", "실수했어요"],
        answer: "길이 막혔거든요",
      },
    ],
    sentences: [
      { text: "오늘 회사에 늦었어요.", translation: "I was late for work today." },
      { text: "길이 너무 막혔거든요.", translation: "The road was really jammed, you see." },
      { text: "죄송해요.", translation: "I'm sorry." },
      { text: "저는 너무 피곤해요.", translation: "I'm so tired." },
      { text: "그리고 실수도 했어요.", translation: "And I made a mistake too." },
      { text: "저는 피곤해서 집에 가고 싶어요.", translation: "I'm tired, so I want to go home." },
      { text: "하지만 내일은 회사에 가요.", translation: "But tomorrow I go to work." },
    ],
  },
  {
    // m26 stretch read (L5). m26 is the excuses module — 피곤해요 / 늦었어요 /
    // 실수 / 막혔거든요 / 잊어버리다 / 죄송해요 — so the week of exhaustion in
    // lines 1-14 is built to make the forgotten meeting inevitable rather than
    // careless. The reversal is symmetry: Mina forgot in exactly the same way,
    // asleep in transit, which is why the apology in line 29 still stands.
    id: "ko-m26-the-three-oclock-i-forgot",
    languageId: "ko",
    module: 26,
    level: 5,
    title: "The three o'clock I forgot",
    theme: "A week too tired to remember, and I wasn't the only one.",
    tags: ["work", "friends", "daily-life"],
    glosses: [
      { surface: "계속", meaning: "continuously, the whole time" },
      { surface: "잊어버렸어요", meaning: "forgot", atomId: "ko:잊어버리다" },
      { surface: "잤어요", meaning: "slept, fell asleep", atomId: "ko:자다" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "미나는 금요일 세 시에 뭐를 했어요?",
        options: ["지하철에서 잤어요", "역에서 밥을 먹었어요", "회사에서 공부했어요"],
        answer: "지하철에서 잤어요",
      },
    ],
    sentences: [
      { text: "저는 너무 바빠서 피곤해요.", translation: "I'm so busy, I'm tired." },
      { text: "월요일부터 금요일까지 계속 회사에 있어요.", translation: "From Monday to Friday I'm at the office the whole time." },
      { text: "화요일에 미나가 우리 회사에 왔어요.", translation: "On Tuesday Mina came to my office." },
      { text: "민수, 금요일 세 시에 역에서 만나요.", translation: "\"Minsu, let's meet at the station at three on Friday.\"" },
      { text: "네, 좋아요.", translation: "\"Yes, sounds good.\"" },
      { text: "그런데 잊어버렸어요.", translation: "But I forgot." },
      { text: "수요일에 저는 회사에서 실수했어요.", translation: "On Wednesday I made a mistake at the office." },
      { text: "목요일에도 실수했어요.", translation: "On Thursday I made a mistake too." },
      { text: "저는 너무 피곤해서 밥도 안 먹었어요.", translation: "I was too tired, so I didn't even eat." },
      { text: "금요일 아홉 시에 회사에 갔어요.", translation: "At nine on Friday I went to the office." },
      { text: "저는 늦었어요.", translation: "I was late." },
      { text: "길이 너무 막혔거든요.", translation: "The road was really jammed, you see." },
      { text: "죄송해요.", translation: "\"I'm sorry.\"" },
      { text: "세 시에 저는 회사에서 공부했어요.", translation: "At three I was studying at the office." },
      { text: "저는 미나를 잊어버렸어요.", translation: "I forgot about Mina." },
      { text: "저는 너무 피곤해서 여섯 시에 잤어요.", translation: "I was too tired, so I slept at six." },
      { text: "여덟 시에 전화가 왔어요.", translation: "At eight a call came." },
      { text: "미나예요.", translation: "It's Mina." },
      { text: "민수, 지금 어디에 있어요?", translation: "\"Minsu, where are you right now?\"" },
      { text: "저는 집에 있어요.", translation: "\"I'm at home.\"" },
      { text: "죄송해요! 저는 잊어버렸어요.", translation: "\"I'm sorry! I forgot.\"" },
      { text: "민수, 저도 죄송해요.", translation: "\"Minsu, I'm sorry too.\"" },
      { text: "미나도 잊어버렸어요.", translation: "Mina forgot too." },
      { text: "미나는 세 시에 지하철에서 잤어요.", translation: "At three Mina was asleep on the subway." },
      { text: "미나도 여섯 시에 집에 왔어요.", translation: "Mina got home at six too." },
      { text: "하지만 저는 죄송해요.", translation: "But I'm sorry." },
      { text: "그래서 일요일에 저는 미나하고 불고기를 먹었어요.", translation: "So on Sunday I had bulgogi with Mina." },
      { text: "미나도 너무 피곤해요.", translation: "Mina is so tired too." },
      { text: "미나, 다음 금요일에도 세 시에 역에서 만나요?", translation: "\"Mina, shall we meet at the station at three next Friday too?\"" },
      { text: "네. 그런데 두 시에 전화해요.", translation: "\"Yes. But call me at two.\"" },
    ],
  },
  {
    id: "ko-m27-before-the-exam",
    languageId: "ko",
    module: 27,
    level: 2,
    title: "Before the exam",
    theme: "Getting ready, and taking care.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "쉬면 어떻게 돼요?",
        options: ["건강해져요", "피곤해요", "괜찮을 거예요"],
        answer: "건강해져요",
      },
    ],
    sentences: [
      { text: "내일은 시험이 있어요.", translation: "I have an exam tomorrow." },
      { text: "저는 시험 준비를 해요.", translation: "I'm getting ready for the exam." },
      { text: "오늘은 연습해요.", translation: "Today I practice." },
      { text: "저는 너무 피곤해요.", translation: "I'm so tired." },
      { text: "쉬면 건강해져요.", translation: "If I rest, I'll get healthy." },
      { text: "그래서 저는 약속을 안 해요.", translation: "So I don't make plans." },
      { text: "조심하세요.", translation: "Take care." },
    ],
  },
  {
    // m27 stretch read (L5) — the top of the Korean ladder. m27's own atoms are
    // 약속 / 준비 / 연습 / 시험 / 건강 / 결정하다, so the story is literally a
    // decision between a promise and an exam. Mom's line 12 ("쉬면 건강해져요")
    // is planted so that Jisu can hand it back in line 32 as the reason she
    // took him away — the choice the narrator agonised over was never a choice.
    id: "ko-m27-the-promise-and-the-exam",
    languageId: "ko",
    module: 27,
    level: 5,
    title: "The promise and the exam",
    theme: "An exam on Monday, a promise made in June, one Thursday to choose.",
    tags: ["study", "friends", "health"],
    glosses: [
      { surface: "몰랐어요", meaning: "didn't know" },
      { surface: "쉬었어요", meaning: "rested", atomId: "ko:쉬다" },
      { surface: "결정했어요", meaning: "decided", atomId: "ko:결정하다" },
      { surface: "계속", meaning: "continuously, without stopping" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "지수는 왜 민수하고 바다에 갔어요?",
        options: ["민수는 쉬면 건강해져요", "지수는 바다를 좋아해요", "민수는 시험이 없어요"],
        answer: "민수는 쉬면 건강해져요",
      },
    ],
    sentences: [
      { text: "유월에 저는 지수하고 약속했어요.", translation: "In June I made a promise with Jisu." },
      { text: "시월 주말에 같이 바다에 가요.", translation: "\"Let's go to the sea together on a weekend in October.\"" },
      { text: "유월에 저는 시험을 몰랐어요.", translation: "In June I didn't know about the exam." },
      { text: "팔월부터 저는 시험 준비를 했어요.", translation: "From August I got ready for the exam." },
      { text: "시험은 시월에 있어요.", translation: "The exam is in October." },
      { text: "저는 아홉 시부터 열두 시까지 공부했어요.", translation: "I studied from nine until twelve." },
      { text: "그리고 토요일에도 연습했어요.", translation: "And on Saturdays I practised too." },
      { text: "구월에 저는 계속 공부했어요.", translation: "In September I kept studying." },
      { text: "엄마가 제 책을 봤어요.", translation: "My mom looked at my books." },
      { text: "쉬면 건강해져요.", translation: "\"If you rest you'll get healthy.\"" },
      { text: "조심하세요.", translation: "\"Take care.\"" },
      { text: "그런데 저는 안 쉬었어요.", translation: "But I didn't rest." },
      { text: "시월에 지수가 전화했어요.", translation: "In October Jisu called." },
      { text: "이번 주말에 바다에 가요?", translation: "\"Are we going to the sea this weekend?\"" },
      { text: "시험은 월요일에 있어요.", translation: "\"The exam is on Monday.\"" },
      { text: "주말에 공부해요.", translation: "\"I'm studying at the weekend.\"" },
      { text: "죄송해요.", translation: "\"I'm sorry.\"" },
      { text: "그런데 저는 유월에 약속했어요.", translation: "But I made the promise in June." },
      { text: "목요일에 저는 결정했어요.", translation: "On Thursday I decided." },
      { text: "지수, 주말에 바다에 가요.", translation: "\"Jisu, let's go to the sea at the weekend.\"" },
      { text: "토요일에 우리는 기차로 갔어요.", translation: "On Saturday we went by train." },
      { text: "우리는 바다를 봤어요.", translation: "We looked at the sea." },
      { text: "우리는 바다에서 밥을 먹었어요.", translation: "We ate at the sea." },
      { text: "저는 세 시간 쉬었어요.", translation: "I rested for three hours." },
      { text: "일요일에 우리는 기차로 갔어요.", translation: "On Sunday we travelled back by train." },
      { text: "지수는 제 시험을 알아요.", translation: "Jisu knows about my exam." },
      { text: "지수는 팔월부터 알아요.", translation: "Jisu has known since August." },
      { text: "그런데 왜 바다에 가요?", translation: "\"But why are we going to the sea?\"" },
      { text: "민수는 쉬면 건강해져요.", translation: "\"If you rest, you'll get healthy, Minsu.\"" },
      { text: "월요일에 저는 시험을 봤어요.", translation: "On Monday I took the exam." },
      { text: "그리고 저는 지수하고 계획했어요.", translation: "And then I made a plan with Jisu." },
      { text: "지수, 십이월에도 바다에 가요.", translation: "\"Jisu, let's go to the sea in December too.\"" },
    ],
  },
];
