/**
 * STORIES are newly authored for early-mid modules using only in-module
 * vocab (gate-verified). Density ramp: sparse early -> richer late.
 */
import type { Story } from "../types";

export const KO_STORIES: Story[] = [
  // ── Early (m3-m8): sparse, ~1 story per 2 modules ──────────────────────────
  {
    id: "ko-m3-new-friend",
    languageId: "ko",
    module: 3,
    level: 1,
    title: "A new classmate",
    theme: "Introducing yourself on the first day.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "이름이 뭐예요?",
        options: ["민수예요", "미나예요", "지수예요"],
        answer: "민수예요",
      },
    ],
    sentences: [
      { text: "안녕하세요.", translation: "Hello." },
      { text: "저는 학생이에요.", translation: "I'm a student." },
      { text: "이름이 민수예요.", translation: "My name is Minsu." },
      { text: "이름이 뭐예요?", translation: "What's your name?" },
      { text: "친구도 학생이에요.", translation: "My friend is a student too." },
      { text: "반갑습니다.", translation: "Nice to meet you." },
    ],
  },
  {
    // m3 stretch read (m3 caps at L2). Copula-only pool: the ONLY predicate
    // available is 이에요/예요, so the arc has to be carried by identity —
    // hence a mistaken-identity turn. 있어요 (m6) and 그런데 (m8) are the two
    // gloss slots; without 그런데 m3 has no connective at all.
    id: "ko-m3-who-is-that",
    languageId: "ko",
    module: 3,
    level: 2,
    title: "Is that Jisu?",
    theme: "A cheerful hello to entirely the wrong person.",
    tags: ["school", "greetings"],
    glosses: [
      { surface: "있어요", meaning: "there is, is (here)", atomId: "ko:있어요" },
      { surface: "그런데", meaning: "but, and yet", atomId: "ko:그런데" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "유진은 누구예요?",
        options: ["선생님이에요", "학생이에요", "친구예요"],
        answer: "선생님이에요",
      },
    ],
    sentences: [
      { text: "여기는 교실이에요.", translation: "This is the classroom." },
      { text: "교실에 학생이 있어요.", translation: "There are students in the classroom." },
      { text: "저는 민수예요.", translation: "I'm Minsu." },
      { text: "거기에 지수가 있어요?", translation: "Is that Jisu over there?" },
      { text: "안녕, 지수!", translation: "Hi, Jisu!" },
      { text: "아니요. 저는 유진이에요.", translation: "No. I'm Yujin." },
      { text: "그런데 유진은 선생님이에요.", translation: "But Yujin is the teacher." },
      { text: "죄송합니다!", translation: "I'm so sorry!" },
      { text: "괜찮아요. 반갑습니다.", translation: "It's all right. Nice to meet you." },
    ],
  },
  {
    // m4 stretch read. Same copula-only constraint as m3, so the arc is a
    // small identification mystery built out of m4's object nouns plus the
    // 제 거예요 / 누구 거예요 possessive frame m4 teaches.
    id: "ko-m4-whose-bag",
    languageId: "ko",
    module: 4,
    level: 2,
    title: "Whose bag?",
    theme: "A bag on a chair, and nobody claiming it.",
    tags: ["school", "objects"],
    glosses: [
      { surface: "있어요", meaning: "there is, is (here)", atomId: "ko:있어요" },
      { surface: "그런데", meaning: "but, and yet", atomId: "ko:그런데" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "이 가방은 누구 거예요?",
        options: ["유진 거예요", "지수 거예요", "제 거예요"],
        answer: "유진 거예요",
      },
    ],
    sentences: [
      { text: "의자에 가방이 있어요.", translation: "There's a bag on a chair." },
      { text: "이거는 제 가방이에요?", translation: "Is this my bag?" },
      { text: "아니요. 제 가방은 여기에 있어요.", translation: "No. My bag is right here." },
      { text: "그런데 이 가방은 누구 거예요?", translation: "So whose bag is this one?" },
      { text: "지수 거예요?", translation: "Is it Jisu's?" },
      { text: "지수 가방은 저거예요.", translation: "Jisu's bag is that one over there." },
      { text: "가방에 책이 있어요.", translation: "There's a book in the bag." },
      { text: "책에 이름이 있어요.", translation: "There's a name in the book." },
      { text: "이름이 유진이에요.", translation: "The name is Yujin." },
      { text: "이 가방은 유진 거예요.", translation: "So this bag is Yujin's." },
    ],
  },
  {
    id: "ko-m5-cafe-morning",
    languageId: "ko",
    module: 5,
    level: 1,
    title: "Morning at the cafe",
    theme: "A quick coffee run.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "이거 얼마예요?",
        options: ["사천 원이에요", "오천 원이에요", "삼천 원이에요"],
        answer: "사천 원이에요",
      },
    ],
    sentences: [
      { text: "커피 두 잔 주세요.", translation: "Two coffees, please." },
      { text: "물도 한 잔 주세요.", translation: "One water too, please." },
      { text: "빵도 주세요.", translation: "Bread too, please." },
      { text: "이거 얼마예요?", translation: "How much is this?" },
      { text: "사천 원이에요.", translation: "It's 4,000 won." },
      { text: "감사합니다.", translation: "Thank you." },
    ],
  },
  {
    // m5 stretch read. m5 has no place nouns and no verbs yet, so the whole
    // story is a counter drill turned into a miscount-and-fix: counters +
    // 주세요 + prices are the module's entire content, and the arc is the
    // number that changes under the narrator.
    id: "ko-m5-one-more-bread",
    languageId: "ko",
    module: 5,
    level: 2,
    title: "One more piece of bread",
    theme: "A count that comes up one short at the counter.",
    tags: ["food", "shopping", "numbers"],
    glosses: [{ surface: "그런데", meaning: "but, and yet", atomId: "ko:그런데" }],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "빵 다섯 개는 얼마예요?",
        options: ["오천 원이에요", "사천 원이에요", "삼천 원이에요"],
        answer: "오천 원이에요",
      },
    ],
    sentences: [
      { text: "제 친구는 네 명이에요.", translation: "I have four friends." },
      { text: "빵 네 개 주세요.", translation: "Four pieces of bread, please." },
      { text: "얼마예요?", translation: "How much is that?" },
      { text: "사천 원이에요.", translation: "That's 4,000 won." },
      { text: "네, 감사합니다.", translation: "Yes, thank you." },
      { text: "그런데 우리 친구는 다섯 명이에요!", translation: "But hold on — there are five of us!" },
      { text: "빵 한 개 주세요.", translation: "One more piece of bread, please." },
      { text: "얼마예요?", translation: "And how much now?" },
      { text: "오천 원이에요.", translation: "It's 5,000 won." },
      { text: "빵이 다섯 개예요.", translation: "Five pieces of bread. That's everyone." },
    ],
  },
  {
    // m6 stretch read. m6 finally supplies places + 있어요/없어요, so this is
    // the first KO story with somewhere to be. Motion is bought with one
    // gloss (가요, m7) so the last line can actually leave.
    id: "ko-m6-no-restaurant-at-the-station",
    languageId: "ko",
    module: 6,
    level: 2,
    title: "No restaurant at the station",
    theme: "Hungry, out of time, and in the wrong building.",
    tags: ["travel", "food"],
    glosses: [
      { surface: "그런데", meaning: "but, and yet", atomId: "ko:그런데" },
      { surface: "가요", meaning: "go, am going", atomId: "ko:가요" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "역에 뭐가 있어요?",
        options: ["가게가 있어요", "식당이 있어요", "병원이 있어요"],
        answer: "가게가 있어요",
      },
    ],
    sentences: [
      { text: "여기는 역이에요.", translation: "I'm at the station." },
      { text: "저는 시간이 없어요.", translation: "I don't have much time." },
      { text: "역에 식당이 있어요?", translation: "Is there a restaurant in the station?" },
      { text: "아니요, 식당이 없어요.", translation: "No — there's no restaurant." },
      { text: "그런데 가게가 있어요.", translation: "But there is a shop." },
      { text: "가게에 빵이 있어요.", translation: "The shop has bread." },
      { text: "빵 두 개 주세요.", translation: "Two pieces of bread, please." },
      { text: "제 가방에 빵이 있어요.", translation: "Now there's bread in my bag." },
      { text: "저는 학교에 가요.", translation: "And I'm off to school." },
    ],
  },
  {
    id: "ko-m7-my-day",
    languageId: "ko",
    module: 7,
    level: 1,
    title: "My afternoon",
    theme: "A simple run-through of an afternoon.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "친구는 어디에 있어요?",
        options: ["학교에 있어요", "집에 있어요", "식당에 있어요"],
        answer: "학교에 있어요",
      },
    ],
    sentences: [
      { text: "저는 집에 있어요.", translation: "I'm at home." },
      { text: "밥을 먹어요.", translation: "I eat a meal." },
      { text: "커피를 마셔요.", translation: "I drink coffee." },
      { text: "영화도 봐요.", translation: "I watch a movie too." },
      { text: "친구는 학교에 있어요.", translation: "My friend is at school." },
      { text: "친구는 공부해요.", translation: "My friend studies." },
    ],
  },
  {
    // m7 stretch read (m7 caps at L3). Present tense throughout — m7 has no
    // past forms and no time adverbs at all (오늘/어제 are m10), so the arc has
    // to run on sequence rather than on when. 하고 (m9) buys the companionship
    // the last line pays off.
    id: "ko-m7-the-teacher-at-the-door",
    languageId: "ko",
    module: 7,
    level: 3,
    title: "The teacher at the door",
    theme: "A study session that quietly stops being a study session.",
    tags: ["school", "movies", "friends"],
    glosses: [
      { surface: "그런데", meaning: "but, and yet", atomId: "ko:그런데" },
      { surface: "하고", meaning: "with, and", atomId: "ko:하고" },
      { surface: "좋아요", meaning: "is good, is nice", atomId: "ko:좋아요" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "우리는 선생님하고 뭐를 해요?",
        options: ["영화를 봐요", "공부해요", "빵을 먹어요"],
        answer: "영화를 봐요",
      },
    ],
    sentences: [
      { text: "저는 학교에 가요.", translation: "I go to school." },
      { text: "교실에서 공부해요.", translation: "I study in the classroom." },
      { text: "교실에 선생님이 없어요.", translation: "The teacher isn't in the classroom." },
      { text: "그런데 친구가 와요.", translation: "But a friend comes in." },
      { text: "친구 핸드폰에 영화가 있어요.", translation: "My friend has a movie on their phone." },
      { text: "저는 친구하고 영화를 봐요.", translation: "I watch the movie with my friend." },
      { text: "영화가 좋아요.", translation: "The movie is good." },
      { text: "우리는 커피도 마셔요.", translation: "We drink coffee too." },
      { text: "빵도 먹어요.", translation: "We eat bread too." },
      { text: "그런데 문에 선생님이 있어요!", translation: "But the teacher is at the door!" },
      { text: "선생님이 교실에 와요.", translation: "The teacher comes into the classroom." },
      { text: "우리는 책을 봐요.", translation: "We look at our books." },
      { text: "선생님도 핸드폰을 봐요.", translation: "The teacher looks at the phone too." },
      { text: "선생님도 영화를 봐요!", translation: "The teacher watches the movie too!" },
      { text: "우리는 선생님하고 영화를 봐요.", translation: "We watch the movie with the teacher." },
    ],
  },
  {
    // m8 stretch read. m8 is the adjective module, so the arc is a comparison
    // the learner can only follow by holding three bags in mind at once —
    // 커요/작아요/비싸요/싸요/예뻐요 all load-bearing, none decorative.
    id: "ko-m8-the-right-bag",
    languageId: "ko",
    module: 8,
    level: 3,
    title: "The right bag",
    theme: "Too big, too small, too expensive — and then the right one.",
    tags: ["shopping", "school"],
    glosses: [
      { surface: "하고", meaning: "and, with", atomId: "ko:하고" },
      { surface: "그래서", meaning: "so, therefore", atomId: "ko:그래서" },
      { surface: "그리고", meaning: "and, and also", atomId: "ko:그리고" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "좋은 가방은 얼마예요?",
        options: ["사천 원이에요", "구천 원이에요", "오천 원이에요"],
        answer: "사천 원이에요",
      },
    ],
    sentences: [
      { text: "제 가방은 작아요.", translation: "My bag is small." },
      { text: "그런데 제 책하고 핸드폰은 커요.", translation: "But my book and my phone are big." },
      { text: "그래서 저는 가게에 가요.", translation: "So I go to the shop." },
      { text: "가게에 가방이 있어요.", translation: "The shop has bags." },
      { text: "이 가방은 커요.", translation: "This bag is big." },
      { text: "그런데 비싸요.", translation: "But it's expensive." },
      { text: "구천 원이에요.", translation: "It's 9,000 won." },
      { text: "저 가방은 싸요.", translation: "That bag over there is cheap." },
      { text: "그런데 작아요.", translation: "But it's small." },
      { text: "거기에 좋은 가방이 있어요.", translation: "Over there is a good bag." },
      { text: "그 가방은 커요.", translation: "That bag is big." },
      { text: "그리고 예뻐요.", translation: "And it's pretty." },
      { text: "그거 얼마예요?", translation: "How much is that one?" },
      { text: "사천 원이에요.", translation: "It's 4,000 won." },
      { text: "그거 주세요!", translation: "I'll take it!" },
      { text: "제 책하고 핸드폰이 가방에 있어요.", translation: "My book and my phone are in the bag." },
    ],
  },
  // ── Mid (m9-m17): ~1 story per module ──────────────────────────────────────
  {
    id: "ko-m9-a-snack",
    languageId: "ko",
    module: 9,
    level: 2,
    title: "A snack at home",
    theme: "Bread, milk, and an apple.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "뭐가 커요?",
        options: ["사과예요", "빵이에요", "우유예요"],
        answer: "사과예요",
      },
    ],
    sentences: [
      { text: "저는 집에 있어요.", translation: "I'm at home." },
      { text: "빵하고 우유가 있어요.", translation: "There's bread and milk." },
      { text: "사과도 있어요.", translation: "There's an apple too." },
      { text: "빵을 먹어요.", translation: "I eat the bread." },
      { text: "우유를 마셔요.", translation: "I drink the milk." },
      { text: "빵하고 우유가 맛있어요.", translation: "The bread and milk are tasty." },
      { text: "사과는 커요.", translation: "The apple is big." },
    ],
  },
  {
    // m9 stretch read. m9 adds the "and" particles (하고 / 과 / 와) plus 빵,
    // 우유, 사과 — so the story is built on sharing, which is what those
    // particles are for. Still present tense: past lands at m10.
    id: "ko-m9-the-apple-in-the-bag",
    languageId: "ko",
    module: 9,
    level: 3,
    title: "The apple in the bag",
    theme: "One lunch between two people, and then a surprise.",
    tags: ["food", "friends", "school"],
    glosses: [
      { surface: "그래서", meaning: "so, therefore", atomId: "ko:그래서" },
      { surface: "좋아해요", meaning: "like(s)", atomId: "ko:좋아해요" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "친구 가방에 뭐가 있어요?",
        options: ["사과가 있어요", "빵이 있어요", "우유가 있어요"],
        answer: "사과가 있어요",
      },
    ],
    sentences: [
      { text: "저는 학교에 가요.", translation: "I go to school." },
      { text: "제 가방에 빵과 우유가 있어요.", translation: "In my bag there's bread and milk." },
      { text: "교실에서 친구를 봐요.", translation: "In the classroom I see my friend." },
      { text: "그런데 친구 가방에 빵이 없어요.", translation: "But there's no bread in my friend's bag." },
      { text: "우유도 없어요.", translation: "No milk either." },
      { text: "그래서 저는 친구하고 빵을 먹어요.", translation: "So I eat the bread with my friend." },
      { text: "우유도 마셔요.", translation: "We drink the milk too." },
      { text: "그런데 친구 가방에 사과가 있어요!", translation: "But there's an apple in my friend's bag!" },
      { text: "사과는 커요.", translation: "The apple is big." },
      { text: "우리는 사과를 먹어요.", translation: "We eat the apple." },
      { text: "사과가 맛있어요.", translation: "The apple is delicious." },
      { text: "우리 가방에 빵도 우유도 사과도 없어요.", translation: "Now our bags have no bread, no milk, no apple." },
      { text: "그런데 괜찮아요.", translation: "But that's fine." },
      { text: "저는 친구를 좋아해요.", translation: "I like my friend." },
    ],
  },
  {
    id: "ko-m10-yesterday",
    languageId: "ko",
    module: 10,
    level: 2,
    title: "Yesterday",
    theme: "Looking back on a good day.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "어제 뭐가 좋았어요?",
        options: ["영화예요", "커피예요", "우유예요"],
        answer: "영화예요",
      },
    ],
    sentences: [
      { text: "어제 친구하고 커피를 마셨어요.", translation: "Yesterday I had coffee with a friend." },
      { text: "우리는 영화를 봤어요.", translation: "We watched a movie." },
      { text: "영화가 좋았어요.", translation: "The movie was good." },
      { text: "저는 집에서 밥을 먹었어요.", translation: "I ate at home." },
      { text: "친구는 공부했어요.", translation: "My friend studied." },
      { text: "우유도 마셨어요.", translation: "I drank milk too." },
      { text: "오늘도 커피를 마셔요.", translation: "Today I drink coffee too." },
    ],
  },
  {
    // m10 stretch read — the FIRST fully past-tense KO story in the file.
    // m10's past action verbs (갔어요 / 왔어요 / 마셨어요 / 먹었어요 /
    // 맛있었어요) all gate; 있었어요 and 없었어요 never gate at ANY module, so
    // they are bought with two of the four gloss slots. They earn them: the
    // whole arc is a sequence of absences ending in a presence.
    id: "ko-m10-looking-for-a-friend",
    languageId: "ko",
    module: 10,
    level: 3,
    title: "Looking for a friend",
    theme: "Two people spend a whole day missing each other.",
    tags: ["friends", "town"],
    glosses: [
      { surface: "없었어요", meaning: "wasn't there, wasn't in", atomId: "ko:없어요" },
      { surface: "있었어요", meaning: "was there, was in", atomId: "ko:있어요" },
      { surface: "그래서", meaning: "so, therefore", atomId: "ko:그래서" },
      { surface: "그리고", meaning: "and, and then", atomId: "ko:그리고" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "친구는 어디에 있었어요?",
        options: ["식당에 있었어요", "집에 있었어요", "학교에 있었어요"],
        answer: "식당에 있었어요",
      },
    ],
    sentences: [
      { text: "어제 저는 친구 집에 갔어요.", translation: "Yesterday I went to my friend's house." },
      { text: "그런데 친구가 집에 없었어요.", translation: "But my friend wasn't home." },
      { text: "그래서 저는 학교에 갔어요.", translation: "So I went to the school." },
      { text: "학교에도 친구가 없었어요.", translation: "My friend wasn't at school either." },
      { text: "저는 교실에서 커피를 마셨어요.", translation: "I drank a coffee in the classroom." },
      { text: "그리고 가게에 갔어요.", translation: "And then I went to the shop." },
      { text: "가게에도 친구가 없었어요.", translation: "My friend wasn't at the shop either." },
      { text: "저는 식당에 갔어요.", translation: "I went to the restaurant." },
      { text: "식당에 친구가 있었어요!", translation: "My friend was at the restaurant!" },
      { text: "친구는 밥을 먹었어요.", translation: "My friend had had a meal." },
      { text: "저도 밥을 먹었어요.", translation: "I ate too." },
      { text: "밥이 맛있었어요.", translation: "The food was delicious." },
      { text: "친구도 어제 우리 집에 갔어요!", translation: "My friend had gone to my house yesterday too!" },
      { text: "그런데 저는 집에 없었어요.", translation: "But I wasn't home." },
      { text: "우리는 식당에서 커피를 마셨어요.", translation: "We drank coffee at the restaurant." },
      { text: "어제는 좋았어요.", translation: "Yesterday turned out well." },
    ],
  },
  {
    id: "ko-m11-a-day-off",
    languageId: "ko",
    module: 11,
    level: 2,
    title: "A day off",
    theme: "Staying in on a quiet day.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "오늘 저는 어디에 있어요?",
        options: ["집에 있어요", "학교에 있어요", "식당에 있어요"],
        answer: "집에 있어요",
      },
    ],
    sentences: [
      { text: "오늘은 학교에 안 가요.", translation: "Today I don't go to school." },
      { text: "저는 집에 있어요.", translation: "I stay at home." },
      { text: "영화를 보고 싶어요.", translation: "I want to watch a movie." },
      { text: "그런데 커피가 없어요.", translation: "But there's no coffee." },
      { text: "커피를 못 마셔요.", translation: "I can't have my coffee." },
      { text: "빵도 없어요.", translation: "There's no bread either." },
      { text: "그런데 밥도 안 먹어요.", translation: "But I don't eat, either." },
    ],
  },
  {
    // m11 stretch read. m11 adds 안 / 못 / …고 싶어요, which is what makes a
    // frustrated-desire arc writable at all. Note 보고 싶어요 is the ONLY
    // want-form available here: 가고 / 먹고 residual until 고 lands at m14, so
    // the atoms "가고 싶어요" / "먹고 싶어요" are unusable as written text.
    id: "ko-m11-the-restaurant-i-cant-go-to",
    languageId: "ko",
    module: 11,
    level: 3,
    title: "The restaurant I can't go to",
    theme: "An expensive craving, and a cheaper thing that beats it.",
    tags: ["food", "friends", "home"],
    glosses: [
      { surface: "좋아해요", meaning: "like(s)", atomId: "ko:좋아해요" },
      { surface: "그래서", meaning: "so, therefore", atomId: "ko:그래서" },
      { surface: "있었어요", meaning: "was there, was in", atomId: "ko:있어요" },
      { surface: "그리고", meaning: "and, and then", atomId: "ko:그리고" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "저는 어디에서 빵을 먹었어요?",
        options: ["집에서 먹었어요", "식당에서 먹었어요", "학교에서 먹었어요"],
        answer: "집에서 먹었어요",
      },
    ],
    sentences: [
      { text: "저는 그 식당을 좋아해요.", translation: "I love that restaurant." },
      { text: "그 식당은 밥이 맛있어요.", translation: "The food there is delicious." },
      { text: "그런데 그 식당은 비싸요.", translation: "But that restaurant is expensive." },
      { text: "그래서 저는 그 식당에 못 가요.", translation: "So I can't go there." },
      { text: "저는 영화를 보고 싶어요.", translation: "I want to watch a movie." },
      { text: "어제 저는 집에 있었어요.", translation: "Yesterday I was at home." },
      { text: "저는 밥을 안 먹었어요.", translation: "I didn't eat." },
      { text: "그런데 친구가 우리 집에 왔어요.", translation: "But my friend came over." },
      { text: "친구 가방에 빵하고 우유가 있었어요.", translation: "There was bread and milk in my friend's bag." },
      { text: "우리는 집에서 빵을 먹었어요.", translation: "We ate the bread at home." },
      { text: "빵이 맛있었어요.", translation: "The bread was delicious." },
      { text: "그리고 우리는 영화를 봤어요.", translation: "And we watched a movie." },
      { text: "영화가 좋았어요.", translation: "The movie was good." },
      { text: "저는 그 식당에 못 가요.", translation: "I can't go to that restaurant." },
      { text: "그런데 괜찮아요!", translation: "But that's all right!" },
      { text: "우리 집이 좋아요.", translation: "Home is good." },
    ],
  },
  {
    id: "ko-m12-friday-plan",
    languageId: "ko",
    module: 12,
    level: 2,
    title: "A plan for Friday",
    theme: "Setting a time to meet.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "몇 시에 만나요?",
        options: ["세 시에 만나요", "두 시에 만나요", "한 시에 만나요"],
        answer: "세 시에 만나요",
      },
    ],
    sentences: [
      { text: "금요일에 시간이 있어요.", translation: "I have time on Friday." },
      { text: "친구하고 영화를 보고 싶어요.", translation: "I want to watch a movie with a friend." },
      { text: "지금 몇 시예요?", translation: "What time is it now?" },
      { text: "두 시예요.", translation: "It's 2 o'clock." },
      { text: "세 시에 만나요.", translation: "Let's meet at 3:00." },
      { text: "우리는 영화를 봐요.", translation: "We watch a movie." },
      { text: "우리는 밥도 먹어요.", translation: "We eat a meal too." },
    ],
  },
  {
    // L3 EXEMPLAR for docs/story-authoring-guide.md. m12 caps at L3, so this is
    // the stretch read that sits above ko-m12-friday-plan's L2. Polite 해요
    // register throughout, matching the course's spine.
    //
    // Present-tense narration is a POOL CONSTRAINT, not a style pick: the past
    // action verbs gate cleanly (갔어요 / 왔어요 / 봤어요 / 마셨어요), but
    // 있었어요 / 없었어요 / 싶었어요 residual whole at m12, m13, m20 AND m27 —
    // they are not writable at any module in the course — and this arc turns on
    // exactly those "was at home" / "wanted to watch" beats.
    //
    // Present tense is the weaker Korean. Where an arc CAN be told with the past
    // action verbs, prefer the past; don't copy this pattern by default.
    id: "ko-m12-waiting-for-a-friend",
    languageId: "ko",
    module: 12,
    level: 3,
    title: "Waiting for a friend",
    theme: "A plan to see a movie falls apart, then comes back together.",
    tags: ["friends", "food", "daily-life"],
    glosses: [
      { surface: "기다려요", meaning: "wait(s)", atomId: "ko:기다리다" },
      { surface: "전화", meaning: "phone, phone call", atomId: "ko:전화" },
      { surface: "아파요", meaning: "hurts, is unwell", atomId: "ko:아파요" },
      { surface: "그래서", meaning: "so, therefore", atomId: "ko:그래서" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "우리는 어디에서 영화를 봐요?",
        options: ["친구 집에서 봐요", "식당에서 봐요", "학교에서 봐요"],
        answer: "친구 집에서 봐요",
      },
      {
        id: "time",
        kind: "detail",
        prompt: "우리는 몇 시에 만나요?",
        options: ["세 시에 만나요", "두 시에 만나요", "한 시에 만나요"],
        answer: "세 시에 만나요",
      },
    ],
    sentences: [
      { text: "오늘은 학교에 안 가요.", translation: "Today I don't go to school." },
      { text: "저는 친구하고 영화를 보고 싶어요.", translation: "I want to watch a movie with my friend." },
      { text: "우리는 세 시에 만나요.", translation: "We're meeting at three." },
      { text: "지금 두 시예요.", translation: "It's two o'clock now." },
      { text: "저는 식당에 가요.", translation: "I go to the restaurant." },
      { text: "식당에서 커피를 마셔요.", translation: "I drink coffee at the restaurant." },
      { text: "저는 식당에서 친구를 기다려요.", translation: "I wait for my friend at the restaurant." },
      { text: "그런데 친구가 안 와요.", translation: "But my friend doesn't come." },
      { text: "저는 한 시간 기다려요.", translation: "I wait for an hour." },
      { text: "지금도 친구가 안 와요.", translation: "Even now my friend doesn't come." },
      { text: "저는 전화해요.", translation: "I call." },
      { text: "친구는 집에 있어요.", translation: "My friend is at home." },
      { text: "친구는 머리가 아파요.", translation: "My friend has a headache." },
      { text: "그래서 저는 친구 집에 가요.", translation: "So I go to my friend's house." },
      { text: "우리는 집에서 영화를 봐요.", translation: "We watch the movie at the house." },
    ],
  },
  {
    id: "ko-m13-my-week",
    languageId: "ko",
    module: 13,
    level: 2,
    title: "My week",
    theme: "Work, study, and a bit of exercise.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "토요일에는 뭐 해요?",
        options: ["집에 있어요", "회사에 가요", "학교에 가요"],
        answer: "집에 있어요",
      },
    ],
    sentences: [
      { text: "저는 자주 운동해요.", translation: "I exercise often." },
      { text: "월요일부터 금요일까지 회사에 가요.", translation: "I go to work from Monday to Friday." },
      { text: "회사에서 공부해요.", translation: "I study at work." },
      { text: "저는 커피를 좋아해요.", translation: "I like coffee." },
      { text: "그리고 운동도 좋아해요.", translation: "And I like exercise too." },
      { text: "가끔 영화를 봐요.", translation: "Sometimes I watch a movie." },
      { text: "토요일에는 항상 집에 있어요.", translation: "On Saturdays I always stay home." },
    ],
  },
  {
    // m13 stretch read — first KO L4 (17-24 sentences). m13 hands over the
    // frequency adverbs (항상 / 자주 / 가끔 / 별로 / 전혀), 부터…까지, month
    // names and both 그래서 / 그리고, which is exactly enough to write a habit
    // that CHANGES rather than a habit that is merely listed.
    id: "ko-m13-from-june-to-october",
    languageId: "ko",
    module: 13,
    level: 4,
    title: "From June to October",
    theme: "Someone drags me out to exercise. Months later the roles swap.",
    tags: ["exercise", "work", "friends"],
    glosses: [
      { surface: "같이", meaning: "together" },
      { surface: "아팠어요", meaning: "hurt, was sore", atomId: "ko:아파요" },
      { surface: "혼자", meaning: "alone, by myself" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "지금 친구는 어디에 있어요?",
        options: ["회사에 있어요", "집에 있어요", "학교에 있어요"],
        answer: "회사에 있어요",
      },
    ],
    sentences: [
      { text: "저는 아홉 시부터 여섯 시까지 회사에 있어요.", translation: "I'm at the office from nine until six." },
      { text: "저는 회사에서 커피를 자주 마셔요.", translation: "I drink coffee at the office a lot." },
      { text: "그런데 저는 운동을 전혀 안 해요.", translation: "But I never exercise at all." },
      { text: "제 친구는 항상 운동해요.", translation: "My friend always exercises." },
      { text: "유월에 친구가 우리 집에 왔어요.", translation: "In June my friend came to my house." },
      { text: "민수, 같이 운동해요!", translation: "\"Minsu, let's exercise together!\"" },
      { text: "저는 운동을 별로 안 좋아해요.", translation: "I don't much like exercise." },
      { text: "그런데 저는 친구하고 운동했어요.", translation: "But I exercised with my friend anyway." },
      { text: "운동이 별로 안 좋았어요.", translation: "I didn't enjoy it much." },
      { text: "제 다리가 아팠어요.", translation: "My legs hurt." },
      { text: "그래서 저는 운동을 안 했어요.", translation: "So I didn't exercise." },
      { text: "그런데 친구가 토요일에 항상 우리 집에 왔어요.", translation: "But my friend came to my house every Saturday." },
      { text: "그리고 우리는 같이 운동했어요.", translation: "And we exercised together." },
      { text: "칠월에도 친구가 왔어요.", translation: "In July my friend came too." },
      { text: "팔월에도 왔어요.", translation: "In August too." },
      { text: "시월부터 저는 운동을 좋아해요.", translation: "From October on, I like exercise." },
      { text: "지금 저는 자주 운동해요.", translation: "Now I exercise often." },
      { text: "그런데 지금 친구는 운동을 안 해요.", translation: "But now my friend doesn't exercise." },
      { text: "친구는 항상 회사에 있어요.", translation: "My friend is always at the office." },
      { text: "그래서 저는 토요일에 혼자 운동해요.", translation: "So on Saturdays I exercise alone." },
      { text: "지금 저는 친구 회사에 가요.", translation: "Now I'm on my way to my friend's office." },
      { text: "친구, 같이 운동해요!", translation: "\"Come on — let's exercise together!\"" },
    ],
  },
  {
    id: "ko-m14-a-busy-day",
    languageId: "ko",
    module: 14,
    level: 2,
    title: "A busy day",
    theme: "Too much to do, too little time.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "저는 뭐를 못 마셔요?",
        options: ["커피를 못 마셔요", "물을 못 마셔요", "우유를 못 마셔요"],
        answer: "커피를 못 마셔요",
      },
    ],
    sentences: [
      { text: "저는 바빠서 시간이 없어요.", translation: "I'm busy, so I have no time." },
      { text: "오늘 회사에 가요.", translation: "I go to work today." },
      { text: "회사에서 공부하고 밥을 먹어요.", translation: "At work I study and eat." },
      { text: "친구가 와요.", translation: "A friend comes over." },
      { text: "친구는 커피를 마셔요.", translation: "My friend drinks coffee." },
      { text: "저는 바빠서 커피를 못 마셔요.", translation: "But I'm too busy for coffee." },
      { text: "기다려 주세요.", translation: "Please wait." },
    ],
  },
  {
    // m14 stretch read. m14 lands 고 (clause join), 바빠서, the 백/천/만
    // number scale and 기다리다 — so this is the first KO story that can both
    // wait and explain why someone else couldn't come. 기다렸어요 never gates
    // at any module and is bought with a gloss; 마시고 / 먹고 are NOT available
    // yet (마시고 is m15, 먹고 never), so the meal is two short sentences.
    id: "ko-m14-the-child-at-the-station",
    languageId: "ko",
    module: 14,
    level: 4,
    title: "The child at the station",
    theme: "A small stranger asks for help, and the wait gets long.",
    tags: ["town", "family", "help"],
    glosses: [
      { surface: "기다렸어요", meaning: "waited", atomId: "ko:기다리다" },
      { surface: "있었어요", meaning: "was there, was in", atomId: "ko:있어요" },
      { surface: "같이", meaning: "together" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "미나 어머니는 어디에 있었어요?",
        options: ["병원에 있었어요", "역에 있었어요", "가게에 있었어요"],
        answer: "병원에 있었어요",
      },
    ],
    sentences: [
      { text: "어제 저는 역에 갔어요.", translation: "Yesterday I went to the station." },
      { text: "역에서 작은 아이를 봤어요.", translation: "At the station I saw a small child." },
      { text: "아이가 저를 봤어요.", translation: "The child looked at me." },
      { text: "어머니가 없어요. 도와주세요.", translation: "\"My mother isn't here. Please help me.\"" },
      { text: "아이 이름은 미나예요.", translation: "The child's name is Mina." },
      { text: "미나는 학생이에요.", translation: "Mina is a schoolchild." },
      { text: "저는 미나하고 어머니를 기다렸어요.", translation: "I waited with Mina for her mother." },
      { text: "그런데 어머니가 안 왔어요.", translation: "But her mother didn't come." },
      { text: "우리는 한 시간 기다렸어요.", translation: "We waited for an hour." },
      { text: "미나는 밥을 안 먹었어요.", translation: "Mina hadn't eaten." },
      { text: "그래서 우리는 가게에 갔어요.", translation: "So we went to the shop." },
      { text: "빵 두 개하고 우유를 주세요.", translation: "\"Two pieces of bread and a milk, please.\"" },
      { text: "이천 원이에요.", translation: "\"That's 2,000 won.\"" },
      { text: "우리는 빵을 먹었어요.", translation: "We ate the bread." },
      { text: "그리고 우유를 마셨어요.", translation: "And we drank the milk." },
      { text: "우리 어머니는 병원에 있어요.", translation: "\"My mother is at the hospital.\"" },
      { text: "그래서 우리는 같이 병원에 갔어요.", translation: "So we went to the hospital together." },
      { text: "병원에 미나 어머니가 있었어요!", translation: "Mina's mother was at the hospital!" },
      { text: "어머니는 바빠서 역에 못 왔어요.", translation: "She was busy, so she couldn't come to the station." },
      { text: "고마워요! 감사합니다!", translation: "\"Thank you! Thank you so much!\"" },
      { text: "미나는 어머니하고 집에 가고 저는 역에 갔어요.", translation: "Mina went home with her mother, and I went back to the station." },
      { text: "어제는 좋았어요.", translation: "Yesterday was a good day." },
    ],
  },
  {
    id: "ko-m15-relaxing-at-home",
    languageId: "ko",
    module: 15,
    level: 2,
    title: "Relaxing at home",
    theme: "A quiet afternoon with a friend.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "오늘 저는 어디에 있어요?",
        options: ["집에 있어요", "학교에 있어요", "회사에 있어요"],
        answer: "집에 있어요",
      },
    ],
    sentences: [
      { text: "오늘은 집에 있어요.", translation: "Today I'm at home." },
      { text: "커피를 마시고 있어요.", translation: "I'm drinking coffee." },
      { text: "영화를 보고 있어요.", translation: "I'm watching a movie." },
      { text: "친구가 전화해요.", translation: "A friend calls." },
      { text: "친구도 집에 와요.", translation: "My friend comes over too." },
      { text: "여기 앉아도 돼요.", translation: "You can sit here." },
      { text: "우리는 커피를 마시고 영화를 봐요.", translation: "We drink coffee and watch a movie." },
    ],
  },
  {
    // m15 stretch read. m15 gives …고 있어요, 이지만 and 전화, so the phone can
    // finally ring and a sentence can finally concede something. Narration is
    // past; the progressive appears where it belongs — inside the phone call,
    // where present tense is what a speaker would actually use.
    id: "ko-m15-the-saturday-call",
    languageId: "ko",
    module: 15,
    level: 4,
    title: "The Saturday call",
    theme: "A day off, one phone call, and an office with nobody in it.",
    tags: ["work", "phone", "home"],
    glosses: [
      { surface: "사람", meaning: "person, people" },
      { surface: "없었어요", meaning: "wasn't there, wasn't in", atomId: "ko:없어요" },
      { surface: "기다렸어요", meaning: "waited", atomId: "ko:기다리다" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "저는 회사에 언제 가요?",
        options: ["일요일에 가요", "토요일에 가요", "금요일에 가요"],
        answer: "일요일에 가요",
      },
    ],
    sentences: [
      { text: "오늘은 토요일이에요.", translation: "Today is Saturday." },
      { text: "저는 회사에 안 가요.", translation: "I don't go to the office on Saturdays." },
      { text: "저는 집에서 영화를 봤어요.", translation: "I watched a movie at home." },
      { text: "커피도 마셨어요.", translation: "I drank coffee too." },
      { text: "그런데 회사에서 전화했어요.", translation: "But the office called." },
      { text: "지금 뭐 해요?", translation: "\"What are you doing right now?\"" },
      { text: "저는 집에서 영화를 보고 있어요.", translation: "\"I'm at home watching a movie.\"" },
      { text: "오늘 회사에 와요.", translation: "\"Come in to the office today.\"" },
      { text: "오늘은 토요일이지만 저는 회사에 갔어요.", translation: "It was Saturday, but I went in." },
      { text: "그런데 회사에 사람이 없었어요.", translation: "But there was nobody at the office." },
      { text: "저는 한 시간 기다렸어요.", translation: "I waited for an hour." },
      { text: "그런데 사람이 안 왔어요.", translation: "But nobody came." },
      { text: "그래서 저는 회사에 전화했어요.", translation: "So I called the office." },
      { text: "일요일에 회사에 와요.", translation: "\"Come in to the office on Sunday.\"" },
      { text: "오늘은 토요일이에요!", translation: "But today is Saturday!" },
      { text: "저는 집에 갔어요.", translation: "I went home." },
      { text: "집에서 커피를 마시고 영화를 봤어요.", translation: "At home I drank coffee and watched my movie." },
      { text: "지금 저는 자고 싶어요.", translation: "Right now I just want to sleep." },
      { text: "일요일에 저는 회사에 가요.", translation: "On Sunday I go in to the office." },
      { text: "그런데 일요일에도 회사에 사람이 없어요?", translation: "But on Sunday — will anyone be at the office?" },
    ],
  },
  {
    id: "ko-m16-friends-house",
    languageId: "ko",
    module: 16,
    level: 2,
    title: "At a friend's house",
    theme: "Visiting a friend's place.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "저는 뭐를 좋아해요?",
        options: ["커피를 좋아해요", "담배를 좋아해요", "영화를 좋아해요"],
        answer: "커피를 좋아해요",
      },
    ],
    sentences: [
      { text: "오늘 친구 집에 가요.", translation: "Today I go to my friend's house." },
      { text: "친구 집에서는 담배를 피우면 안 돼요.", translation: "You can't smoke at my friend's house." },
      { text: "저는 담배를 싫어해요.", translation: "I don't like cigarettes." },
      { text: "네, 알겠어요.", translation: "OK, got it." },
      { text: "친구는 커피를 좋아해요.", translation: "My friend likes coffee." },
      { text: "저도 커피를 좋아해요.", translation: "I like coffee too." },
      { text: "우리는 커피를 마시고 영화를 봐요.", translation: "We drink coffee and watch a movie." },
    ],
  },
  {
    id: "ko-m17-my-commute",
    languageId: "ko",
    module: 17,
    level: 2,
    title: "My commute",
    theme: "Bus, subway, and a left turn.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "회사는 어디에 있어요?",
        options: ["왼쪽에 있어요", "오른쪽에 있어요", "역에 있어요"],
        answer: "왼쪽에 있어요",
      },
    ],
    sentences: [
      { text: "저는 회사에 가요.", translation: "I go to work." },
      { text: "버스를 타요.", translation: "I take the bus." },
      { text: "다음 역에서 내려요.", translation: "I get off at the next stop." },
      { text: "그리고 지하철을 타요.", translation: "And then I take the subway." },
      { text: "회사까지 똑바로 가요.", translation: "I go straight to the office." },
      { text: "회사는 왼쪽에 있어요.", translation: "The office is on the left." },
      { text: "저는 회사에서 공부해요.", translation: "I study at work." },
    ],
  },
  // ── Late (m18-m27): ramp up — 1, sometimes 2 stories per module ────────────
  {
    id: "ko-m18-tomorrows-weather",
    languageId: "ko",
    module: 18,
    level: 2,
    title: "Tomorrow's weather",
    theme: "A clear day, then rain.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "내일은 뭐가 올 거예요?",
        options: ["비가 올 거예요", "눈이 올 거예요", "바람이 올 거예요"],
        answer: "비가 올 거예요",
      },
    ],
    sentences: [
      { text: "오늘은 날씨가 좋아요.", translation: "The weather is nice today." },
      { text: "맑아요.", translation: "It's clear." },
      { text: "그런데 내일은 비가 올 거예요.", translation: "But tomorrow it will rain." },
      { text: "내일은 추워요.", translation: "Tomorrow it's cold." },
      { text: "저는 겨울을 좋아해요.", translation: "I like winter." },
      { text: "겨울에는 눈이 와요.", translation: "In winter it snows." },
      { text: "여름에는 더워요.", translation: "In summer it's hot." },
    ],
  },
  {
    id: "ko-m19-my-family",
    languageId: "ko",
    module: 19,
    level: 2,
    title: "My family",
    theme: "Four of us, and an older brother.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "우리 가족은 몇 명이에요?",
        options: ["네 명이에요", "세 명이에요", "두 명이에요"],
        answer: "네 명이에요",
      },
    ],
    sentences: [
      { text: "우리 가족은 네 명이에요.", translation: "There are four people in my family." },
      { text: "엄마, 아빠, 형, 그리고 저요.", translation: "Mom, dad, my older brother, and me." },
      { text: "형은 스무 살이에요.", translation: "My brother is twenty." },
      { text: "저는 학생이에요.", translation: "I'm a student." },
      { text: "형은 회사에 가요.", translation: "My brother goes to work." },
      { text: "우리 가족은 커피를 좋아해요.", translation: "My family likes coffee." },
      { text: "저는 우리 가족을 좋아해요.", translation: "I love my family." },
    ],
  },
  {
    id: "ko-m20-a-cold",
    languageId: "ko",
    module: 20,
    level: 2,
    title: "A cold",
    theme: "Aches, a fever, and some medicine.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "어디가 아파요?",
        options: ["머리가 아파요", "다리가 아파요", "팔이 아파요"],
        answer: "머리가 아파요",
      },
    ],
    sentences: [
      { text: "오늘은 머리가 아파요.", translation: "My head hurts today." },
      { text: "그리고 배도 아파요.", translation: "And my stomach hurts too." },
      { text: "감기예요.", translation: "It's a cold." },
      { text: "저는 병원에 가요.", translation: "I go to the hospital." },
      { text: "약을 먹어요.", translation: "I take medicine." },
      { text: "약을 먹으면 괜찮을 거예요.", translation: "If I take medicine, I'll be fine." },
      { text: "그리고 집에 있어요.", translation: "And I stay home." },
    ],
  },
  {
    id: "ko-m21-a-korean-meal",
    languageId: "ko",
    module: 21,
    level: 2,
    title: "A Korean meal",
    theme: "Bibimbap, bulgogi, and kimchi.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "친구는 뭐를 먹어요?",
        options: ["생선을 먹어요", "비빔밥을 먹어요", "라면을 먹어요"],
        answer: "생선을 먹어요",
      },
    ],
    sentences: [
      { text: "저는 식당에 가요.", translation: "I go to a restaurant." },
      { text: "비빔밥하고 불고기를 먹어요.", translation: "I eat bibimbap and bulgogi." },
      { text: "김치도 맛있어요.", translation: "The kimchi is tasty too." },
      { text: "라면도 좋아해요.", translation: "I like ramen too." },
      { text: "친구는 생선하고 채소를 먹어요.", translation: "My friend eats fish and vegetables." },
      { text: "과일도 먹어요.", translation: "We eat fruit too." },
      { text: "커피 한 잔 주세요.", translation: "One coffee, please." },
    ],
  },
  {
    id: "ko-m21-cooking-dinner",
    languageId: "ko",
    module: 21,
    level: 2,
    title: "Cooking dinner",
    theme: "A meal at home with a friend.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "친구는 뭐를 마셔요?",
        options: ["우유를 마셔요", "커피를 마셔요", "물을 마셔요"],
        answer: "우유를 마셔요",
      },
    ],
    sentences: [
      { text: "오늘은 집에서 밥을 먹어요.", translation: "Today I eat at home." },
      { text: "저는 불고기를 좋아해요.", translation: "I like bulgogi." },
      { text: "그래서 불고기하고 밥을 먹어요.", translation: "So I have bulgogi and rice." },
      { text: "김치도 있어요.", translation: "There's kimchi too." },
      { text: "친구도 집에 와요.", translation: "My friend comes over too." },
      { text: "우리는 라면하고 과일도 먹어요.", translation: "We eat ramen and fruit too." },
      { text: "저는 커피를 마시고 친구는 우유를 마셔요.", translation: "I drink coffee and my friend drinks milk." },
    ],
  },
  {
    id: "ko-m22-which-i-like-more",
    languageId: "ko",
    module: 22,
    level: 2,
    title: "Which I like more",
    theme: "Comparing coffee and tea.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "뭐가 제일 좋아요?",
        options: ["커피예요", "차예요", "우유예요"],
        answer: "커피예요",
      },
    ],
    sentences: [
      { text: "저는 커피하고 차 중에서 커피가 더 좋아요.", translation: "Between coffee and tea, I like coffee more." },
      { text: "차는 커피보다 싸요.", translation: "Tea is cheaper than coffee." },
      { text: "그래도 커피가 제일 맛있어요.", translation: "Still, coffee is the tastiest." },
      { text: "친구는 차를 더 좋아해요.", translation: "My friend likes tea more." },
      { text: "뭐가 제일 좋아요?", translation: "What do you like best?" },
      { text: "커피가 가장 좋아요.", translation: "I like coffee best." },
      { text: "저는 커피를 자주 마셔요.", translation: "I drink coffee often." },
    ],
  },
  {
    id: "ko-m22-bibimbap-or-ramen",
    languageId: "ko",
    module: 22,
    level: 2,
    title: "Bibimbap or ramen?",
    theme: "Picking a favorite at the restaurant.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "이 식당은 뭐가 가장 맛있어요?",
        options: ["불고기예요", "비빔밥이에요", "라면이에요"],
        answer: "불고기예요",
      },
    ],
    sentences: [
      { text: "저는 비빔밥하고 라면 중에서 비빔밥이 더 좋아요.", translation: "Between bibimbap and ramen, I like bibimbap more." },
      { text: "라면은 비빔밥보다 싸요.", translation: "Ramen is cheaper than bibimbap." },
      { text: "그래도 비빔밥이 제일 맛있어요.", translation: "Still, bibimbap is the tastiest." },
      { text: "친구는 라면을 더 좋아해요.", translation: "My friend likes ramen more." },
      { text: "우리는 식당에서 밥을 먹어요.", translation: "We eat at a restaurant." },
      { text: "이 식당은 불고기가 가장 맛있어요.", translation: "This restaurant's bulgogi is the tastiest." },
      { text: "그래서 저는 이 식당을 좋아해요.", translation: "So I like this place." },
    ],
  },
  {
    id: "ko-m23-weekend-plans",
    languageId: "ko",
    module: 23,
    level: 2,
    title: "Weekend plans",
    theme: "Cooking and doing things together.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "저는 뭐를 못해요?",
        options: ["노래를 못해요", "요리를 못해요", "수영을 못해요"],
        answer: "노래를 못해요",
      },
    ],
    sentences: [
      { text: "주말에 뭐 할까요?", translation: "What shall we do on the weekend?" },
      { text: "저는 요리를 잘해요.", translation: "I'm good at cooking." },
      { text: "같이 요리할까요?", translation: "Shall we cook together?" },
      { text: "저는 수영도 잘해요.", translation: "I'm good at swimming too." },
      { text: "그런데 노래는 못해요.", translation: "But I can't sing." },
      { text: "주말에 같이 운동합시다.", translation: "Let's exercise together on the weekend." },
      { text: "그리고 같이 밥도 먹어요.", translation: "And let's eat together too." },
    ],
  },
  {
    id: "ko-m24-my-hobbies",
    languageId: "ko",
    module: 24,
    level: 2,
    title: "My hobbies",
    theme: "Music, photos, and a bit of singing.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "제 취미는 뭐예요?",
        options: ["음악이에요", "게임이에요", "요리예요"],
        answer: "음악이에요",
      },
    ],
    sentences: [
      { text: "제 취미는 음악이에요.", translation: "My hobby is music." },
      { text: "저는 음악을 자주 들어요.", translation: "I listen to music often." },
      { text: "사진도 좋아해요.", translation: "I like photography too." },
      { text: "노래도 할 줄 알아요.", translation: "I also know how to sing." },
      { text: "일주일에 두 번 게임을 해요.", translation: "I play games twice a week." },
      { text: "저는 그림도 좋아해요.", translation: "I like drawing too." },
      { text: "주말에 같이 할까요?", translation: "Shall we do it together on the weekend?" },
    ],
  },
  {
    id: "ko-m24-music-and-games",
    languageId: "ko",
    module: 24,
    level: 2,
    title: "Music and games",
    theme: "Sharing hobbies with a friend.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "친구는 뭐를 좋아해요?",
        options: ["게임을 좋아해요", "노래를 좋아해요", "사진을 좋아해요"],
        answer: "게임을 좋아해요",
      },
    ],
    sentences: [
      { text: "저는 음악을 좋아해요.", translation: "I like music." },
      { text: "저는 노래도 할 줄 알아요.", translation: "I also know how to sing." },
      { text: "일주일에 세 번 노래해요.", translation: "I sing three times a week." },
      { text: "친구는 게임을 좋아해요.", translation: "My friend likes games." },
      { text: "우리는 같이 게임을 해요.", translation: "We play games together." },
      { text: "저는 사진도 좋아해요.", translation: "I like photos too." },
      { text: "취미가 뭐예요?", translation: "What's your hobby?" },
    ],
  },
  {
    id: "ko-m25-planning-a-trip",
    languageId: "ko",
    module: 25,
    level: 2,
    title: "Planning a trip",
    theme: "A trip to Japan and a hot spring.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "어디에 가려고 해요?",
        options: ["일본에 가려고 해요", "한국에 가려고 해요", "학교에 가려고 해요"],
        answer: "일본에 가려고 해요",
      },
    ],
    sentences: [
      { text: "저는 여행 계획이 있어요.", translation: "I have travel plans." },
      { text: "저는 일본에 가려고 해요.", translation: "I intend to go to Japan." },
      { text: "일본에 간 적이 있어요.", translation: "I've been to Japan before." },
      { text: "온천에 가고 싶어요.", translation: "I want to go to a hot spring." },
      { text: "축제도 보고 싶어요.", translation: "I want to see a festival too." },
      { text: "다음 주말에 출발해요.", translation: "I leave next weekend." },
      { text: "저는 여행을 좋아해요.", translation: "I like traveling." },
    ],
  },
  {
    id: "ko-m25-trip-with-a-friend",
    languageId: "ko",
    module: 25,
    level: 2,
    title: "A trip with a friend",
    theme: "Two friends heading to Japan.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "저는 뭐를 하고 싶어요?",
        options: ["온천에 가고 싶어요", "축제를 보고 싶어요", "집에 가고 싶어요"],
        answer: "온천에 가고 싶어요",
      },
    ],
    sentences: [
      { text: "친구하고 여행 계획이 있어요.", translation: "My friend and I have travel plans." },
      { text: "우리는 일본에 가려고 해요.", translation: "We intend to go to Japan." },
      { text: "친구는 일본에 간 적이 있어요.", translation: "My friend has been to Japan before." },
      { text: "저는 온천에 가고 싶어요.", translation: "I want to go to a hot spring." },
      { text: "친구는 축제를 보고 싶어요.", translation: "My friend wants to see a festival." },
      { text: "우리는 다음 주말에 출발해요.", translation: "We leave next weekend." },
      { text: "일본에서 비빔밥을 먹어요.", translation: "We'll eat bibimbap in Japan." },
    ],
  },
  {
    id: "ko-m26-a-rough-morning",
    languageId: "ko",
    module: 26,
    level: 2,
    title: "A rough morning",
    theme: "Late, tired, and a traffic jam.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "왜 회사에 늦었어요?",
        options: ["길이 막혔거든요", "피곤해요", "실수했어요"],
        answer: "길이 막혔거든요",
      },
    ],
    sentences: [
      { text: "오늘 회사에 늦었어요.", translation: "I was late for work today." },
      { text: "길이 너무 막혔거든요.", translation: "The road was really jammed, you see." },
      { text: "죄송해요.", translation: "I'm sorry." },
      { text: "저는 너무 피곤해요.", translation: "I'm so tired." },
      { text: "그리고 실수도 했어요.", translation: "And I made a mistake too." },
      { text: "저는 피곤해서 집에 가고 싶어요.", translation: "I'm tired, so I want to go home." },
      { text: "하지만 내일은 회사에 가요.", translation: "But tomorrow I go to work." },
    ],
  },
  {
    id: "ko-m27-before-the-exam",
    languageId: "ko",
    module: 27,
    level: 2,
    title: "Before the exam",
    theme: "Getting ready, and taking care.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "쉬면 어떻게 돼요?",
        options: ["건강해져요", "피곤해요", "괜찮을 거예요"],
        answer: "건강해져요",
      },
    ],
    sentences: [
      { text: "내일은 시험이 있어요.", translation: "I have an exam tomorrow." },
      { text: "저는 시험 준비를 해요.", translation: "I'm getting ready for the exam." },
      { text: "오늘은 연습해요.", translation: "Today I practice." },
      { text: "저는 너무 피곤해요.", translation: "I'm so tired." },
      { text: "쉬면 건강해져요.", translation: "If I rest, I'll get healthy." },
      { text: "그래서 저는 약속을 안 해요.", translation: "So I don't make plans." },
      { text: "조심하세요.", translation: "Take care." },
    ],
  },
];
