/** Culture stories — festivals, customs, and everyday cultural context. */
import type { Story } from "../types";

export const KO_CULTURE_STORIES: Story[] = [
  {
    // m15 is the earliest module with 전화, and a delivery story is a phone story.
    // The speed of the delivery is told with clock arithmetic (seven, then seven
    // twenty) because 빨리 / 많이 / 아주 are not atoms at any module. Past events,
    // present states — the mix the m22 exemplar uses; 있었어요 is never writable.
    id: "ko-m15-the-rainy-saturday",
    languageId: "ko",
    module: 15,
    level: 3,
    title: "The rainy Saturday",
    theme: "Rain, an empty kitchen, and a phone call that fixes both.",
    tags: ["culture", "food", "home"],
    glosses: [
      { surface: "배달", meaning: "delivery — food brought to your door" },
      { surface: "치킨", meaning: "Korean fried chicken" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "우리는 어디에서 영화를 봤어요?",
        options: ["집에서 봤어요", "식당에서 봤어요", "가게에서 봤어요"],
        answer: "집에서 봤어요",
      },
      {
        id: "time",
        kind: "detail",
        prompt: "치킨이 몇 시에 왔어요?",
        options: ["일곱 시 이십 분에 왔어요", "일곱 시에 왔어요", "여덟 시에 왔어요"],
        answer: "일곱 시 이십 분에 왔어요",
      },
    ],
    sentences: [
      { text: "저는 비를 안 좋아해요.", translation: "I do not like rain." },
      { text: "토요일에 비가 왔어요.", translation: "On Saturday it rained." },
      { text: "집에 밥이 없어요.", translation: "There is no food at home." },
      { text: "친구가 우리 집에 왔어요.", translation: "A friend came to our house." },
      { text: "우리는 식당에 가고 싶어요.", translation: "We want to go to a restaurant." },
      { text: "그런데 비가 와요.", translation: "But it is raining." },
      { text: "그래서 우리는 식당에 안 갔어요.", translation: "So we did not go to a restaurant." },
      { text: "한국에는 배달이 있어요.", translation: "In Korea there is delivery." },
      { text: "저는 일곱 시에 가게에 전화했어요.", translation: "I phoned the shop at seven." },
      { text: "일곱 시 이십 분에 치킨이 왔어요.", translation: "At seven twenty the chicken came." },
      { text: "치킨은 이만 원이에요.", translation: "The chicken is twenty thousand won." },
      { text: "우리는 치킨하고 빵을 먹었어요. 그리고 커피를 마셨어요.", translation: "We ate chicken and bread. And we drank coffee." },
      { text: "치킨이 맛있었어요.", translation: "The chicken was delicious." },
      { text: "우리는 집에서 영화를 봤어요.", translation: "We watched a movie at home." },
      { text: "한국의 배달은 이십 분이에요.", translation: "Korea's delivery is twenty minutes." },
      { text: "지금 저는 비가 좋아요.", translation: "Now I like rain." },
    ],
  },
  {
    // m18 is the earliest module with 춥다 / 덥다 / 눈 / 겨울, and the jjimjilbang
    // arc is entirely the cold-outside / hot-inside contrast. The overnight stay
    // is told with clock times (twelve, then seven on Sunday) because 밤 / 아침 are
    // not atoms and 있었어요 does not gate.
    id: "ko-m18-the-hot-room",
    languageId: "ko",
    module: 18,
    level: 4,
    title: "The hot room",
    theme: "A winter I hated, and the place my friend took me instead.",
    tags: ["culture", "winter", "friends"],
    glosses: [
      { surface: "찜질방", meaning: "jjimjilbang — a Korean bathhouse with hot rooms, open all night" },
      { surface: "계란", meaning: "boiled egg — what people eat at a jjimjilbang" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "우리는 언제까지 찜질방에 있어요?",
        options: ["일요일 일곱 시까지 있어요", "토요일 열두 시까지 있어요", "토요일 일곱 시까지 있어요"],
        answer: "일요일 일곱 시까지 있어요",
      },
      {
        id: "food",
        kind: "detail",
        prompt: "친구는 찜질방에서 뭐 먹었어요?",
        options: ["계란을 먹었어요", "빵을 먹었어요", "사과를 먹었어요"],
        answer: "계란을 먹었어요",
      },
    ],
    sentences: [
      { text: "겨울이에요.", translation: "It is winter." },
      { text: "날씨가 추워요.", translation: "The weather is cold." },
      { text: "눈이 와요.", translation: "It is snowing." },
      { text: "저는 겨울을 싫어해요.", translation: "I hate winter." },
      { text: "토요일에 친구가 우리 집에 왔어요.", translation: "On Saturday a friend came to our house." },
      { text: "우리는 찜질방에 갔어요.", translation: "We went to a jjimjilbang." },
      { text: "찜질방은 우리 집에서 지하철로 십 분이에요.", translation: "The jjimjilbang is ten minutes from our house by subway." },
      { text: "찜질방은 커요.", translation: "The jjimjilbang is big." },
      { text: "찜질방이 더워요.", translation: "The jjimjilbang is hot." },
      { text: "저는 물을 마셨어요.", translation: "I drank water." },
      { text: "친구는 계란을 먹었어요.", translation: "My friend ate an egg." },
      { text: "찜질방에는 계란하고 우유하고 물이 있어요.", translation: "A jjimjilbang has eggs, milk and water." },
      { text: "계란이 맛있었어요.", translation: "The egg was delicious." },
      { text: "우리는 찜질방에서 영화를 봤어요.", translation: "We watched a movie at the jjimjilbang." },
      { text: "열두 시였어요.", translation: "It was twelve o'clock." },
      { text: "그런데 우리는 집에 안 갔어요.", translation: "But we did not go home." },
      { text: "우리는 일요일 일곱 시까지 찜질방에 있어요.", translation: "We stay at the jjimjilbang until seven on Sunday." },
      { text: "찜질방이 좋았어요.", translation: "The jjimjilbang was good." },
      { text: "눈이 와요. 그런데 저는 안 추워요.", translation: "It is snowing. But I am not cold." },
    ],
  },
  {
    // Seollal is an age story, and 살 / 스무 / 부모님 / 형 / 누나 / 동생 all arrive at
    // m19 — the earliest module where the year everyone gains can actually be
    // counted. 이었어요 (m10) carries "was nineteen"; 있었어요 would not.
    id: "ko-m19-a-year-older",
    languageId: "ko",
    module: 19,
    level: 3,
    title: "A year older",
    theme: "One bowl of soup, and everybody in the house turns a year older.",
    tags: ["culture", "festival", "family"],
    glosses: [
      { surface: "설날", meaning: "Seollal — Korean lunar new year" },
      { surface: "떡국", meaning: "rice cake soup, eaten on Seollal" },
      { surface: "세배", meaning: "the deep new year bow children make to their elders" },
      { surface: "옛날", meaning: "long ago, in the old days" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "오늘 저는 몇 살이에요?",
        options: ["스무 살이에요", "열아홉 살이에요", "열 살이에요"],
        answer: "스무 살이에요",
      },
      {
        id: "food",
        kind: "detail",
        prompt: "우리는 설날에 뭐 먹었어요?",
        options: ["떡국을 먹었어요", "빵을 먹었어요", "사과를 먹었어요"],
        answer: "떡국을 먹었어요",
      },
    ],
    sentences: [
      { text: "저는 열아홉 살이에요.", translation: "I am nineteen." },
      { text: "오늘은 설날이에요.", translation: "Today is Seollal." },
      { text: "우리 가족은 부모님 집에 갔어요.", translation: "Our family went to my parents' house." },
      { text: "형하고 누나도 왔어요.", translation: "My older brother and older sister came too." },
      { text: "우리는 떡국을 먹었어요.", translation: "We ate tteokguk." },
      { text: "엄마의 떡국이 맛있었어요.", translation: "Mum's tteokguk was delicious." },
      { text: "한국에서 설날에 떡국을 먹어요.", translation: "In Korea people eat tteokguk on Seollal." },
      { text: "저하고 동생은 세배를 했어요.", translation: "My younger sibling and I did sebae." },
      { text: "옛날부터 한국에서 설날에 모두 한 살 먹어요.", translation: "Since long ago, in Korea everyone gains a year on Seollal." },
      { text: "동생은 열 살이에요.", translation: "My younger sibling is ten." },
      { text: "어제 동생은 아홉 살이었어요.", translation: "Yesterday my younger sibling was nine." },
      { text: "어제 저는 열아홉 살이었어요.", translation: "Yesterday I was nineteen." },
      { text: "오늘 저는 스무 살이에요.", translation: "Today I am twenty." },
      { text: "저는 열아홉 살이 좋았어요.", translation: "I liked nineteen." },
      { text: "그런데 스무 살도 좋아요.", translation: "But twenty is good too." },
    ],
  },
  {
    // Chuseok is the food holiday, and m21 is the module that hands over the food:
    // 고기 / 생선 / 채소 / 과일 / 김치 / 불고기. m20's 배 + 아파요 give the ending the
    // whole thing is built toward. 만들었어요 does not gate, so the songpyeon is
    // eaten rather than made.
    id: "ko-m21-the-chuseok-table",
    languageId: "ko",
    module: 21,
    level: 4,
    title: "The Chuseok table",
    theme: "Five hours on a train I did not want to take, and one plate too many.",
    tags: ["culture", "festival", "food", "family"],
    glosses: [
      { surface: "추석", meaning: "Chuseok — the autumn harvest holiday" },
      { surface: "명절", meaning: "a traditional holiday" },
      { surface: "고향", meaning: "hometown, the place your family is from" },
      { surface: "송편", meaning: "half-moon rice cakes eaten at Chuseok" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "우리 가족은 추석에 어디에 갔어요?",
        options: ["부모님 집에 갔어요", "병원에 갔어요", "식당에 갔어요"],
        answer: "부모님 집에 갔어요",
      },
      {
        id: "hurt",
        kind: "detail",
        prompt: "저는 지금 어디가 아파요?",
        options: ["배가 아파요", "머리가 아파요", "목이 아파요"],
        answer: "배가 아파요",
      },
    ],
    sentences: [
      { text: "추석은 가을의 명절이에요.", translation: "Chuseok is an autumn holiday." },
      { text: "추석에 모두 고향에 가요.", translation: "At Chuseok everyone goes to their hometown." },
      { text: "그래서 우리 가족은 여섯 시 기차로 부모님 집에 갔어요.", translation: "So our family went to my parents' house on the six o'clock train." },
      { text: "기차는 다섯 시간이에요.", translation: "The train is five hours." },
      { text: "저는 기차를 싫어해요.", translation: "I hate trains." },
      { text: "우리는 송편을 먹었어요.", translation: "We ate songpyeon." },
      { text: "송편이 맛있었어요.", translation: "The songpyeon was delicious." },
      { text: "우리는 고기하고 생선하고 채소를 먹었어요.", translation: "We ate meat, fish and vegetables." },
      { text: "과일도 먹었어요.", translation: "We ate fruit too." },
      { text: "저는 불고기를 좋아해요.", translation: "I like bulgogi." },
      { text: "저는 불고기를 먹었어요.", translation: "I ate bulgogi." },
      { text: "김치하고 밥도 먹었어요.", translation: "I ate kimchi and rice too." },
      { text: "그런데 지금 배가 아파요.", translation: "But now my stomach hurts." },
      { text: "엄마는 약이 있어요.", translation: "Mum has medicine." },
      { text: "저는 약을 먹었어요.", translation: "I took the medicine." },
      { text: "추석에 저는 항상 배가 아파요.", translation: "At Chuseok my stomach always hurts." },
      { text: "그리고 저는 추석을 항상 좋아해요.", translation: "And I always like Chuseok." },
    ],
  },
  {
    // m23 is the earliest module with 노래 / 잘해요 / 못해요 / 같이 — a hoesik story
    // without singing is not a hoesik story. 그래도 (m22) carries the turn. There
    // is no word for "tired" until m26, so the late hour does that work instead.
    id: "ko-m23-after-work",
    languageId: "ko",
    module: 23,
    level: 4,
    title: "After work",
    theme: "Friday, and the one evening of the week I cannot go straight home.",
    tags: ["culture", "work", "food"],
    glosses: [
      { surface: "회식", meaning: "hoesik — a company dinner the whole team goes to" },
      { surface: "노래방", meaning: "noraebang — a private karaoke room" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "저는 노래방에서 뭐 했어요?",
        options: ["노래했어요", "수영했어요", "공부했어요"],
        answer: "노래했어요",
      },
      {
        id: "jisu",
        kind: "detail",
        prompt: "지수는 뭐 먹었어요?",
        options: ["비빔밥을 먹었어요", "고기를 먹었어요", "라면을 먹었어요"],
        answer: "비빔밥을 먹었어요",
      },
    ],
    sentences: [
      { text: "금요일 여섯 시예요.", translation: "It is six o'clock on Friday." },
      { text: "저는 집에 가고 싶어요.", translation: "I want to go home." },
      { text: "그런데 오늘 회식이 있어요.", translation: "But today there is a hoesik." },
      { text: "회식에 회사 친구가 모두 가요.", translation: "All my friends from the office go to the hoesik." },
      { text: "우리는 여섯 시에 식당에 갔어요.", translation: "We went to a restaurant at six." },
      { text: "우리는 고기를 먹었어요.", translation: "We ate meat." },
      { text: "저는 고기를 제일 좋아해요.", translation: "I like meat best." },
      { text: "지수는 고기를 안 먹어요.", translation: "Jisu does not eat meat." },
      { text: "그래서 지수는 비빔밥을 먹었어요.", translation: "So Jisu ate bibimbap." },
      { text: "여덟 시에 우리는 노래방에 갔어요.", translation: "At eight we went to a noraebang." },
      { text: "한국에서 회식은 식당하고 노래방이에요.", translation: "In Korea a hoesik is a restaurant and a noraebang." },
      { text: "민수는 노래를 잘해요.", translation: "Minsu sings well." },
      { text: "저는 노래를 못해요.", translation: "I cannot sing." },
      { text: "그래도 저는 노래했어요.", translation: "Still, I sang." },
      { text: "지수하고 같이 노래했어요.", translation: "I sang together with Jisu." },
      { text: "열한 시에 저는 역에 갔어요.", translation: "At eleven I went to the station." },
      { text: "저는 회식을 안 좋아해요.", translation: "I do not like hoesik." },
      { text: "다음 회식에 저는 지수하고 노래해요.", translation: "At the next hoesik I sing with Jisu." },
    ],
  },
  {
    // 일주일 / 번 / 게임 / 음악 / 들어요 all land at m24, which is what lets the
    // river become a habit with a countable frequency rather than a single visit.
    // 들어요 has no past form that gates, so the listening stays in the habitual
    // present at the end, where it belongs.
    id: "ko-m24-the-river",
    languageId: "ko",
    module: 24,
    level: 3,
    title: "The river",
    theme: "A big city where I knew nobody, and the place that fixed it.",
    tags: ["culture", "city", "friends"],
    glosses: [
      { surface: "한강", meaning: "the Han River — the wide river through the middle of Seoul" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "저는 어디를 제일 좋아해요?",
        options: ["한강을 좋아해요", "회사를 좋아해요", "서울을 좋아해요"],
        answer: "한강을 좋아해요",
      },
      {
        id: "food",
        kind: "detail",
        prompt: "우리는 한강에서 뭐 먹었어요?",
        options: ["라면을 먹었어요", "비빔밥을 먹었어요", "빵을 먹었어요"],
        answer: "라면을 먹었어요",
      },
    ],
    sentences: [
      { text: "저는 서울에 왔어요.", translation: "I came to Seoul." },
      { text: "서울은 커요.", translation: "Seoul is big." },
      { text: "그런데 저는 친구가 없어요.", translation: "But I have no friends." },
      { text: "회사 친구가 저하고 한강에 갔어요.", translation: "A friend from the office went to the Han River with me." },
      { text: "한강은 서울에 있어요.", translation: "The Han River is in Seoul." },
      { text: "우리는 지하철로 갔어요.", translation: "We went by subway." },
      { text: "우리는 한강에서 라면을 먹었어요.", translation: "We ate ramyeon at the Han River." },
      { text: "한강 라면이 제일 맛있어요.", translation: "Han River ramyeon is the tastiest." },
      { text: "우리는 게임을 했어요.", translation: "We played a game." },
      { text: "저는 게임을 못해요.", translation: "I am bad at games." },
      { text: "그래도 게임이 좋았어요.", translation: "Still, the game was good." },
      { text: "지금 저는 일주일에 두 번 한강에 가요.", translation: "Now I go to the Han River twice a week." },
      { text: "여름에 한강이 좋아요.", translation: "In summer the Han River is good." },
      { text: "한강에서 우리는 음악을 들어요.", translation: "At the Han River we listen to music." },
      { text: "저는 한강을 제일 좋아해요.", translation: "I like the Han River best." },
      { text: "그리고 지금 저는 친구가 있어요.", translation: "And now I have friends." },
    ],
  },
  {
    // m27 is the top of the KO course and the only module with 시험 / 준비 / 연습 /
    // 실수 — which is to say, the only module where the exam day can be described
    // in its own vocabulary. 늦었어요 / 도착했어요 / 출발했어요 first gate here too.
    // L5 runs it as four scenes: the autumn before, the morning, the commute, and
    // the evening after.
    id: "ko-m27-the-exam-day",
    languageId: "ko",
    module: 27,
    level: 5,
    title: "The exam day",
    theme: "The one day a year when the whole country goes quiet.",
    tags: ["culture", "school", "exam"],
    glosses: [
      { surface: "수능", meaning: "Suneung — the national university entrance exam" },
      { surface: "시험장", meaning: "the exam hall you are assigned to sit Suneung in" },
    ],
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "저는 시험장에 어떻게 갔어요?",
        options: ["택시로 갔어요", "지하철로 갔어요", "버스로 갔어요"],
        answer: "택시로 갔어요",
      },
      {
        id: "length",
        kind: "detail",
        prompt: "시험은 몇 시간이에요?",
        options: ["여덟 시간이에요", "다섯 시간이에요", "여섯 시간이에요"],
        answer: "여덟 시간이에요",
      },
    ],
    sentences: [
      { text: "오늘은 수능이에요.", translation: "Today is Suneung." },
      { text: "수능은 한국에서 제일 큰 시험이에요.", translation: "Suneung is the biggest exam in Korea." },
      { text: "저는 시월부터 공부했어요.", translation: "I studied from October." },
      { text: "저는 학교에서 공부했어요.", translation: "I studied at school." },
      { text: "그리고 집에서도 공부했어요.", translation: "And I studied at home too." },
      { text: "저는 시험을 너무 싫어해요.", translation: "I hate exams very much." },
      { text: "오늘 저는 여섯 시에 준비했어요.", translation: "Today I got ready at six." },
      { text: "엄마가 밥을 했어요.", translation: "Mum made a meal." },
      { text: "하지만 저는 밥을 못 먹었어요.", translation: "But I could not eat the meal." },
      { text: "엄마는 저를 봤어요.", translation: "Mum looked at me." },
      { text: "엄마, 괜찮아요.", translation: "\"Mum, it is all right.\"" },
      { text: "저는 일곱 시에 집에서 출발했어요.", translation: "I left home at seven." },
      { text: "그런데 지하철이 늦었어요.", translation: "But the subway was late." },
      { text: "그래서 저는 택시로 갔어요.", translation: "So I went by taxi." },
      { text: "택시가 여덟 시에 시험장에 도착했어요.", translation: "The taxi arrived at the exam hall at eight." },
      { text: "수능에 회사도 열 시예요.", translation: "On Suneung the office too is at ten." },
      { text: "모두 수능을 알아요.", translation: "Everyone knows Suneung." },
      { text: "여덟 시 사십 분에 시험을 봤어요.", translation: "At eight forty I sat the exam." },
      { text: "시험은 여덟 시간이에요.", translation: "The exam is eight hours." },
      { text: "저는 실수했어요.", translation: "I made a mistake." },
      { text: "하지만 저는 시월부터 연습했어요.", translation: "But I practised from October." },
      { text: "그래서 괜찮아요.", translation: "So it is all right." },
      { text: "다섯 시에 저는 시험장에서 출발했어요.", translation: "At five I left the exam hall." },
      { text: "저는 너무 피곤해요.", translation: "I am very tired." },
      { text: "하지만 지금 시험이 없어요.", translation: "But now there is no exam." },
      { text: "친구하고 저는 식당에 갔어요.", translation: "My friend and I went to a restaurant." },
      { text: "우리는 고기하고 라면을 먹었어요.", translation: "We ate meat and ramyeon." },
      { text: "고기가 맛있었어요.", translation: "The meat was delicious." },
      { text: "오늘이 제일 좋아요.", translation: "Today is the best." },
    ],
  },
];
