/**
 * STORIES are newly authored for early-mid modules using only in-module
 * vocab (gate-verified). Density ramp: sparse early -> richer late.
 */
import type { Story } from "../types";

export const KO_STORIES: Story[] = [
  // ── Early (m3-m8): sparse, ~1 story per 2 modules ──────────────────────────
  {
    id: "ko-m3-new-friend",
    languageId: "ko",
    module: 3,
    level: 1,
    title: "A new classmate",
    theme: "Introducing yourself on the first day.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "이름이 뭐예요?",
        options: ["민수예요", "미나예요", "지수예요"],
        answer: "민수예요",
      },
    ],
    sentences: [
      { text: "안녕하세요.", translation: "Hello." },
      { text: "저는 학생이에요.", translation: "I'm a student." },
      { text: "이름이 민수예요.", translation: "My name is Minsu." },
      { text: "이름이 뭐예요?", translation: "What's your name?" },
      { text: "친구도 학생이에요.", translation: "My friend is a student too." },
      { text: "반갑습니다.", translation: "Nice to meet you." },
    ],
  },
  {
    id: "ko-m5-cafe-morning",
    languageId: "ko",
    module: 5,
    level: 1,
    title: "Morning at the cafe",
    theme: "A quick coffee run.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "이거 얼마예요?",
        options: ["사천 원이에요", "오천 원이에요", "삼천 원이에요"],
        answer: "사천 원이에요",
      },
    ],
    sentences: [
      { text: "커피 두 잔 주세요.", translation: "Two coffees, please." },
      { text: "물도 한 잔 주세요.", translation: "One water too, please." },
      { text: "빵도 주세요.", translation: "Bread too, please." },
      { text: "이거 얼마예요?", translation: "How much is this?" },
      { text: "사천 원이에요.", translation: "It's 4,000 won." },
      { text: "감사합니다.", translation: "Thank you." },
    ],
  },
  {
    id: "ko-m7-my-day",
    languageId: "ko",
    module: 7,
    level: 1,
    title: "My afternoon",
    theme: "A simple run-through of an afternoon.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "친구는 어디에 있어요?",
        options: ["학교에 있어요", "집에 있어요", "식당에 있어요"],
        answer: "학교에 있어요",
      },
    ],
    sentences: [
      { text: "저는 집에 있어요.", translation: "I'm at home." },
      { text: "밥을 먹어요.", translation: "I eat a meal." },
      { text: "커피를 마셔요.", translation: "I drink coffee." },
      { text: "영화도 봐요.", translation: "I watch a movie too." },
      { text: "친구는 학교에 있어요.", translation: "My friend is at school." },
      { text: "친구는 공부해요.", translation: "My friend studies." },
    ],
  },
  // ── Mid (m9-m17): ~1 story per module ──────────────────────────────────────
  {
    id: "ko-m9-a-snack",
    languageId: "ko",
    module: 9,
    level: 2,
    title: "A snack at home",
    theme: "Bread, milk, and an apple.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "뭐가 커요?",
        options: ["사과예요", "빵이에요", "우유예요"],
        answer: "사과예요",
      },
    ],
    sentences: [
      { text: "저는 집에 있어요.", translation: "I'm at home." },
      { text: "빵하고 우유가 있어요.", translation: "There's bread and milk." },
      { text: "사과도 있어요.", translation: "There's an apple too." },
      { text: "빵을 먹어요.", translation: "I eat the bread." },
      { text: "우유를 마셔요.", translation: "I drink the milk." },
      { text: "빵하고 우유가 맛있어요.", translation: "The bread and milk are tasty." },
      { text: "사과는 커요.", translation: "The apple is big." },
    ],
  },
  {
    id: "ko-m10-yesterday",
    languageId: "ko",
    module: 10,
    level: 2,
    title: "Yesterday",
    theme: "Looking back on a good day.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "어제 뭐가 좋았어요?",
        options: ["영화예요", "커피예요", "우유예요"],
        answer: "영화예요",
      },
    ],
    sentences: [
      { text: "어제 친구하고 커피를 마셨어요.", translation: "Yesterday I had coffee with a friend." },
      { text: "우리는 영화를 봤어요.", translation: "We watched a movie." },
      { text: "영화가 좋았어요.", translation: "The movie was good." },
      { text: "저는 집에서 밥을 먹었어요.", translation: "I ate at home." },
      { text: "친구는 공부했어요.", translation: "My friend studied." },
      { text: "우유도 마셨어요.", translation: "I drank milk too." },
      { text: "오늘도 커피를 마셔요.", translation: "Today I drink coffee too." },
    ],
  },
  {
    id: "ko-m11-a-day-off",
    languageId: "ko",
    module: 11,
    level: 2,
    title: "A day off",
    theme: "Staying in on a quiet day.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "오늘 저는 어디에 있어요?",
        options: ["집에 있어요", "학교에 있어요", "식당에 있어요"],
        answer: "집에 있어요",
      },
    ],
    sentences: [
      { text: "오늘은 학교에 안 가요.", translation: "Today I don't go to school." },
      { text: "저는 집에 있어요.", translation: "I stay at home." },
      { text: "영화를 보고 싶어요.", translation: "I want to watch a movie." },
      { text: "그런데 커피가 없어요.", translation: "But there's no coffee." },
      { text: "커피를 못 마셔요.", translation: "I can't have my coffee." },
      { text: "빵도 없어요.", translation: "There's no bread either." },
      { text: "그런데 밥도 안 먹어요.", translation: "But I don't eat, either." },
    ],
  },
  {
    id: "ko-m12-friday-plan",
    languageId: "ko",
    module: 12,
    level: 2,
    title: "A plan for Friday",
    theme: "Setting a time to meet.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "몇 시에 만나요?",
        options: ["세 시에 만나요", "두 시에 만나요", "한 시에 만나요"],
        answer: "세 시에 만나요",
      },
    ],
    sentences: [
      { text: "금요일에 시간이 있어요.", translation: "I have time on Friday." },
      { text: "친구하고 영화를 보고 싶어요.", translation: "I want to watch a movie with a friend." },
      { text: "지금 몇 시예요?", translation: "What time is it now?" },
      { text: "두 시예요.", translation: "It's 2 o'clock." },
      { text: "세 시에 만나요.", translation: "Let's meet at 3:00." },
      { text: "우리는 영화를 봐요.", translation: "We watch a movie." },
      { text: "우리는 밥도 먹어요.", translation: "We eat a meal too." },
    ],
  },
  {
    id: "ko-m13-my-week",
    languageId: "ko",
    module: 13,
    level: 2,
    title: "My week",
    theme: "Work, study, and a bit of exercise.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "토요일에는 뭐 해요?",
        options: ["집에 있어요", "회사에 가요", "학교에 가요"],
        answer: "집에 있어요",
      },
    ],
    sentences: [
      { text: "저는 자주 운동해요.", translation: "I exercise often." },
      { text: "월요일부터 금요일까지 회사에 가요.", translation: "I go to work from Monday to Friday." },
      { text: "회사에서 공부해요.", translation: "I study at work." },
      { text: "저는 커피를 좋아해요.", translation: "I like coffee." },
      { text: "그리고 운동도 좋아해요.", translation: "And I like exercise too." },
      { text: "가끔 영화를 봐요.", translation: "Sometimes I watch a movie." },
      { text: "토요일에는 항상 집에 있어요.", translation: "On Saturdays I always stay home." },
    ],
  },
  {
    id: "ko-m14-a-busy-day",
    languageId: "ko",
    module: 14,
    level: 2,
    title: "A busy day",
    theme: "Too much to do, too little time.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "저는 뭐를 못 마셔요?",
        options: ["커피를 못 마셔요", "물을 못 마셔요", "우유를 못 마셔요"],
        answer: "커피를 못 마셔요",
      },
    ],
    sentences: [
      { text: "저는 바빠서 시간이 없어요.", translation: "I'm busy, so I have no time." },
      { text: "오늘 회사에 가요.", translation: "I go to work today." },
      { text: "회사에서 공부하고 밥을 먹어요.", translation: "At work I study and eat." },
      { text: "친구가 와요.", translation: "A friend comes over." },
      { text: "친구는 커피를 마셔요.", translation: "My friend drinks coffee." },
      { text: "저는 바빠서 커피를 못 마셔요.", translation: "But I'm too busy for coffee." },
      { text: "기다려 주세요.", translation: "Please wait." },
    ],
  },
  {
    id: "ko-m15-relaxing-at-home",
    languageId: "ko",
    module: 15,
    level: 2,
    title: "Relaxing at home",
    theme: "A quiet afternoon with a friend.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "오늘 저는 어디에 있어요?",
        options: ["집에 있어요", "학교에 있어요", "회사에 있어요"],
        answer: "집에 있어요",
      },
    ],
    sentences: [
      { text: "오늘은 집에 있어요.", translation: "Today I'm at home." },
      { text: "커피를 마시고 있어요.", translation: "I'm drinking coffee." },
      { text: "영화를 보고 있어요.", translation: "I'm watching a movie." },
      { text: "친구가 전화해요.", translation: "A friend calls." },
      { text: "친구도 집에 와요.", translation: "My friend comes over too." },
      { text: "여기 앉아도 돼요.", translation: "You can sit here." },
      { text: "우리는 커피를 마시고 영화를 봐요.", translation: "We drink coffee and watch a movie." },
    ],
  },
  {
    id: "ko-m16-friends-house",
    languageId: "ko",
    module: 16,
    level: 2,
    title: "At a friend's house",
    theme: "Visiting a friend's place.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "저는 뭐를 좋아해요?",
        options: ["커피를 좋아해요", "담배를 좋아해요", "영화를 좋아해요"],
        answer: "커피를 좋아해요",
      },
    ],
    sentences: [
      { text: "오늘 친구 집에 가요.", translation: "Today I go to my friend's house." },
      { text: "친구 집에서는 담배를 피우면 안 돼요.", translation: "You can't smoke at my friend's house." },
      { text: "저는 담배를 싫어해요.", translation: "I don't like cigarettes." },
      { text: "네, 알겠어요.", translation: "OK, got it." },
      { text: "친구는 커피를 좋아해요.", translation: "My friend likes coffee." },
      { text: "저도 커피를 좋아해요.", translation: "I like coffee too." },
      { text: "우리는 커피를 마시고 영화를 봐요.", translation: "We drink coffee and watch a movie." },
    ],
  },
  {
    id: "ko-m17-my-commute",
    languageId: "ko",
    module: 17,
    level: 2,
    title: "My commute",
    theme: "Bus, subway, and a left turn.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "회사는 어디에 있어요?",
        options: ["왼쪽에 있어요", "오른쪽에 있어요", "역에 있어요"],
        answer: "왼쪽에 있어요",
      },
    ],
    sentences: [
      { text: "저는 회사에 가요.", translation: "I go to work." },
      { text: "버스를 타요.", translation: "I take the bus." },
      { text: "다음 역에서 내려요.", translation: "I get off at the next stop." },
      { text: "그리고 지하철을 타요.", translation: "And then I take the subway." },
      { text: "회사까지 똑바로 가요.", translation: "I go straight to the office." },
      { text: "회사는 왼쪽에 있어요.", translation: "The office is on the left." },
      { text: "저는 회사에서 공부해요.", translation: "I study at work." },
    ],
  },
  // ── Late (m18-m27): ramp up — 1, sometimes 2 stories per module ────────────
  {
    id: "ko-m18-tomorrows-weather",
    languageId: "ko",
    module: 18,
    level: 2,
    title: "Tomorrow's weather",
    theme: "A clear day, then rain.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "내일은 뭐가 올 거예요?",
        options: ["비가 올 거예요", "눈이 올 거예요", "바람이 올 거예요"],
        answer: "비가 올 거예요",
      },
    ],
    sentences: [
      { text: "오늘은 날씨가 좋아요.", translation: "The weather is nice today." },
      { text: "맑아요.", translation: "It's clear." },
      { text: "그런데 내일은 비가 올 거예요.", translation: "But tomorrow it will rain." },
      { text: "내일은 추워요.", translation: "Tomorrow it's cold." },
      { text: "저는 겨울을 좋아해요.", translation: "I like winter." },
      { text: "겨울에는 눈이 와요.", translation: "In winter it snows." },
      { text: "여름에는 더워요.", translation: "In summer it's hot." },
    ],
  },
  {
    id: "ko-m19-my-family",
    languageId: "ko",
    module: 19,
    level: 2,
    title: "My family",
    theme: "Four of us, and an older brother.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "우리 가족은 몇 명이에요?",
        options: ["네 명이에요", "세 명이에요", "두 명이에요"],
        answer: "네 명이에요",
      },
    ],
    sentences: [
      { text: "우리 가족은 네 명이에요.", translation: "There are four people in my family." },
      { text: "엄마, 아빠, 형, 그리고 저요.", translation: "Mom, dad, my older brother, and me." },
      { text: "형은 스무 살이에요.", translation: "My brother is twenty." },
      { text: "저는 학생이에요.", translation: "I'm a student." },
      { text: "형은 회사에 가요.", translation: "My brother goes to work." },
      { text: "우리 가족은 커피를 좋아해요.", translation: "My family likes coffee." },
      { text: "저는 우리 가족을 좋아해요.", translation: "I love my family." },
    ],
  },
  {
    id: "ko-m20-a-cold",
    languageId: "ko",
    module: 20,
    level: 2,
    title: "A cold",
    theme: "Aches, a fever, and some medicine.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "어디가 아파요?",
        options: ["머리가 아파요", "다리가 아파요", "팔이 아파요"],
        answer: "머리가 아파요",
      },
    ],
    sentences: [
      { text: "오늘은 머리가 아파요.", translation: "My head hurts today." },
      { text: "그리고 배도 아파요.", translation: "And my stomach hurts too." },
      { text: "감기예요.", translation: "It's a cold." },
      { text: "저는 병원에 가요.", translation: "I go to the hospital." },
      { text: "약을 먹어요.", translation: "I take medicine." },
      { text: "약을 먹으면 괜찮을 거예요.", translation: "If I take medicine, I'll be fine." },
      { text: "그리고 집에 있어요.", translation: "And I stay home." },
    ],
  },
  {
    id: "ko-m21-a-korean-meal",
    languageId: "ko",
    module: 21,
    level: 2,
    title: "A Korean meal",
    theme: "Bibimbap, bulgogi, and kimchi.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "친구는 뭐를 먹어요?",
        options: ["생선을 먹어요", "비빔밥을 먹어요", "라면을 먹어요"],
        answer: "생선을 먹어요",
      },
    ],
    sentences: [
      { text: "저는 식당에 가요.", translation: "I go to a restaurant." },
      { text: "비빔밥하고 불고기를 먹어요.", translation: "I eat bibimbap and bulgogi." },
      { text: "김치도 맛있어요.", translation: "The kimchi is tasty too." },
      { text: "라면도 좋아해요.", translation: "I like ramen too." },
      { text: "친구는 생선하고 채소를 먹어요.", translation: "My friend eats fish and vegetables." },
      { text: "과일도 먹어요.", translation: "We eat fruit too." },
      { text: "커피 한 잔 주세요.", translation: "One coffee, please." },
    ],
  },
  {
    id: "ko-m21-cooking-dinner",
    languageId: "ko",
    module: 21,
    level: 2,
    title: "Cooking dinner",
    theme: "A meal at home with a friend.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "친구는 뭐를 마셔요?",
        options: ["우유를 마셔요", "커피를 마셔요", "물을 마셔요"],
        answer: "우유를 마셔요",
      },
    ],
    sentences: [
      { text: "오늘은 집에서 밥을 먹어요.", translation: "Today I eat at home." },
      { text: "저는 불고기를 좋아해요.", translation: "I like bulgogi." },
      { text: "그래서 불고기하고 밥을 먹어요.", translation: "So I have bulgogi and rice." },
      { text: "김치도 있어요.", translation: "There's kimchi too." },
      { text: "친구도 집에 와요.", translation: "My friend comes over too." },
      { text: "우리는 라면하고 과일도 먹어요.", translation: "We eat ramen and fruit too." },
      { text: "저는 커피를 마시고 친구는 우유를 마셔요.", translation: "I drink coffee and my friend drinks milk." },
    ],
  },
  {
    id: "ko-m22-which-i-like-more",
    languageId: "ko",
    module: 22,
    level: 2,
    title: "Which I like more",
    theme: "Comparing coffee and tea.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "뭐가 제일 좋아요?",
        options: ["커피예요", "차예요", "우유예요"],
        answer: "커피예요",
      },
    ],
    sentences: [
      { text: "저는 커피하고 차 중에서 커피가 더 좋아요.", translation: "Between coffee and tea, I like coffee more." },
      { text: "차는 커피보다 싸요.", translation: "Tea is cheaper than coffee." },
      { text: "그래도 커피가 제일 맛있어요.", translation: "Still, coffee is the tastiest." },
      { text: "친구는 차를 더 좋아해요.", translation: "My friend likes tea more." },
      { text: "뭐가 제일 좋아요?", translation: "What do you like best?" },
      { text: "커피가 가장 좋아요.", translation: "I like coffee best." },
      { text: "저는 커피를 자주 마셔요.", translation: "I drink coffee often." },
    ],
  },
  {
    id: "ko-m22-bibimbap-or-ramen",
    languageId: "ko",
    module: 22,
    level: 2,
    title: "Bibimbap or ramen?",
    theme: "Picking a favorite at the restaurant.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "이 식당은 뭐가 가장 맛있어요?",
        options: ["불고기예요", "비빔밥이에요", "라면이에요"],
        answer: "불고기예요",
      },
    ],
    sentences: [
      { text: "저는 비빔밥하고 라면 중에서 비빔밥이 더 좋아요.", translation: "Between bibimbap and ramen, I like bibimbap more." },
      { text: "라면은 비빔밥보다 싸요.", translation: "Ramen is cheaper than bibimbap." },
      { text: "그래도 비빔밥이 제일 맛있어요.", translation: "Still, bibimbap is the tastiest." },
      { text: "친구는 라면을 더 좋아해요.", translation: "My friend likes ramen more." },
      { text: "우리는 식당에서 밥을 먹어요.", translation: "We eat at a restaurant." },
      { text: "이 식당은 불고기가 가장 맛있어요.", translation: "This restaurant's bulgogi is the tastiest." },
      { text: "그래서 저는 이 식당을 좋아해요.", translation: "So I like this place." },
    ],
  },
  {
    id: "ko-m23-weekend-plans",
    languageId: "ko",
    module: 23,
    level: 2,
    title: "Weekend plans",
    theme: "Cooking and doing things together.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "저는 뭐를 못해요?",
        options: ["노래를 못해요", "요리를 못해요", "수영을 못해요"],
        answer: "노래를 못해요",
      },
    ],
    sentences: [
      { text: "주말에 뭐 할까요?", translation: "What shall we do on the weekend?" },
      { text: "저는 요리를 잘해요.", translation: "I'm good at cooking." },
      { text: "같이 요리할까요?", translation: "Shall we cook together?" },
      { text: "저는 수영도 잘해요.", translation: "I'm good at swimming too." },
      { text: "그런데 노래는 못해요.", translation: "But I can't sing." },
      { text: "주말에 같이 운동합시다.", translation: "Let's exercise together on the weekend." },
      { text: "그리고 같이 밥도 먹어요.", translation: "And let's eat together too." },
    ],
  },
  {
    id: "ko-m24-my-hobbies",
    languageId: "ko",
    module: 24,
    level: 2,
    title: "My hobbies",
    theme: "Music, photos, and a bit of singing.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "제 취미는 뭐예요?",
        options: ["음악이에요", "게임이에요", "요리예요"],
        answer: "음악이에요",
      },
    ],
    sentences: [
      { text: "제 취미는 음악이에요.", translation: "My hobby is music." },
      { text: "저는 음악을 자주 들어요.", translation: "I listen to music often." },
      { text: "사진도 좋아해요.", translation: "I like photography too." },
      { text: "노래도 할 줄 알아요.", translation: "I also know how to sing." },
      { text: "일주일에 두 번 게임을 해요.", translation: "I play games twice a week." },
      { text: "저는 그림도 좋아해요.", translation: "I like drawing too." },
      { text: "주말에 같이 할까요?", translation: "Shall we do it together on the weekend?" },
    ],
  },
  {
    id: "ko-m24-music-and-games",
    languageId: "ko",
    module: 24,
    level: 2,
    title: "Music and games",
    theme: "Sharing hobbies with a friend.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "친구는 뭐를 좋아해요?",
        options: ["게임을 좋아해요", "노래를 좋아해요", "사진을 좋아해요"],
        answer: "게임을 좋아해요",
      },
    ],
    sentences: [
      { text: "저는 음악을 좋아해요.", translation: "I like music." },
      { text: "저는 노래도 할 줄 알아요.", translation: "I also know how to sing." },
      { text: "일주일에 세 번 노래해요.", translation: "I sing three times a week." },
      { text: "친구는 게임을 좋아해요.", translation: "My friend likes games." },
      { text: "우리는 같이 게임을 해요.", translation: "We play games together." },
      { text: "저는 사진도 좋아해요.", translation: "I like photos too." },
      { text: "취미가 뭐예요?", translation: "What's your hobby?" },
    ],
  },
  {
    id: "ko-m25-planning-a-trip",
    languageId: "ko",
    module: 25,
    level: 2,
    title: "Planning a trip",
    theme: "A trip to Japan and a hot spring.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "어디에 가려고 해요?",
        options: ["일본에 가려고 해요", "한국에 가려고 해요", "학교에 가려고 해요"],
        answer: "일본에 가려고 해요",
      },
    ],
    sentences: [
      { text: "저는 여행 계획이 있어요.", translation: "I have travel plans." },
      { text: "저는 일본에 가려고 해요.", translation: "I intend to go to Japan." },
      { text: "일본에 간 적이 있어요.", translation: "I've been to Japan before." },
      { text: "온천에 가고 싶어요.", translation: "I want to go to a hot spring." },
      { text: "축제도 보고 싶어요.", translation: "I want to see a festival too." },
      { text: "다음 주말에 출발해요.", translation: "I leave next weekend." },
      { text: "저는 여행을 좋아해요.", translation: "I like traveling." },
    ],
  },
  {
    id: "ko-m25-trip-with-a-friend",
    languageId: "ko",
    module: 25,
    level: 2,
    title: "A trip with a friend",
    theme: "Two friends heading to Japan.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "저는 뭐를 하고 싶어요?",
        options: ["온천에 가고 싶어요", "축제를 보고 싶어요", "집에 가고 싶어요"],
        answer: "온천에 가고 싶어요",
      },
    ],
    sentences: [
      { text: "친구하고 여행 계획이 있어요.", translation: "My friend and I have travel plans." },
      { text: "우리는 일본에 가려고 해요.", translation: "We intend to go to Japan." },
      { text: "친구는 일본에 간 적이 있어요.", translation: "My friend has been to Japan before." },
      { text: "저는 온천에 가고 싶어요.", translation: "I want to go to a hot spring." },
      { text: "친구는 축제를 보고 싶어요.", translation: "My friend wants to see a festival." },
      { text: "우리는 다음 주말에 출발해요.", translation: "We leave next weekend." },
      { text: "일본에서 비빔밥을 먹어요.", translation: "We'll eat bibimbap in Japan." },
    ],
  },
  {
    id: "ko-m26-a-rough-morning",
    languageId: "ko",
    module: 26,
    level: 2,
    title: "A rough morning",
    theme: "Late, tired, and a traffic jam.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "왜 회사에 늦었어요?",
        options: ["길이 막혔거든요", "피곤해요", "실수했어요"],
        answer: "길이 막혔거든요",
      },
    ],
    sentences: [
      { text: "오늘 회사에 늦었어요.", translation: "I was late for work today." },
      { text: "길이 너무 막혔거든요.", translation: "The road was really jammed, you see." },
      { text: "죄송해요.", translation: "I'm sorry." },
      { text: "저는 너무 피곤해요.", translation: "I'm so tired." },
      { text: "그리고 실수도 했어요.", translation: "And I made a mistake too." },
      { text: "저는 피곤해서 집에 가고 싶어요.", translation: "I'm tired, so I want to go home." },
      { text: "하지만 내일은 회사에 가요.", translation: "But tomorrow I go to work." },
    ],
  },
  {
    id: "ko-m27-before-the-exam",
    languageId: "ko",
    module: 27,
    level: 2,
    title: "Before the exam",
    theme: "Getting ready, and taking care.",
    questions: [
      {
        id: "gist",
        kind: "gist",
        prompt: "쉬면 어떻게 돼요?",
        options: ["건강해져요", "피곤해요", "괜찮을 거예요"],
        answer: "건강해져요",
      },
    ],
    sentences: [
      { text: "내일은 시험이 있어요.", translation: "I have an exam tomorrow." },
      { text: "저는 시험 준비를 해요.", translation: "I'm getting ready for the exam." },
      { text: "오늘은 연습해요.", translation: "Today I practice." },
      { text: "저는 너무 피곤해요.", translation: "I'm so tired." },
      { text: "쉬면 건강해져요.", translation: "If I rest, I'll get healthy." },
      { text: "그래서 저는 약속을 안 해요.", translation: "So I don't make plans." },
      { text: "조심하세요.", translation: "Take care." },
    ],
  },
];
