/**
 * Domain icon name → Lucide component. Tree-shake safe.
 * Only the UI layer imports Lucide; app code uses Icon with domain names.
 */

import {
  ArrowBigLeft,
  Github,
  ArrowBigRight,
  ArrowLeft,
  ArrowRight,
  LogOut,
  BookOpen,
  BookOpenText,
  BookText,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Cloud,
  FileText,
  Film,
  Copy,
  Dumbbell,
  Flame,
  Globe,
  GraduationCap,
  Headphones,
  Mic,
  Music,
  Newspaper,
  GripVertical,
  Info,
  Layers2,
  Link2,
  Lock,
  Menu,
  PartyPopper,
  Podcast,
  Pause,
  Play,
  SwatchBook,
  Pencil,
  Plus,
  RefreshCw,
  Settings,
  Smartphone,
  Square,
  Star,
  Tv,
  Trash2,
  Upload,
  User,
  Video,
  X,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const iconRegistry = {
  lock: Lock,
  settings: Settings,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  close: X,
  user: User,
  logOut: LogOut,
  menu: Menu,
  palette: SwatchBook,
  refresh: RefreshCw,
  cloud: Cloud,
  check: Check,
  circle: Circle,
  info: Info,
  bookOpen: BookOpen,
  bookText: BookText,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  gripVertical: GripVertical,
  trash: Trash2,
  pencil: Pencil,
  plus: Plus,
  star: Star,
  decks: BookOpen,
  stories: BookOpenText,
  dumbbell: Dumbbell,
  flame: Flame,
  github: Github,
  globe: Globe,
  graduationCap: GraduationCap,
  arrowBigLeft: ArrowBigLeft,
  arrowBigRight: ArrowBigRight,
  avatarFallback: User,
  link: Link2,
  video: Video,
  play: Play,
  pause: Pause,
  upload: Upload,
  copy: Copy,
  chevronUp: ChevronUp,
  layers: Layers2,
  partyPopper: PartyPopper,
  headphones: Headphones,
  mic: Mic,
  music: Music,
  podcast: Podcast,
  film: Film,
  tv: Tv,
  newspaper: Newspaper,
  fileText: FileText,
  smartphone: Smartphone,
  // Placeholder – replace with correct icon if needed
  placeholder: Square,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;
