/**
 * Domain icon name → Lucide component. Tree-shake safe.
 * Only the UI layer imports Lucide; app code uses Icon with domain names.
 */

import {
  Activity,
  AlertTriangle,
  ArrowBigLeft,
  Github,
  ArrowBigRight,
  ArrowLeft,
  ArrowRight,
  BarChart2,
  Camera,
  LogOut,
  BookOpen,
  BookOpenText,
  BookText,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  Moon,
  Cloud,
  CloudAlert,
  CloudSync,
  CloudUpload,
  Crown,
  Edit2,
  FileText,
  Film,
  Copy,
  Dumbbell,
  Eye,
  Flame,
  Gem,
  Globe,
  GraduationCap,
  Hand,
  Headphones,
  HelpCircle,
  Heart,
  Lightbulb,
  Megaphone,
  MessageCircle,
  Mic,
  MoreHorizontal,
  Music,
  Newspaper,
  Package,
  GripVertical,
  Info,
  Layers2,
  LayoutGrid,
  Link2,
  List,
  Lock,
  LayoutDashboard,
  Menu,
  MoreVertical,
  PartyPopper,
  Podcast,
  Pause,
  Play,
  RotateCcw,
  Ruler,
  Search,
  Send,
  Smile,
  Sparkles,
  SwatchBook,
  Pencil,
  Plus,
  RefreshCw,
  Settings,
  Shield,
  ShieldCheck,
  Smartphone,
  Square,
  Star,
  Target,
  TrendingUp,
  Trophy,
  Tv,
  Trash2,
  Upload,
  User,
  UserPlus,
  UserMinus,
  Ban,
  Users,
  Video,
  Volume2,
  Wrench,
  Zap,
  X,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const iconRegistry = {
  lock: Lock,
  settings: Settings,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  close: X,
  user: User,
  logOut: LogOut,
  menu: Menu,
  palette: SwatchBook,
  refresh: RefreshCw,
  edit2: Edit2,
  rotateCcw: RotateCcw,
  trendingUp: TrendingUp,
  activity: Activity,
  alertTriangle: AlertTriangle,
  checkCircle: CheckCircle,
  wrench: Wrench,
  shield: Shield,
  shieldCheck: ShieldCheck,
  layoutDashboard: LayoutDashboard,
  layoutGrid: LayoutGrid,
  list: List,
  cloud: Cloud,
  cloudSync: CloudSync,
  cloudUpload: CloudUpload,
  cloudAlert: CloudAlert,
  check: Check,
  circle: Circle,
  info: Info,
  help: HelpCircle,
  bookOpen: BookOpen,
  bookText: BookText,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  gripVertical: GripVertical,
  trash: Trash2,
  pencil: Pencil,
  plus: Plus,
  star: Star,
  decks: BookOpen,
  stories: BookOpenText,
  dumbbell: Dumbbell,
  eye: Eye,
  flame: Flame,
  /** In-app currency (lingots). Brand-level concept. */
  gem: Gem,
  moreVertical: MoreVertical,
  github: Github,
  globe: Globe,
  graduationCap: GraduationCap,
  arrowBigLeft: ArrowBigLeft,
  arrowBigRight: ArrowBigRight,
  avatarFallback: User,
  link: Link2,
  video: Video,
  play: Play,
  /** Speaker icon for "play audio" buttons — distinct from `play` (▶
   *  triangle) so audio buttons read as audio, not as start-animation. */
  volume: Volume2,
  pause: Pause,
  upload: Upload,
  copy: Copy,
  chevronUp: ChevronUp,
  layers: Layers2,
  partyPopper: PartyPopper,
  headphones: Headphones,
  mic: Mic,
  music: Music,
  podcast: Podcast,
  film: Film,
  tv: Tv,
  newspaper: Newspaper,
  /** Package — inventory / shop items affordance */
  package: Package,
  fileText: FileText,
  smartphone: Smartphone,
  search: Search,
  send: Send,
  smile: Smile,
  sparkles: Sparkles,
  trophy: Trophy,
  crown: Crown,
  heart: Heart,
  hand: Hand,
  messageCircle: MessageCircle,
  users: Users,
  userPlus: UserPlus,
  userMinus: UserMinus,
  ban: Ban,
  moreHorizontal: MoreHorizontal,
  /** BarChart2 — data/stats indicator */
  barChart: BarChart2,
  /** Camera — change profile picture affordance */
  camera: Camera,
  /** Lightbulb — tip / hint affordance */
  lightbulb: Lightbulb,
  /** Megaphone — announcement / speech */
  megaphone: Megaphone,
  /** Ruler — measurement / lengths */
  ruler: Ruler,
  /** Target / crosshair — "target" label in speaking steps */
  target: Target,
  /** Zap — quick / boost indicator */
  zap: Zap,
  /** Clock — time / duration (e.g. ad-free 30m window) */
  clock: Clock,
  /** Moon — overnight / all-day quiet (e.g. ad-free 24h window) */
  moon: Moon,
  // Placeholder – replace with correct icon if needed
  placeholder: Square,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;
