/**
 * Domain icon name → Lucide component. Tree-shake safe.
 * Only the UI layer imports Lucide; app code uses Icon with domain names.
 */

import {
  ArrowBigLeft,
  Github,
  ArrowBigRight,
  ArrowLeft,
  ArrowRight,
  LogOut,
  BookOpen,
  BookOpenText,
  BookText,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Cloud,
  Crown,
  FileText,
  Film,
  Copy,
  Dumbbell,
  Eye,
  Flame,
  Gem,
  Globe,
  GraduationCap,
  Hand,
  Headphones,
  Heart,
  MessageCircle,
  Mic,
  MoreHorizontal,
  Music,
  Newspaper,
  GripVertical,
  Info,
  Layers2,
  LayoutGrid,
  Link2,
  List,
  Lock,
  LayoutDashboard,
  Menu,
  MoreVertical,
  PartyPopper,
  Podcast,
  Pause,
  Play,
  Search,
  Send,
  Smile,
  Sparkles,
  SwatchBook,
  Pencil,
  Plus,
  RefreshCw,
  Settings,
  Shield,
  Smartphone,
  Square,
  Star,
  Trophy,
  Tv,
  Trash2,
  Upload,
  User,
  UserPlus,
  Users,
  Video,
  Volume2,
  X,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const iconRegistry = {
  lock: Lock,
  settings: Settings,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  close: X,
  user: User,
  logOut: LogOut,
  menu: Menu,
  palette: SwatchBook,
  refresh: RefreshCw,
  shield: Shield,
  layoutDashboard: LayoutDashboard,
  layoutGrid: LayoutGrid,
  list: List,
  cloud: Cloud,
  check: Check,
  circle: Circle,
  info: Info,
  bookOpen: BookOpen,
  bookText: BookText,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  gripVertical: GripVertical,
  trash: Trash2,
  pencil: Pencil,
  plus: Plus,
  star: Star,
  decks: BookOpen,
  stories: BookOpenText,
  dumbbell: Dumbbell,
  eye: Eye,
  flame: Flame,
  /** In-app currency (lingots). Brand-level concept. */
  gem: Gem,
  moreVertical: MoreVertical,
  github: Github,
  globe: Globe,
  graduationCap: GraduationCap,
  arrowBigLeft: ArrowBigLeft,
  arrowBigRight: ArrowBigRight,
  avatarFallback: User,
  link: Link2,
  video: Video,
  play: Play,
  /** Speaker icon for "play audio" buttons — distinct from `play` (▶
   *  triangle) so audio buttons read as audio, not as start-animation. */
  volume: Volume2,
  pause: Pause,
  upload: Upload,
  copy: Copy,
  chevronUp: ChevronUp,
  layers: Layers2,
  partyPopper: PartyPopper,
  headphones: Headphones,
  mic: Mic,
  music: Music,
  podcast: Podcast,
  film: Film,
  tv: Tv,
  newspaper: Newspaper,
  fileText: FileText,
  smartphone: Smartphone,
  search: Search,
  send: Send,
  smile: Smile,
  sparkles: Sparkles,
  trophy: Trophy,
  crown: Crown,
  heart: Heart,
  hand: Hand,
  messageCircle: MessageCircle,
  users: Users,
  userPlus: UserPlus,
  moreHorizontal: MoreHorizontal,
  // Placeholder – replace with correct icon if needed
  placeholder: Square,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;
