/**
 * Korean conjugation-trainer provider (Phase 1).
 *
 * Implements the generic `ConjugationTrainerProvider` so the shared drill
 * surface lights up for KO exactly as it does for JA — driven by
 * `getLanguageModule("ko").conjugation.trainer`, with zero KO-specific code in
 * the UI. Forms + distractors are generated by the jamo engine
 * (`conjugationEngine.ts`) off the authored lemma list (`conjugationTables.ts`).
 *
 * Phase 1 scope (per docs/ja-ko-parity-audit-2026-07-15.md §2.5):
 *   - drills gate on REACHED MODULE only;
 *   - NO Track-B grammar SRS integration (grading is a no-op — see the TODO in
 *     `gradeSessionIfOnPath`). Phase 2 generalizes `grammarSrs.ts` off the JA
 *     atom map and wires a `ko-grammar-points.json`;
 *   - NO combo (stacked) forms and NO free drill yet — the hub degrades to
 *     free-mix multi-select and hides the Mix tile.
 */
import type {
  ConjugationTrainerProvider,
  ConjTrainerTypeMeta,
  ConjTrainerQuestion,
  ConjWordClassInfo,
  ConjCheatItem,
  ConjFormationRow,
  ConjExampleSentence,
} from "@/shared/conjugation/types";
import { shuffle, clamp, roundRobinBuild, type QuestionFactory } from "@/shared/conjugation/session";
import { registerConjugationTrainer } from "@/shared/conjugation/registry";
import {
  conjugateKo,
  generateKoDistractors,
  type KoFormKey,
  type KoStemClass,
} from "./conjugationEngine";
import { KO_LEMMAS, getLemmasUpToModule, type KoLemma } from "./conjugationTables";

// ─── Trainer types (hub tiles) ────────────────────────────────────────────

interface KoTile {
  id: string;
  title: string;
  subtitle: string;
  glyph: string;
  colorVar: string;
  form: KoFormKey;
  unlockModule: number;
  verbsOnly: boolean;
  category: "verb" | "adjective";
  formation: ConjFormationRow[];
}

const R = (groupLabel: string, pattern: string, exampleDict: string, exampleForm: string): ConjFormationRow => ({
  groupLabel,
  pattern,
  exampleDict,
  exampleForm,
});

/** Present-polite formation covers the vowel-harmony + every irregular class —
 *  reused (trimmed) by casual/past since they share the -아/어 stem. */
const PRESENT_FORMATION: ConjFormationRow[] = [
  R("Regular (batchim)", "ㅏ/ㅗ stem → 아요, else → 어요", "먹다", "먹어요"),
  R("Vowel stem", "contracts: 오 → 와, 주 → 줘, 시 → 셔", "오다", "와요"),
  R("하다", "하 → 해", "공부하다", "공부해요"),
  R("ㅂ irregular", "받침 ㅂ → 우 (+ 어)", "춥다", "추워요"),
  R("ㄷ irregular", "받침 ㄷ → ㄹ", "듣다", "들어요"),
  R("ㅅ irregular", "받침 ㅅ drops", "짓다", "지어요"),
  R("르 irregular", "adds ㄹ to the prior syllable", "모르다", "몰라요"),
  R("ㅎ irregular", "받침 ㅎ drops, vowel → ㅐ", "그렇다", "그래요"),
  R("으 (ㅡ-deletion)", "final ㅡ drops", "쓰다", "써요"),
];

const KO_TILES: KoTile[] = [
  {
    id: "present-polite",
    title: "해요체 · polite",
    subtitle: "Everyday polite speech — the -아/어요 ending.",
    glyph: "요",
    colorVar: "--type-haeyo",
    form: "present.polite",
    unlockModule: 2,
    verbsOnly: false,
    category: "verb",
    formation: PRESENT_FORMATION,
  },
  {
    id: "present-casual",
    title: "반말 · casual",
    subtitle: "Plain speech with close friends — drop the 요.",
    glyph: "반",
    colorVar: "--type-banmal",
    form: "present.casual",
    unlockModule: 3,
    verbsOnly: false,
    category: "verb",
    formation: [
      R("Rule", "the 해요체 form without 요", "먹다", "먹어"),
      R("Vowel stem", "오다 → 와, 하다 → 해", "하다", "해"),
      R("Irregulars", "same stem as 해요체", "듣다", "들어"),
    ],
  },
  {
    id: "present-formal",
    title: "합쇼체 · formal",
    subtitle: "Formal/deferential -습니다 · -ㅂ니다.",
    glyph: "다",
    colorVar: "--type-formal",
    form: "present.formal",
    unlockModule: 3,
    verbsOnly: false,
    category: "verb",
    formation: [
      R("Consonant stem", "받침 있음 → -습니다", "먹다", "먹습니다"),
      R("Vowel stem", "받침 없음 → -ㅂ니다", "가다", "갑니다"),
      R("ㄹ stem", "ㄹ drops → -ㅂ니다", "살다", "삽니다"),
      R("Irregulars keep 받침", "before a consonant ending", "춥다", "춥습니다"),
    ],
  },
  {
    id: "past",
    title: "Past · -았/었어요",
    subtitle: "Past tense in polite speech.",
    glyph: "었",
    colorVar: "--type-past",
    form: "past.polite",
    unlockModule: 3,
    verbsOnly: false,
    category: "verb",
    formation: [
      R("Rule", "해요체 stem + ㅆ + 어요", "먹다", "먹었어요"),
      R("Vowel stem", "가 → 갔, 하 → 했", "가다", "갔어요"),
      R("Irregulars", "형성은 현재형과 동일", "듣다", "들었어요"),
    ],
  },
  {
    id: "future",
    title: "Future · -(으)ㄹ 거예요",
    subtitle: "Plans and predictions.",
    glyph: "거",
    colorVar: "--type-future",
    form: "future.polite",
    unlockModule: 4,
    verbsOnly: false,
    category: "verb",
    formation: [
      R("Consonant stem", "-을 거예요", "먹다", "먹을 거예요"),
      R("Vowel / ㄹ stem", "-ㄹ 거예요", "가다", "갈 거예요"),
      R("ㄷ irregular", "ㄷ → ㄹ, then -을", "듣다", "들을 거예요"),
      R("ㅂ irregular", "ㅂ → 우, then -ㄹ", "춥다", "추울 거예요"),
    ],
  },
  {
    id: "progressive",
    title: "Progressive · -고 있어요",
    subtitle: "Ongoing action — “is …-ing”. (Verbs only.)",
    glyph: "고",
    colorVar: "--type-prog",
    form: "progressive.polite",
    unlockModule: 4,
    verbsOnly: true,
    category: "verb",
    formation: [
      R("Rule", "stem + 고 있어요 (no stem change)", "먹다", "먹고 있어요"),
      R("Irregulars unaffected", "고 attaches to the raw stem", "듣다", "듣고 있어요"),
    ],
  },
  {
    id: "negation",
    title: "Negation · 안 …",
    subtitle: "Short negation — 안 before the verb.",
    glyph: "안",
    colorVar: "--type-neg",
    form: "neg.short.present.polite",
    unlockModule: 4,
    verbsOnly: false,
    category: "verb",
    formation: [
      R("Short negation", "안 + verb", "먹다", "안 먹어요"),
      R("하다 compounds split", "noun 안 하다", "공부하다", "공부 안 해요"),
      R("Long negation", "-지 않아요", "먹다", "먹지 않아요"),
    ],
  },

  // ── Endings & connectives — the "little words" that make KO hard ──────────
  {
    id: "desiderative",
    title: "Want to · -고 싶어요",
    subtitle: "“I want to …” — attaches straight to the stem. (Verbs only.)",
    glyph: "싶",
    colorVar: "--type-want",
    form: "desiderative",
    unlockModule: 5,
    verbsOnly: true,
    category: "verb",
    formation: [
      R("Rule", "stem + 고 싶어요 (no stem change)", "먹다", "먹고 싶어요"),
      R("Irregulars unaffected", "고 attaches to the raw stem", "듣다", "듣고 싶어요"),
    ],
  },
  {
    id: "connective-and",
    title: "And · -고",
    subtitle: "Links two clauses — “… and (then) …”.",
    glyph: "고",
    colorVar: "--type-and",
    form: "connective.and",
    unlockModule: 5,
    verbsOnly: false,
    category: "verb",
    formation: [
      R("Rule", "stem + 고 (no stem change)", "먹다", "먹고"),
      R("Adjectives too", "same rule", "좋다", "좋고"),
      R("Irregulars unaffected", "고 attaches raw", "듣다", "듣고"),
    ],
  },
  {
    id: "honorific-command",
    title: "Please / command · -(으)세요",
    subtitle: "Polite command + honorific — “please do …”. (Verbs only.)",
    glyph: "세",
    colorVar: "--type-cmd",
    form: "honorific.command",
    unlockModule: 6,
    verbsOnly: true,
    category: "verb",
    formation: [
      R("Consonant stem", "+ 으세요", "먹다", "먹으세요"),
      R("Vowel stem", "+ 세요", "가다", "가세요"),
      R("ㄹ stem", "ㄹ drops → 세요", "살다", "사세요"),
      R("ㄷ irregular", "ㄷ → ㄹ, then 으세요", "듣다", "들으세요"),
    ],
  },
  {
    id: "adverbial",
    title: "Adverb · -게",
    subtitle: "Turns an adjective into an adverb — “prettily”, “easily”.",
    glyph: "게",
    colorVar: "--type-adv",
    form: "adverbial",
    unlockModule: 6,
    verbsOnly: false,
    category: "adjective",
    formation: [
      R("Rule", "stem + 게 (no stem change)", "예쁘다", "예쁘게"),
      R("Irregulars unaffected", "게 attaches raw", "쉽다", "쉽게"),
    ],
  },
  {
    id: "connective-but",
    title: "But · -지만",
    subtitle: "Contrast — “… but / although …”.",
    glyph: "만",
    colorVar: "--type-but",
    form: "connective.but",
    unlockModule: 7,
    verbsOnly: false,
    category: "verb",
    formation: [
      R("Rule", "stem + 지만 (no stem change)", "먹다", "먹지만"),
      R("Adjectives too", "same rule", "춥다", "춥지만"),
    ],
  },
  {
    id: "connective-so",
    title: "So / because · -아서/어서",
    subtitle: "Sequence + cause — “… so / and then …”.",
    glyph: "서",
    colorVar: "--type-so",
    form: "connective.so",
    unlockModule: 7,
    verbsOnly: false,
    category: "verb",
    formation: [
      R("Rule", "해요체 stem + 서", "먹다", "먹어서"),
      R("Vowel stem", "가 → 가서, 하 → 해서", "하다", "해서"),
      R("Irregulars", "same stem as 해요체", "듣다", "들어서"),
    ],
  },
  {
    id: "conditional",
    title: "If / when · -(으)면",
    subtitle: "Condition — “if / when …”.",
    glyph: "면",
    colorVar: "--type-if",
    form: "conditional",
    unlockModule: 8,
    verbsOnly: false,
    category: "verb",
    formation: [
      R("Consonant stem", "+ 으면", "먹다", "먹으면"),
      R("Vowel stem", "+ 면", "가다", "가면"),
      R("ㄹ stem", "keeps ㄹ + 면", "살다", "살면"),
      R("ㄷ irregular", "ㄷ → ㄹ, then 으면", "듣다", "들으면"),
    ],
  },
  {
    id: "prohibition",
    title: "Don't · -지 마세요",
    subtitle: "Negative command — “please don't …”. (Verbs only.)",
    glyph: "지",
    colorVar: "--type-proh",
    form: "prohibition",
    unlockModule: 8,
    verbsOnly: true,
    category: "verb",
    formation: [
      R("Rule", "stem + 지 마세요", "먹다", "먹지 마세요"),
      R("Irregulars unaffected", "지 attaches raw", "듣다", "듣지 마세요"),
    ],
  },
  {
    id: "present-plain",
    title: "Plain present · -ㄴ다/는다",
    subtitle: "Plain/written declarative — “eats / is eating”. (Verbs only.)",
    glyph: "는",
    colorVar: "--type-plain",
    form: "present.plain",
    unlockModule: 9,
    verbsOnly: true,
    category: "verb",
    formation: [
      R("Consonant stem", "+ 는다", "먹다", "먹는다"),
      R("Vowel stem", "add ㄴ + 다", "가다", "간다"),
      R("ㄹ stem", "ㄹ drops → ㄴ다", "살다", "산다"),
      R("하다", "→ 한다", "공부하다", "공부한다"),
    ],
  },
];

// ─── Sections (hub grouping) + example sentences ─────────────────────────

/** The four learner-facing sections. Order here is the hub's section order. */
const GROUP_SPEECH = "Speech level";
const GROUP_TENSE = "Tense & aspect";
const GROUP_CONNECT = "Connecting";
const GROUP_REQUEST = "Requests & negation";

const TILE_GROUP: Record<string, string> = {
  "present-polite": GROUP_SPEECH,
  "present-casual": GROUP_SPEECH,
  "present-formal": GROUP_SPEECH,
  "present-plain": GROUP_SPEECH,
  past: GROUP_TENSE,
  future: GROUP_TENSE,
  progressive: GROUP_TENSE,
  "connective-and": GROUP_CONNECT,
  "connective-but": GROUP_CONNECT,
  "connective-so": GROUP_CONNECT,
  conditional: GROUP_CONNECT,
  adverbial: GROUP_CONNECT,
  "honorific-command": GROUP_REQUEST,
  prohibition: GROUP_REQUEST,
  desiderative: GROUP_REQUEST,
  negation: GROUP_REQUEST,
};

/** Section render order for the hub. */
const GROUP_ORDER = [GROUP_SPEECH, GROUP_TENSE, GROUP_CONNECT, GROUP_REQUEST];

const ex = (text: string, translation: string): ConjExampleSentence => ({ text, translation });

/** One example sentence per form — the conjugation shown in real use. */
const TILE_EXAMPLE: Record<string, ConjExampleSentence> = {
  "present-polite": ex("저는 커피를 마셔요.", "I drink coffee."),
  "present-casual": ex("지금 뭐 해?", "What are you doing now?"),
  "present-formal": ex("저는 은행에서 일합니다.", "I work at a bank."),
  "present-plain": ex("그는 매일 책을 읽는다.", "He reads a book every day."),
  past: ex("어제 영화를 봤어요.", "I watched a movie yesterday."),
  future: ex("내일 친구를 만날 거예요.", "I'll meet a friend tomorrow."),
  progressive: ex("지금 밥을 먹고 있어요.", "I'm eating right now."),
  "connective-and": ex("밥을 먹고 커피를 마셔요.", "I eat and (then) drink coffee."),
  "connective-but": ex("작지만 좋아요.", "It's small but good."),
  "connective-so": ex("배가 아파서 병원에 가요.", "My stomach hurts, so I'm going to the hospital."),
  conditional: ex("비가 오면 집에 있어요.", "If it rains, I stay home."),
  adverbial: ex("글씨를 예쁘게 써요.", "I write the letters prettily."),
  "honorific-command": ex("여기 앉으세요.", "Please sit here."),
  prohibition: ex("그 물을 마시지 마세요.", "Please don't drink that water."),
  desiderative: ex("물을 마시고 싶어요.", "I want to drink water."),
  negation: ex("저는 고기를 안 먹어요.", "I don't eat meat."),
};

/** "to be big" → "big", "to eat" → "eat" — the bare English gloss. */
function baseMeaning(m: string): string {
  return m.replace(/^to be /i, "").replace(/^to /i, "").trim();
}

/**
 * Build an example FROM the reviewed lemma's own conjugation, so the learner
 * sees their word in use (커요, not a demo word). The Korean side is a short,
 * grammatical sentence built off the correct answer; the English gloss uses
 * the word's meaning + the form's function (kept light — the KO sentence is
 * the point). `correct` is the already-conjugated surface.
 */
function koQuestionExample(
  meaning: string,
  form: KoFormKey,
  isAdj: boolean,
  correct: string,
): ConjExampleSentence {
  const b = baseMeaning(meaning);
  switch (form) {
    case "present.polite":
    case "present.casual":
    case "present.formal":
      return ex(`${correct}.`, isAdj ? `It's ${b}.` : `(I) ${b}.`);
    case "present.plain":
      return ex(`${correct}.`, `(I) ${b}. (plain style)`);
    case "past.polite":
    case "past.casual":
    case "past.formal":
      return ex(`어제 ${correct}.`, isAdj ? `It was ${b} yesterday.` : `(I) ${b} — yesterday.`);
    case "future.polite":
    case "future.casual":
    case "future.formal":
      return ex(`내일 ${correct}.`, `(I) will ${b} tomorrow.`);
    case "progressive.polite":
    case "progressive.casual":
    case "progressive.formal":
      return ex(`지금 ${correct}.`, `(I)'m ${b}-ing right now.`);
    case "neg.short.present.polite":
    case "neg.short.present.casual":
    case "neg.short.past.polite":
    case "neg.long.present.polite":
    case "neg.long.present.formal":
    case "neg.long.past.polite":
      return ex(`${correct}.`, isAdj ? `It isn't ${b}.` : `(I) don't ${b}.`);
    case "desiderative":
      return ex(`${correct}.`, `(I) want to ${b}.`);
    case "prohibition":
      return ex(`${correct}.`, `Please don't ${b}.`);
    case "honorific.command":
      return ex(`${correct}.`, `Please ${b}.`);
    case "connective.and":
      return ex(`${correct} 좋아요.`, isAdj ? `It's ${b} and good.` : `(I) ${b} and it's good.`);
    case "connective.but":
      return ex(`${correct} 괜찮아요.`, isAdj ? `It's ${b}, but it's okay.` : `(I) ${b}, but it's okay.`);
    case "connective.so":
      return ex(`${correct} 좋아요.`, isAdj ? `It's ${b}, so it's good.` : `(I) ${b}, so it's good.`);
    case "conditional":
      return ex(`${correct} 좋아요.`, isAdj ? `If it's ${b}, it's good.` : `If (I) ${b}, it's good.`);
    case "adverbial":
      return ex(`${correct} 말해요.`, `(I) speak in a ${b} way.`);
    default:
      return ex(`${correct}.`, b);
  }
}

const TILE_BY_ID = new Map(KO_TILES.map((t) => [t.id, t]));
// Hub order follows the sections, not the raw tile order.
const TILE_ORDER = [...KO_TILES]
  .sort(
    (a, b) =>
      GROUP_ORDER.indexOf(TILE_GROUP[a.id] ?? "") - GROUP_ORDER.indexOf(TILE_GROUP[b.id] ?? ""),
  )
  .map((t) => t.id);

const FORM_LABELS: Record<string, string> = {
  "present.polite": "해요체 (polite)",
  "present.casual": "반말 (casual)",
  "present.formal": "합쇼체 (formal)",
  "past.polite": "Past (-았/었어요)",
  "future.polite": "Future (-(으)ㄹ 거예요)",
  "progressive.polite": "Progressive (-고 있어요)",
  "neg.short.present.polite": "Negation (안 …)",
  "present.plain": "Plain present (-ㄴ다/는다)",
  adverbial: "Adverb (-게)",
  prohibition: "Don't (-지 마세요)",
  "honorific.command": "Command (-(으)세요)",
  desiderative: "Want to (-고 싶어요)",
  "connective.and": "And (-고)",
  "connective.but": "But (-지만)",
  "connective.so": "So / because (-아서/어서)",
  conditional: "If / when (-(으)면)",
};

// ─── Word-class chip metadata ─────────────────────────────────────────────

const WORD_CLASS: Record<KoStemClass, ConjWordClassInfo> = {
  regular: {
    labelKey: "practice.conjugation.koClassRegular",
    labelDefault: "Regular",
    explainKey: "practice.conjugation.koClassRegularExplain",
    explainDefault:
      "Regular stems take -아 (after ㅏ/ㅗ) or -어; vowel stems contract — 오다 → 와요, 주다 → 줘요.",
    irregular: false,
  },
  hada: {
    labelKey: "practice.conjugation.koClassHada",
    labelDefault: "하다 verb",
    explainKey: "practice.conjugation.koClassHadaExplain",
    explainDefault: "하다 becomes 해 — 공부하다 → 공부해요, 공부했어요.",
    irregular: false,
  },
  p_irr: {
    labelKey: "practice.conjugation.koClassP",
    labelDefault: "ㅂ irregular",
    explainKey: "practice.conjugation.koClassPExplain",
    explainDefault: "Final ㅂ turns into 우 before a vowel ending — 춥다 → 추워요 (돕다 → 도와요).",
    irregular: true,
  },
  t_irr: {
    labelKey: "practice.conjugation.koClassT",
    labelDefault: "ㄷ irregular",
    explainKey: "practice.conjugation.koClassTExplain",
    explainDefault: "Final ㄷ turns into ㄹ before a vowel — 듣다 → 들어요, 걷다 → 걸어요.",
    irregular: true,
  },
  s_irr: {
    labelKey: "practice.conjugation.koClassS",
    labelDefault: "ㅅ irregular",
    explainKey: "practice.conjugation.koClassSExplain",
    explainDefault: "Final ㅅ drops before a vowel (no contraction) — 짓다 → 지어요, 낫다 → 나아요.",
    irregular: true,
  },
  reu_irr: {
    labelKey: "practice.conjugation.koClassReu",
    labelDefault: "르 irregular",
    explainKey: "practice.conjugation.koClassReuExplain",
    explainDefault: "르 adds a ㄹ to the syllable before it — 모르다 → 몰라요, 부르다 → 불러요.",
    irregular: true,
  },
  h_irr: {
    labelKey: "practice.conjugation.koClassH",
    labelDefault: "ㅎ irregular",
    explainKey: "practice.conjugation.koClassHExplain",
    explainDefault: "Final ㅎ drops and the vowel becomes ㅐ — 그렇다 → 그래요, 빨갛다 → 빨개요.",
    irregular: true,
  },
  l_stem: {
    labelKey: "practice.conjugation.koClassL",
    labelDefault: "ㄹ stem",
    explainKey: "practice.conjugation.koClassLExplain",
    explainDefault: "The ㄹ drops before -ㅂ니다/-ㄴ — 살다 → 삽니다 — but stays elsewhere (살아요).",
    irregular: false,
  },
  eu_irr: {
    labelKey: "practice.conjugation.koClassEu",
    labelDefault: "으 irregular",
    explainKey: "practice.conjugation.koClassEuExplain",
    explainDefault: "The final ㅡ drops before a vowel — 쓰다 → 써요, 바쁘다 → 바빠요.",
    irregular: true,
  },
};

// ─── Session building ─────────────────────────────────────────────────────

function poolFor(tile: KoTile, poolModule: number): KoLemma[] {
  const pool = getLemmasUpToModule(poolModule);
  return tile.verbsOnly ? pool.filter((l) => l.pos === "verb") : pool;
}

/** Build one MCQ; pads to 4 options with other lemmas' same-form values when
 *  the rule-misapplication generator returns fewer than 3 distractors. */
function makeQuestion(lemma: KoLemma, form: KoFormKey, pool: KoLemma[]): ConjTrainerQuestion {
  const correct = conjugateKo(lemma.lemma, lemma.cls, form);
  const distractors = generateKoDistractors(lemma.lemma, lemma.cls, form, correct);
  if (distractors.length < 3) {
    const seen = new Set<string>([correct, ...distractors]);
    for (const other of shuffle(pool)) {
      if (other.id === lemma.id) continue;
      const alt = conjugateKo(other.lemma, other.cls, form);
      if (!seen.has(alt)) {
        seen.add(alt);
        distractors.push(alt);
      }
      if (distractors.length >= 3) break;
    }
  }
  return {
    itemId: `${lemma.id}:${form}`,
    prompt: lemma.lemma,
    meaning: lemma.meaning,
    wordClassId: lemma.cls,
    formLabel: FORM_LABELS[form] ?? form,
    form,
    correct,
    options: shuffle([correct, ...distractors.slice(0, 3)]),
    isAdjective: lemma.pos === "adjective",
    example: koQuestionExample(lemma.meaning, form, lemma.pos === "adjective", correct),
  };
}

const MIN_Q = 6;
const MAX_Q = 12;

function toMeta(tile: KoTile): ConjTrainerTypeMeta {
  return {
    id: tile.id,
    title: tile.title,
    subtitle: tile.subtitle,
    category: tile.category,
    group: TILE_GROUP[tile.id],
    // Non-verb-only forms include descriptive verbs (adjectives) in their pool.
    adjective: !tile.verbsOnly,
    example: TILE_EXAMPLE[tile.id],
    glyph: tile.glyph,
    colorVar: tile.colorVar,
    unlockModule: tile.unlockModule,
    formation: tile.formation,
  };
}

function unlockModuleFor(id: string): number {
  return TILE_BY_ID.get(id)?.unlockModule ?? 0;
}

// ─── Scoped CSS (KO palette + shared drill-card ink styles) ───────────────

const KO_SCOPE_CSS = `
.conj-scope {
  --type-haeyo:#047857; --type-banmal:#7c3aed; --type-formal:#1d4ed8;
  --type-past:#b45309; --type-future:#0e7490; --type-prog:#be185d; --type-neg:#b91c1c;
  --type-want:#c2410c; --type-and:#0f766e; --type-cmd:#4338ca; --type-adv:#a16207;
  --type-but:#9f1239; --type-so:#15803d; --type-if:#6d28d9; --type-proh:#be123c;
  --type-plain:#0369a1;
  --type-default:#6b7280;
}
.dark .conj-scope {
  --type-haeyo:#34d399; --type-banmal:#c084fc; --type-formal:#60a5fa;
  --type-past:#fbbf24; --type-future:#22d3ee; --type-prog:#f472b6; --type-neg:#f87171;
  --type-want:#fb923c; --type-and:#2dd4bf; --type-cmd:#818cf8; --type-adv:#facc15;
  --type-but:#fb7185; --type-so:#4ade80; --type-if:#a78bfa; --type-proh:#fda4af;
  --type-plain:#38bdf8;
  --type-default:#9ca3af;
}
.conj-tile-suggest { animation: conj-wobble 4s ease-in-out infinite; }
@keyframes conj-wobble { 2% { transform: rotate(1.1deg); } 4% { transform: rotate(-1.1deg); } 6% { transform: rotate(0); } }
.conj-scope .conj-opt { position: relative; overflow: hidden; }
.conj-scope .conj-opt::before {
  content: ""; position: absolute; left: 0; right: 0; bottom: 0; height: 0;
  background: color-mix(in srgb, var(--fc, rgb(var(--color-accent))) 12%, transparent);
  transition: height 0.16s ease;
}
.conj-scope .conj-opt > * { position: relative; }
.conj-scope .conj-opt:not(:disabled):hover { border-color: var(--fc, rgb(var(--color-accent))); }
.conj-scope .conj-opt:not(:disabled):hover::before { height: 100%; }
.conj-scope .conj-opt-correct { animation: conj-pop 0.3s ease; }
.conj-scope .conj-opt-wrong { animation: conj-shake 0.3s ease; }
.conj-scope .conj-cheat-nudge { animation: conj-shake 0.35s ease, conj-wobble 5s ease-in-out 1s infinite; }
@keyframes conj-pop { 35% { transform: scale(1.04); } 100% { transform: scale(1); } }
@keyframes conj-shake { 20% { transform: translateX(-4px); } 45% { transform: translateX(4px); } 70% { transform: translateX(-2px); } 100% { transform: translateX(0); } }
@media (prefers-reduced-motion: reduce) {
  .conj-tile-suggest, .conj-scope .conj-opt-correct, .conj-scope .conj-opt-wrong, .conj-scope .conj-cheat-nudge { animation: none; }
  .conj-scope .conj-opt::before { transition: none; }
}
`.trim();

// ─── Provider ─────────────────────────────────────────────────────────────

export const koConjugationTrainer: ConjugationTrainerProvider = {
  tileOrder: TILE_ORDER,
  getTypes: () => KO_TILES.map(toMeta),
  getType: (id) => {
    const t = TILE_BY_ID.get(id);
    return t ? toMeta(t) : undefined;
  },

  scopeCss: KO_SCOPE_CSS,
  glyph: (id) => TILE_BY_ID.get(id)?.glyph ?? "",
  // Fallback resolves to a standalone-hex `--type-*` var so `var(${colorVar})`
  // stays a valid color (post-W1 `--color-accent` is a bare channel triple).
  colorVar: (id) => TILE_BY_ID.get(id)?.colorVar ?? "--type-default",
  mixGlyphs: KO_TILES.slice(0, 5).map((t) => ({ glyph: t.glyph, colorVar: t.colorVar })),

  wordClass: (id) =>
    WORD_CLASS[id as KoStemClass] ?? {
      labelKey: `practice.conjugation.koClass${id}`,
      labelDefault: id,
      explainKey: `practice.conjugation.koClass${id}Explain`,
      explainDefault: "",
      irregular: false,
    },

  // KO has no second script (Hangul is phonetic) — always plain.
  secondScriptExposureModule: undefined,
  renderSurface: (_question, surface) => [{ text: surface }],

  isTypeUnlocked: (id, reachedModule) => reachedModule >= unlockModuleFor(id),
  isSelectionAhead: (ids, reachedModule) =>
    ids.some((id) => reachedModule < unlockModuleFor(id)),
  effectivePoolModule: (ids, reachedModule) =>
    Math.max(reachedModule, ...ids.map((id) => unlockModuleFor(id)), 0),

  // Combos not authored for KO in Phase 1 — the hub degrades to free-mix.
  supportsCombos: false,
  combosForSelection: () => [],
  canExtendSelection: () => true,
  missingComboTiles: () => null,
  formToTiles: (form) => {
    const tile = KO_TILES.find((t) => t.form === form);
    return tile ? [tile.id] : undefined;
  },
  individualFormCount: (ids) => new Set(ids).size,

  buildSession: (typeId, poolModule) => {
    const tile = TILE_BY_ID.get(typeId);
    if (!tile) return [];
    const pool = poolFor(tile, poolModule);
    if (pool.length === 0) return [];
    const target = clamp(pool.length, MIN_Q, MAX_Q);
    const shuffled = shuffle(pool);
    return Array.from({ length: target }, (_, i) =>
      makeQuestion(shuffled[i % shuffled.length], tile.form, pool),
    );
  },
  buildCombinedSession: (typeIds, poolModule) => {
    const tiles = typeIds
      .map((id) => TILE_BY_ID.get(id))
      .filter((t): t is KoTile => !!t);
    if (tiles.length === 0) return [];
    const factories: QuestionFactory<ConjTrainerQuestion>[] = tiles.map((tile) => {
      const pool = poolFor(tile, poolModule);
      return {
        form: tile.form,
        pool,
        make: (item) => makeQuestion(item as KoLemma, tile.form, pool),
      };
    });
    const target = clamp(12, 8, 14);
    return roundRobinBuild(factories, target);
  },

  // Phase 1: no Track-B SRS for KO. Mastery/due are neutral.
  typeMasteryPercent: () => 0,
  dueCount: () => 0,

  // TODO(Phase 2): wire KO Track-B grammar SRS (generalize grammarSrs.ts off
  // JA_COURSE_ATOMS + add ko-grammar-points.json). Until then KO drills are
  // reached-module gated and write no review schedule.
  gradeSessionIfOnPath: (typeId, reachedModule) =>
    reachedModule >= unlockModuleFor(typeId),
  gradeCombinedSessionIfOnPath: (typeIds, reachedModule) =>
    !typeIds.some((id) => reachedModule < unlockModuleFor(id)),

  cheatItems: (typeId, reachedModule): ConjCheatItem[] => {
    const tile = TILE_BY_ID.get(typeId);
    if (!tile) return [];
    return poolFor(tile, reachedModule)
      .slice(0, 8)
      .map((l) => ({ dict: l.lemma, form: conjugateKo(l.lemma, l.cls, tile.form) }));
  },

  getIntroStep: () => null,

  // freeDrill omitted — Mix tile hidden for KO in Phase 1.
};

export { KO_LEMMAS };

registerConjugationTrainer("ko", koConjugationTrainer);
